INSERT INTO "public"."questions" ("topic_id", "question_number", "question_type", "category", "question", "option_a", "option_b", "option_c", "option_d", "correct_answer", "hint", "explanation", "tags", "sources") VALUES

-- Questions for 2025-03-24-ap-gulf-mexico-lawsuit (Multiple Choice - 17 questions)
('2025-03-24-ap-gulf-mexico-lawsuit', 1, 'multiple_choice', 'Media', 'What news organization filed a lawsuit challenging the Gulf of Mexico name change?', 'Reuters', 'Associated Press', 'CNN', 'New York Times', 'Associated Press', 'This news cooperative provides reporting to member newspapers and broadcasters.', 'The Associated Press (AP) filed a lawsuit challenging the Trump administration\'s executive order renaming the Gulf of Mexico to "Gulf of America." The AP argues this creates confusion in geographic reporting and violates established naming conventions for journalistic accuracy.', '["Associated Press", "lawsuit", "Gulf of Mexico"]', '[{"name": "Associated Press - Official Website", "url": "https://www.ap.org/"}, {"name": "Federal Court Filing - AP v. Trump Administration", "url": "https://www.courtlistener.com/docket/federal-court-filings/"}, {"name": "Reuters - AP Lawsuit Coverage", "url": "https://www.reuters.com/world/us/ap-gulf-mexico-lawsuit/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 2, 'multiple_choice', 'Constitutional Law', 'What type of presidential action was used to rename the Gulf of Mexico?', 'Congressional legislation', 'Executive order', 'Supreme Court ruling', 'Interstate compact', 'Executive order', 'This type of presidential directive doesn\'t require congressional approval.', 'The Trump administration used an executive order to rename the Gulf of Mexico to "Gulf of America." Executive orders are presidential directives that have the force of law but do not require congressional approval, though they can be challenged in federal court.', '["executive order", "presidential directive", "administrative action"]', '[{"name": "Federal Register - Executive Orders", "url": "https://www.federalregister.gov/presidential-documents/executive-orders"}, {"name": "Congressional Research Service - Executive Order Authority", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}, {"name": "American Presidency Project - Executive Orders", "url": "https://www.presidency.ucsb.edu/documents/presidential-documents-archive-guidebook/executive-orders"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 3, 'multiple_choice', 'Government', 'What federal agency typically oversees geographic naming in the United States?', 'Federal Communications Commission', 'U.S. Board on Geographic Names', 'National Archives', 'Library of Congress', 'U.S. Board on Geographic Names', 'This federal board has statutory authority over geographic nomenclature.', 'The U.S. Board on Geographic Names, housed within the U.S. Geological Survey, has statutory authority to establish and maintain uniform geographic name usage throughout the federal government. The board standardizes geographic names for federal use and publication.', '["U.S. Board on Geographic Names", "geographic naming", "federal authority"]', '[{"name": "U.S. Board on Geographic Names", "url": "https://www.usgs.gov/us-board-on-geographic-names"}, {"name": "Geographic Names Information System", "url": "https://www.usgs.gov/core-science-systems/ngp/board-on-geographic-names"}, {"name": "Federal Geographic Data Committee", "url": "https://www.fgdc.gov/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 4, 'multiple_choice', 'Constitutional Law', 'What constitutional principle is involved when the federal government names geographic features?', 'Due Process Clause', 'Commerce Clause and federal supremacy', 'Equal Protection Clause', 'Second Amendment', 'Commerce Clause and federal supremacy', 'Federal authority over interstate waters derives from constitutional commerce powers.', 'Federal geographic naming authority derives from the Commerce Clause and federal supremacy over interstate and international waters. The Constitution grants Congress power to regulate interstate commerce, including navigation and naming of waters that cross state boundaries.', '["Commerce Clause", "federal supremacy", "interstate commerce"]', '[{"name": "Supreme Court - Commerce Clause Cases", "url": "https://supreme.justia.com/cases/federal/commerce-clause/"}, {"name": "Congressional Research Service - Commerce Clause Analysis", "url": "https://crsreports.congress.gov/product/pdf/R/R45129"}, {"name": "Constitution Annotated - Commerce Power", "url": "https://constitution.congress.gov/browse/essay/artI-S8-C3-1/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 5, 'multiple_choice', 'Media', 'How do geographic name changes affect news reporting accuracy?', 'They have no effect on reporting', 'They create confusion and complicate accurate geographic references', 'They improve reporting quality', 'They only affect local news', 'They create confusion and complicate accurate geographic references', 'Consistent geographic names are essential for clear communication.', 'Geographic name changes create confusion and complicate accurate geographic references in news reporting. Media organizations rely on standardized geographic names to ensure clarity and consistency in reporting locations for national and international audiences.', '["news reporting", "geographic accuracy", "media standards"]', '[{"name": "Associated Press Stylebook - Geographic Names", "url": "https://www.apstylebook.com/"}, {"name": "Society of Professional Journalists - Ethics Code", "url": "https://www.spj.org/ethicscode.asp"}, {"name": "Poynter Institute - Journalism Standards", "url": "https://www.poynter.org/ethics-guidelines/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 6, 'multiple_choice', 'Constitutional Law', 'What legal standard applies to challenges of executive orders?', 'Rational basis review', 'Administrative Procedure Act requirements and constitutional limits', 'No judicial review allowed', 'Presidential immunity', 'Administrative Procedure Act requirements and constitutional limits', 'Executive orders must comply with legal procedures and constitutional limits.', 'Challenges to executive orders are reviewed under Administrative Procedure Act requirements and constitutional limits. Courts examine whether the order exceeds presidential authority, follows proper procedures, and complies with constitutional restrictions on executive power.', '["Administrative Procedure Act", "executive order review", "constitutional limits"]', '[{"name": "Administrative Procedure Act - Legal Information Institute", "url": "https://www.law.cornell.edu/wex/administrative_procedure_act"}, {"name": "Supreme Court - Executive Order Review", "url": "https://supreme.justia.com/cases/federal/executive-power/"}, {"name": "Congressional Research Service - APA Analysis", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 7, 'multiple_choice', 'Government', 'What international implications exist for unilateral geographic name changes?', 'No international implications', 'Potential conflicts with international naming conventions and treaties', 'Automatic international acceptance', 'Only affects domestic policy', 'Potential conflicts with international naming conventions and treaties', 'Geographic names often involve international coordination and treaties.', 'Unilateral geographic name changes can create conflicts with international naming conventions, treaties, and diplomatic protocols. International bodies like the United Nations Group of Experts on Geographical Names work to standardize geographic nomenclature for global consistency.', '["international naming", "treaties", "diplomatic implications"]', '[{"name": "United Nations Group of Experts on Geographical Names", "url": "https://unstats.un.org/unsd/ungegn/"}, {"name": "International Hydrographic Organization", "url": "https://iho.int/"}, {"name": "U.S. Department of State - Geographic Names Policy", "url": "https://www.state.gov/policy-issues/geographic-names/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 8, 'multiple_choice', 'Constitutional Law', 'How does the separation of powers apply to geographic naming authority?', 'Only the president can name geographic features', 'Congress, executive agencies, and courts all have roles in geographic policy', 'Only Congress has naming authority', 'States have exclusive naming rights', 'Congress, executive agencies, and courts all have roles in geographic policy', 'Multiple branches and levels of government have different roles.', 'Separation of powers in geographic naming involves Congress (legislative authority), executive agencies like the Board on Geographic Names (implementation), and courts (review of legal challenges). This creates checks and balances on naming decisions.', '["separation of powers", "geographic policy", "checks and balances"]', '[{"name": "Congressional Research Service - Separation of Powers", "url": "https://crsreports.congress.gov/product/pdf/R/R42733"}, {"name": "Supreme Court - Administrative Authority", "url": "https://supreme.justia.com/cases/federal/administrative-law/"}, {"name": "U.S. Geological Survey - Board Authority", "url": "https://www.usgs.gov/us-board-on-geographic-names"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 9, 'multiple_choice', 'Media', 'What First Amendment concerns arise from government geographic naming decisions?', 'No First Amendment issues exist', 'Government control over information and compelled speech concerns', 'Enhanced free speech protections', 'Only applies to private property', 'Government control over information and compelled speech concerns', 'Forcing media to use government-mandated names raises free speech questions.', 'Government geographic naming decisions raise First Amendment concerns about government control over information and potential compelled speech when media organizations are pressured to use official names that may not reflect journalistic standards for accuracy and clarity.', '["First Amendment", "compelled speech", "government control"]', '[{"name": "Supreme Court - Compelled Speech Cases", "url": "https://supreme.justia.com/cases/federal/first-amendment/"}, {"name": "First Amendment Law Review", "url": "https://firstamendmentlawreview.org/"}, {"name": "Congressional Research Service - First Amendment Analysis", "url": "https://crsreports.congress.gov/product/pdf/R/R45650"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 10, 'multiple_choice', 'Government', 'What statutory authority governs federal geographic naming?', 'No specific statutory authority exists', 'Geographic Names Act and related federal laws', 'Presidential prerogative only', 'State geography laws', 'Geographic Names Act and related federal laws', 'Federal law establishes specific procedures for geographic naming.', 'Federal geographic naming is governed by the Geographic Names Act and related laws that establish the U.S. Board on Geographic Names, set procedures for naming decisions, and define federal authority over geographic nomenclature for official government use.', '["Geographic Names Act", "federal law", "statutory authority"]', '[{"name": "U.S. Code - Geographic Names Act", "url": "https://www.law.cornell.edu/uscode/text/43/364"}, {"name": "U.S. Board on Geographic Names - Legal Authority", "url": "https://www.usgs.gov/us-board-on-geographic-names/domestic-names"}, {"name": "Congressional Research Service - Geographic Naming Law", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 11, 'multiple_choice', 'Constitutional Law', 'What judicial review standard applies to presidential executive orders?', 'No judicial review allowed', 'Courts review for constitutional authority and procedural compliance', 'Complete judicial deference', 'State court review only', 'Courts review for constitutional authority and procedural compliance', 'Federal courts can review executive orders for legal compliance.', 'Federal courts review presidential executive orders to determine whether they exceed constitutional authority, comply with statutory requirements, and follow proper administrative procedures. Courts do not defer automatically to presidential decisions that may violate legal limits.', '["judicial review", "executive orders", "constitutional authority"]', '[{"name": "Supreme Court - Executive Power Limits", "url": "https://supreme.justia.com/cases/federal/executive-power/"}, {"name": "Administrative Law - Executive Review", "url": "https://www.law.cornell.edu/wex/administrative_law"}, {"name": "Congressional Research Service - Judicial Review", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 12, 'multiple_choice', 'Government', 'How do state governments typically respond to federal geographic naming decisions?', 'States must automatically adopt federal names', 'States may use different names for their own purposes', 'States have no role in geographic naming', 'Only federal names are legally valid', 'States may use different names for their own purposes', 'States retain some autonomy over geographic names within their jurisdiction.', 'States may use different geographic names for their own purposes while federal agencies use official federal names. This creates a federal system where different levels of government may have different naming conventions for the same geographic features.', '["state government", "federalism", "geographic naming"]', '[{"name": "Council of State Governments - Geographic Policy", "url": "https://www.csg.org/"}, {"name": "National Conference of State Legislatures", "url": "https://www.ncsl.org/"}, {"name": "U.S. Geological Survey - Federal-State Coordination", "url": "https://www.usgs.gov/us-board-on-geographic-names"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 13, 'multiple_choice', 'Media', 'What professional standards guide news organizations in using geographic names?', 'Government mandates only', 'Professional style guides and accuracy standards', 'Personal preference of reporters', 'Social media trends', 'Professional style guides and accuracy standards', 'Media organizations follow established professional standards for accuracy.', 'News organizations follow professional style guides like the Associated Press Stylebook and accuracy standards that prioritize clarity, consistency, and reader understanding over government mandates when reporting geographic names and locations.', '["professional standards", "style guides", "journalistic accuracy"]', '[{"name": "Associated Press Stylebook", "url": "https://www.apstylebook.com/"}, {"name": "Society of Professional Journalists", "url": "https://www.spj.org/"}, {"name": "Poynter Institute - Ethics Guidelines", "url": "https://www.poynter.org/ethics-guidelines/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 14, 'multiple_choice', 'Constitutional Law', 'What constitutional limitation might apply to arbitrary geographic naming changes?', 'No constitutional limitations exist', 'Due process requirements for rational decision-making', 'Second Amendment restrictions', 'Commerce Clause expansion', 'Due process requirements for rational decision-making', 'Government actions must meet basic rationality standards.', 'Due process requirements may limit arbitrary geographic naming changes by requiring rational decision-making based on legitimate government purposes rather than personal or political motivations that lack justification in law or policy.', '["due process", "rational decision-making", "constitutional limits"]', '[{"name": "Supreme Court - Due Process Cases", "url": "https://supreme.justia.com/cases/federal/due-process/"}, {"name": "Constitutional Law - Due Process Analysis", "url": "https://www.law.cornell.edu/wex/due_process"}, {"name": "Congressional Research Service - Constitutional Limits", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 15, 'multiple_choice', 'Government', 'What role do federal courts play in geographic naming disputes?', 'Courts cannot review naming decisions', 'Courts review legal authority and procedural compliance', 'Courts make original naming decisions', 'Only state courts have jurisdiction', 'Courts review legal authority and procedural compliance', 'Federal courts have jurisdiction over federal administrative actions.', 'Federal courts review geographic naming disputes to determine whether naming decisions comply with statutory authority, follow proper procedures, and stay within constitutional limits. Courts do not typically make original naming decisions but review the legality of government actions.', '["federal courts", "judicial review", "administrative law"]', '[{"name": "Federal Courts - Administrative Review", "url": "https://www.uscourts.gov/about-federal-courts"}, {"name": "Administrative Procedure Act", "url": "https://www.law.cornell.edu/wex/administrative_procedure_act"}, {"name": "Congressional Research Service - Court Jurisdiction", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 16, 'multiple_choice', 'Constitutional Law', 'How does federalism affect geographic naming authority?', 'Only federal government can name features', 'Different levels of government have different naming roles', 'Only state governments have authority', 'No government can name geographic features', 'Different levels of government have different naming roles', 'Federalism creates shared and separate authorities between government levels.', 'Federalism in geographic naming creates different roles for federal, state, and local governments. Federal government typically names interstate features, while states and localities may name features within their jurisdiction, creating overlapping but distinct naming authorities.', '["federalism", "shared authority", "government levels"]', '[{"name": "Congressional Research Service - Federalism", "url": "https://crsreports.congress.gov/product/pdf/R/R42733"}, {"name": "National Conference of State Legislatures - Federal Relations", "url": "https://www.ncsl.org/research/about-state-legislatures/federalism.aspx"}, {"name": "Council of State Governments", "url": "https://www.csg.org/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 17, 'multiple_choice', 'Media', 'What precedent exists for news organizations challenging government naming decisions?', 'No precedent exists', 'Various First Amendment and access cases involving government information', 'Automatic media compliance required', 'Only international cases exist', 'Various First Amendment and access cases involving government information', 'Media organizations have challenged government control over information.', 'Precedent exists for news organizations challenging government naming and information decisions under First Amendment principles, freedom of information laws, and professional journalism standards that prioritize accuracy and independence from government mandates.', '["media precedent", "First Amendment cases", "journalism independence"]', '[{"name": "Reporters Committee for Freedom of the Press", "url": "https://www.rcfp.org/"}, {"name": "First Amendment Law Review", "url": "https://firstamendmentlawreview.org/"}, {"name": "Society of Professional Journalists - Legal Defense", "url": "https://www.spj.org/ldf.asp"}]'),

-- True/False Questions (5 questions)
('2025-03-24-ap-gulf-mexico-lawsuit', 18, 'true_false', 'Constitutional Law', 'The President has unlimited authority to rename any geographic feature by executive order.', '', '', '', '', 'False', 'Presidential power is limited by law, constitutional authority, and existing statutory frameworks.', 'False. Presidential authority to rename geographic features is limited by statutory requirements, constitutional bounds, and existing legal frameworks. The U.S. Board on Geographic Names has specific statutory authority, and courts can review executive orders for legal compliance.', '["presidential authority", "executive limits", "statutory requirements"]', '[{"name": "U.S. Code - Geographic Names Act", "url": "https://www.law.cornell.edu/uscode/text/43/364"}, {"name": "Congressional Research Service - Executive Power Limits", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}, {"name": "Supreme Court - Administrative Authority", "url": "https://supreme.justia.com/cases/federal/administrative-law/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 19, 'true_false', 'Media', 'News organizations must use whatever geographic names the federal government mandates.', '', '', '', '', 'False', 'Media organizations have editorial independence and professional standards.', 'False. News organizations have editorial independence and follow professional journalism standards that prioritize accuracy and clarity. While they may note official names, they are not required to abandon established geographic terms that serve journalistic accuracy and reader understanding.', '["media independence", "editorial freedom", "professional standards"]', '[{"name": "First Amendment - Press Freedom", "url": "https://www.law.cornell.edu/constitution/first_amendment"}, {"name": "Associated Press Stylebook", "url": "https://www.apstylebook.com/"}, {"name": "Society of Professional Journalists - Ethics", "url": "https://www.spj.org/ethicscode.asp"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 20, 'true_false', 'Government', 'The U.S. Board on Geographic Names has statutory authority over federal geographic naming.', '', '', '', '', 'True', 'Federal law establishes this board\'s authority over geographic nomenclature.', 'True. The U.S. Board on Geographic Names has statutory authority under federal law to establish and maintain uniform geographic name usage throughout the federal government and standardize geographic names for federal use and publication.', '["Board on Geographic Names", "statutory authority", "federal law"]', '[{"name": "U.S. Board on Geographic Names", "url": "https://www.usgs.gov/us-board-on-geographic-names"}, {"name": "Geographic Names Act", "url": "https://www.law.cornell.edu/uscode/text/43/364"}, {"name": "U.S. Geological Survey - Naming Authority", "url": "https://www.usgs.gov/core-science-systems/ngp/board-on-geographic-names"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 21, 'true_false', 'Constitutional Law', 'Federal courts can review the legality of presidential executive orders.', '', '', '', '', 'True', 'Judicial review is a fundamental check on executive power.', 'True. Federal courts have constitutional authority to review presidential executive orders for compliance with statutory requirements, constitutional limits, and proper administrative procedures. Judicial review serves as a check on executive power.', '["judicial review", "executive orders", "constitutional checks"]', '[{"name": "Supreme Court - Executive Power Cases", "url": "https://supreme.justia.com/cases/federal/executive-power/"}, {"name": "Administrative Procedure Act", "url": "https://www.law.cornell.edu/wex/administrative_procedure_act"}, {"name": "Congressional Research Service - Judicial Review", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 22, 'true_false', 'Government', 'Geographic name changes have no impact on international relations or treaties.', '', '', '', '', 'False', 'Geographic names often involve international coordination and diplomatic considerations.', 'False. Geographic name changes can significantly impact international relations and treaties, especially for shared waters and boundaries. International bodies work to coordinate geographic naming, and unilateral changes can create diplomatic complications.', '["international relations", "treaties", "diplomatic impact"]', '[{"name": "United Nations Group of Experts on Geographical Names", "url": "https://unstats.un.org/unsd/ungegn/"}, {"name": "U.S. Department of State - Geographic Policy", "url": "https://www.state.gov/policy-issues/geographic-names/"}, {"name": "International Hydrographic Organization", "url": "https://iho.int/"}]'),

-- Short Answer Questions (3 questions)
('2025-03-24-ap-gulf-mexico-lawsuit', 23, 'short_answer', 'Media', 'What news organization filed a lawsuit challenging the Gulf of Mexico name change?', '', '', '', '', 'Associated Press', 'This news cooperative is known by its initials AP.', 'The Associated Press (AP) filed a lawsuit challenging the Trump administration\'s executive order renaming the Gulf of Mexico to "Gulf of America." The AP argued this creates confusion in geographic reporting and conflicts with established journalistic standards.', '["Associated Press", "AP", "news organization"]', '[{"name": "Associated Press", "url": "https://www.ap.org/"}, {"name": "Federal Court Documents", "url": "https://www.courtlistener.com/docket/"}, {"name": "Reuters - Lawsuit Coverage", "url": "https://www.reuters.com/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 24, 'short_answer', 'Government', 'What federal board has statutory authority over geographic naming in the United States?', '', '', '', '', 'U.S. Board on Geographic Names', 'This board is housed within the U.S. Geological Survey.', 'The U.S. Board on Geographic Names has statutory authority to establish and maintain uniform geographic name usage throughout the federal government. The board standardizes geographic names for federal use and publication.', '["U.S. Board on Geographic Names", "geographic naming", "federal authority"]', '[{"name": "U.S. Board on Geographic Names", "url": "https://www.usgs.gov/us-board-on-geographic-names"}, {"name": "Geographic Names Act", "url": "https://www.law.cornell.edu/uscode/text/43/364"}, {"name": "U.S. Geological Survey", "url": "https://www.usgs.gov/"}]'),

('2025-03-24-ap-gulf-mexico-lawsuit', 25, 'short_answer', 'Constitutional Law', 'What type of presidential action was used to rename the Gulf of Mexico?', '', '', '', '', 'Executive order', 'This type of presidential directive has the force of law but doesn\'t require congressional approval.', 'The Trump administration used an executive order to rename the Gulf of Mexico to "Gulf of America." Executive orders are presidential directives that have the force of law but can be challenged in federal court for legal compliance.', '["executive order", "presidential directive", "administrative action"]', '[{"name": "Federal Register - Executive Orders", "url": "https://www.federalregister.gov/presidential-documents/executive-orders"}, {"name": "Congressional Research Service - Executive Orders", "url": "https://crsreports.congress.gov/product/pdf/R/R46707"}, {"name": "Administrative Law Guide", "url": "https://www.law.cornell.edu/wex/administrative_law"}]');