INSERT INTO "public"."questions" ("topic_id", "question_number", "question_type", "category", "question", "option_a", "option_b", "option_c", "option_d", "correct_answer", "hint", "explanation", "tags", "sources") VALUES

-- Questions for 2025-04-11-military-parade-planning (Multiple Choice - 17 questions)
('2025-04-11-military-parade-planning', 1, 'multiple_choice', 'Government', 'What constitutional authority does the President have over military ceremonial activities?', 'No constitutional authority', 'Commander-in-Chief powers', 'Congressional approval required', 'State government authorization needed', 'Commander-in-Chief powers', 'Article II establishes the President as Commander-in-Chief.', 'The President has constitutional authority over military ceremonial activities through Commander-in-Chief powers established in Article II, Section 2. This includes directing military participation in parades, ceremonies, and other official events as part of executive authority over the armed forces.', '["Commander-in-Chief", "constitutional authority", "military ceremonies"]', '[{"name": "Constitution - Commander-in-Chief Clause", "url": "https://constitution.congress.gov/browse/essay/artII-S2-C1-1/"}, {"name": "Congressional Research Service - Presidential Military Authority", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}, {"name": "Department of Defense - Ceremonial Guidelines", "url": "https://www.defense.gov/News/ceremonial/"}]'),

('2025-04-11-military-parade-planning', 2, 'multiple_choice', 'Government', 'How are military parades typically funded?', 'Private donations exclusively', 'Federal defense budget and appropriated funds', 'State government funding', 'International contributions', 'Federal defense budget and appropriated funds', 'Military activities are funded through congressional appropriations.', 'Military parades are typically funded through the federal defense budget using appropriated funds. Congress controls spending through the budget process, and significant parade costs would require either existing defense appropriations or additional congressional funding authorization.', '["federal funding", "defense budget", "congressional appropriations"]', '[{"name": "Congressional Budget Office - Defense Spending", "url": "https://www.cbo.gov/topics/defense-and-national-security"}, {"name": "Government Accountability Office - Military Spending", "url": "https://www.gao.gov/products/military-spending"}, {"name": "Congressional Research Service - Defense Appropriations", "url": "https://crsreports.congress.gov/product/pdf/R/R46928"}]'),

('2025-04-11-military-parade-planning', 3, 'multiple_choice', 'Government', 'What role does Congress play in military parade authorization?', 'No congressional role', 'Budget approval and oversight authority', 'Direct operational command', 'International treaty approval', 'Budget approval and oversight authority', 'Congress controls federal spending and provides oversight.', 'Congress plays a role in military parade authorization through budget approval for significant costs, oversight of military activities, and its constitutional authority over federal spending. Large-scale parades would likely require congressional funding approval and oversight.', '["congressional oversight", "budget authority", "spending approval"]', '[{"name": "Congressional Research Service - Congressional Oversight", "url": "https://crsreports.congress.gov/product/pdf/R/R45442"}, {"name": "House Armed Services Committee", "url": "https://armedservices.house.gov/"}, {"name": "Senate Armed Services Committee", "url": "https://www.armed-services.senate.gov/"}]'),

('2025-04-11-military-parade-planning', 4, 'multiple_choice', 'Government', 'What security considerations affect military parade planning?', 'No security considerations needed', 'Crowd control, venue security, and threat assessment', 'Only international diplomacy concerns', 'State police handle all security', 'Crowd control, venue security, and threat assessment', 'Large public events require comprehensive security planning.', 'Military parade planning involves extensive security considerations including crowd control, venue security, threat assessment, coordination between federal and local law enforcement, and protection of high-profile officials and military assets during public display.', '["security planning", "threat assessment", "crowd control"]', '[{"name": "Department of Homeland Security - Event Security", "url": "https://www.dhs.gov/topic/special-event-security"}, {"name": "Secret Service - Protective Operations", "url": "https://www.secretservice.gov/protection/"}, {"name": "Congressional Research Service - Event Security", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-04-11-military-parade-planning', 5, 'multiple_choice', 'Civic Participation', 'How do military parades differ from political campaign events?', 'They are identical in purpose', 'Military parades are official government ceremonies, not partisan political events', 'Only campaign events require permits', 'Military parades are privately funded', 'Military parades are official government ceremonies, not partisan political events', 'Government ceremonies should be nonpartisan official functions.', 'Military parades differ from political campaign events because they are official government ceremonies funded by taxpayers and conducted by federal military forces, rather than partisan political events. They should serve national rather than partisan political purposes.', '["official ceremonies", "nonpartisan government", "public purpose"]', '[{"name": "Office of Government Ethics - Political Activities", "url": "https://www.oge.gov/Web/oge.nsf/Resources/Political+Activities"}, {"name": "Hatch Act Guidelines", "url": "https://osc.gov/Services/Pages/HatchAct.aspx"}, {"name": "Congressional Research Service - Government Ceremonies", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

('2025-04-11-military-parade-planning', 6, 'multiple_choice', 'Government', 'What logistical challenges do large military parades present?', 'No logistical challenges exist', 'Transportation, coordination, equipment movement, and personnel management', 'Only catering arrangements', 'Simple scheduling requirements', 'Transportation, coordination, equipment movement, and personnel management', 'Large-scale military events require complex coordination.', 'Large military parades present significant logistical challenges including transporting personnel and equipment from multiple bases, coordinating between different military branches, managing parade route logistics, and ensuring proper timing and safety for complex operations.', '["logistical coordination", "equipment transport", "multi-branch cooperation"]', '[{"name": "Department of Defense - Logistics", "url": "https://www.defense.gov/News/logistics/"}, {"name": "Joint Chiefs of Staff - Operations", "url": "https://www.jcs.mil/"}, {"name": "Congressional Research Service - Military Operations", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

('2025-04-11-military-parade-planning', 7, 'multiple_choice', 'Constitutional Law', 'What limits exist on using military forces for domestic ceremonies?', 'No limits on military use', 'Posse Comitatus Act and constitutional restrictions on domestic military use', 'Complete prohibition of military ceremonies', 'Only state approval required', 'Posse Comitatus Act and constitutional restrictions on domestic military use', 'Federal law limits domestic military activities.', 'The Posse Comitatus Act and constitutional principles limit using military forces for domestic law enforcement but generally allow ceremonial activities. However, large military displays raise questions about appropriate use of armed forces for domestic political purposes.', '["Posse Comitatus Act", "domestic military use", "constitutional limits"]', '[{"name": "Posse Comitatus Act", "url": "https://www.law.cornell.edu/uscode/text/18/1385"}, {"name": "Congressional Research Service - Posse Comitatus", "url": "https://crsreports.congress.gov/product/pdf/R/R42659"}, {"name": "Department of Defense - Domestic Operations", "url": "https://www.defense.gov/News/domestic-operations/"}]'),

('2025-04-11-military-parade-planning', 8, 'multiple_choice', 'Government', 'How do military parades affect diplomatic relations?', 'No diplomatic impact', 'Can signal military strength or be perceived as aggressive displays', 'Only improve international relations', 'Have no international significance', 'Can signal military strength or be perceived as aggressive displays', 'Military displays send messages to international audiences.', 'Military parades can significantly affect diplomatic relations by signaling military strength, demonstrating national power, or being perceived as aggressive displays that may concern allies or adversaries, influencing international perceptions of U.S. intentions and capabilities.', '["diplomatic signaling", "military strength", "international perceptions"]', '[{"name": "Council on Foreign Relations", "url": "https://www.cfr.org/"}, {"name": "State Department - Public Diplomacy", "url": "https://www.state.gov/bureaus-offices/under-secretary-for-public-diplomacy-and-public-affairs/"}, {"name": "Congressional Research Service - Military Diplomacy", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

('2025-04-11-military-parade-planning', 9, 'multiple_choice', 'Government', 'What oversight mechanisms exist for military parade costs?', 'No oversight mechanisms', 'Congressional budget oversight and GAO auditing', 'Only military internal review', 'State government oversight', 'Congressional budget oversight and GAO auditing', 'Federal spending is subject to congressional oversight and auditing.', 'Military parade costs are subject to oversight through congressional budget review, Government Accountability Office auditing, Inspector General investigations, and public transparency requirements for federal spending, ensuring accountability for taxpayer funds.', '["congressional oversight", "GAO auditing", "fiscal accountability"]', '[{"name": "Government Accountability Office", "url": "https://www.gao.gov/"}, {"name": "Congressional Budget Office", "url": "https://www.cbo.gov/"}, {"name": "Department of Defense Inspector General", "url": "https://www.dodig.mil/"}]'),

('2025-04-11-military-parade-planning', 10, 'multiple_choice', 'Civic Participation', 'How should citizens evaluate the appropriateness of military parades?', 'Accept all government decisions without question', 'Consider purpose, cost, precedent, and constitutional principles', 'Only focus on entertainment value', 'Ignore cost considerations completely', 'Consider purpose, cost, precedent, and constitutional principles', 'Citizens should critically evaluate government activities using multiple criteria.', 'Citizens should evaluate military parades by considering their stated purpose, cost to taxpayers, historical precedent, constitutional appropriateness, opportunity costs of military resources, and whether they serve legitimate public rather than partisan political purposes.', '["critical evaluation", "civic responsibility", "government accountability"]', '[{"name": "American Democracy Project", "url": "https://www.aascu.org/programs/adp/"}, {"name": "Center for Civic Education", "url": "https://www.civiced.org/"}, {"name": "Congressional Research Service - Civic Participation", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-04-11-military-parade-planning', 11, 'multiple_choice', 'Government', 'What precedents exist for large military parades in the United States?', 'Regular annual military parades', 'Occasional parades for specific events like victory celebrations', 'No military parades in U.S. history', 'Monthly military displays', 'Occasional parades for specific events like victory celebrations', 'U.S. has limited tradition of large military parades.', 'The United States has limited precedents for large military parades, primarily for specific occasions like victory celebrations after major wars, inaugural parades, or bicentennial celebrations, unlike some countries with regular military parade traditions.', '["historical precedent", "victory celebrations", "limited tradition"]', '[{"name": "National Archives - Military History", "url": "https://www.archives.gov/research/military"}, {"name": "American Military History", "url": "https://history.army.mil/"}, {"name": "Congressional Research Service - Military Traditions", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

('2025-04-11-military-parade-planning', 12, 'multiple_choice', 'Government', 'How do military parades affect military readiness and training?', 'Always improve military readiness', 'Can divert resources from training and operational readiness', 'Have no effect on military operations', 'Only enhance combat capabilities', 'Can divert resources from training and operational readiness', 'Large ceremonies require significant military resources and time.', 'Military parades can affect readiness by diverting personnel, equipment, and resources from training and operational activities. The time and effort required for parade preparation and execution represents opportunity costs for other military priorities.', '["military readiness", "resource allocation", "opportunity costs"]', '[{"name": "Department of Defense - Readiness Reports", "url": "https://www.defense.gov/News/readiness/"}, {"name": "Government Accountability Office - Military Readiness", "url": "https://www.gao.gov/products/military-readiness"}, {"name": "Congressional Research Service - Military Preparedness", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

('2025-04-11-military-parade-planning', 13, 'multiple_choice', 'Constitutional Law', 'What constitutional concerns arise from large military displays in the capital?', 'No constitutional concerns', 'Separation of powers and civilian control of military', 'Only budget concerns', 'International law violations', 'Separation of powers and civilian control of military', 'Constitutional principles address military-civilian relationships.', 'Large military displays in the capital raise constitutional concerns about separation of powers, civilian control of the military, and whether such displays serve legitimate governmental purposes or inappropriate political demonstration of military power in democratic governance.', '["separation of powers", "civilian control", "democratic principles"]', '[{"name": "Constitution - Separation of Powers", "url": "https://constitution.congress.gov/browse/essay/artI-S8-C12-C16-1/"}, {"name": "Congressional Research Service - Civil-Military Relations", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}, {"name": "Federalist Papers - Military Control", "url": "https://guides.loc.gov/federalist-papers/government-structure"}]'),

('2025-04-11-military-parade-planning', 14, 'multiple_choice', 'Government', 'What role do local governments play in military parade planning?', 'Complete control over military parades', 'Coordination on permits, traffic, and local services', 'No involvement in federal events', 'Military command authority', 'Coordination on permits, traffic, and local services', 'Local governments provide essential services and coordination.', 'Local governments play important roles in military parade planning by coordinating on permits, traffic management, emergency services, crowd control, and other municipal services needed to support large public events in their jurisdictions.', '["local coordination", "municipal services", "permits and traffic"]', '[{"name": "International City/County Management Association", "url": "https://icma.org/"}, {"name": "National League of Cities", "url": "https://www.nlc.org/"}, {"name": "Congressional Research Service - Federal-Local Coordination", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-04-11-military-parade-planning', 15, 'multiple_choice', 'Civic Participation', 'How can citizens provide input on military parade decisions?', 'Citizens have no input on military decisions', 'Congressional representatives, public comment, and civic engagement', 'Only military personnel can comment', 'International organizations decide', 'Congressional representatives, public comment, and civic engagement', 'Democratic participation includes multiple channels for citizen input.', 'Citizens can provide input on military parade decisions through contacting congressional representatives, participating in public comment processes, engaging in civic organizations, and exercising democratic accountability through elections and public discourse.', '["democratic participation", "congressional contact", "civic engagement"]', '[{"name": "Congress.gov - Contact Representatives", "url": "https://www.congress.gov/"}, {"name": "Center for Civic Education", "url": "https://www.civiced.org/"}, {"name": "American Democracy Project", "url": "https://www.aascu.org/programs/adp/"}]'),

('2025-04-11-military-parade-planning', 16, 'multiple_choice', 'Government', 'What transparency requirements apply to military parade planning?', 'Complete secrecy required', 'Public disclosure of costs and basic planning information', 'No transparency requirements', 'Only military classification rules', 'Public disclosure of costs and basic planning information', 'Government activities are generally subject to transparency requirements.', 'Military parade planning is subject to transparency requirements including public disclosure of costs, basic planning information, and compliance with Freedom of Information Act requests, while protecting legitimate security and operational details.', '["government transparency", "FOIA requirements", "public disclosure"]', '[{"name": "Freedom of Information Act", "url": "https://www.foia.gov/"}, {"name": "Government Accountability Office - Transparency", "url": "https://www.gao.gov/about/transparency"}, {"name": "Congressional Research Service - Government Transparency", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-04-11-military-parade-planning', 17, 'multiple_choice', 'Government', 'How do military parades relate to national symbols and patriotism?', 'No relationship to national symbols', 'Can demonstrate national pride but risk politicizing military service', 'Only negative effects on patriotism', 'Automatically increase patriotism', 'Can demonstrate national pride but risk politicizing military service', 'Military displays have complex relationships with patriotism and politics.', 'Military parades can demonstrate national pride and honor military service, but they also risk politicizing the military, creating partisan divisions about patriotism, and potentially using national symbols for political rather than genuinely patriotic purposes.', '["national symbols", "patriotism", "military politicization"]', '[{"name": "American Legion", "url": "https://www.legion.org/"}, {"name": "Veterans of Foreign Wars", "url": "https://www.vfw.org/"}, {"name": "Congressional Research Service - National Symbols", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

-- True/False Questions (5 questions)
('2025-04-11-military-parade-planning', 18, 'true_false', 'Constitutional Law', 'The President has absolute authority to order military parades without any oversight.', '', '', '', '', 'False', 'Presidential military authority is subject to constitutional limits and congressional oversight.', 'False. While the President has Commander-in-Chief authority, military parade decisions are subject to constitutional limits, congressional budget authority, oversight requirements, and other checks and balances in the democratic system.', '["presidential limits", "congressional oversight", "constitutional checks"]', '[{"name": "Constitution - Checks and Balances", "url": "https://constitution.congress.gov/browse/essay/intro-7/"}, {"name": "Congressional Research Service - Presidential Authority", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}, {"name": "Federalist Papers - Separation of Powers", "url": "https://guides.loc.gov/federalist-papers/government-structure"}]'),

('2025-04-11-military-parade-planning', 19, 'true_false', 'Government', 'Military parade costs must be publicly disclosed under transparency laws.', '', '', '', '', 'True', 'Government spending is generally subject to public disclosure requirements.', 'True. Military parade costs must generally be publicly disclosed under transparency laws including Freedom of Information Act requirements, congressional oversight, and public accountability measures for federal spending, with exceptions for legitimate security concerns.', '["public disclosure", "FOIA", "spending transparency"]', '[{"name": "Freedom of Information Act", "url": "https://www.foia.gov/"}, {"name": "Government Accountability Office", "url": "https://www.gao.gov/"}, {"name": "Congressional Research Service - Government Transparency", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-04-11-military-parade-planning', 20, 'true_false', 'Government', 'Congress has no role in military parade decisions since they involve military operations.', '', '', '', '', 'False', 'Congress has budget authority and oversight responsibilities for military activities.', 'False. Congress has significant roles in military parade decisions through budget authority, oversight of military activities, and its constitutional responsibilities for defense appropriations and checking executive power over military use.', '["congressional authority", "budget oversight", "military oversight"]', '[{"name": "Congressional Research Service - Congressional Authority", "url": "https://crsreports.congress.gov/product/pdf/R/R45442"}, {"name": "House Armed Services Committee", "url": "https://armedservices.house.gov/"}, {"name": "Constitution - Congressional Powers", "url": "https://constitution.congress.gov/browse/article-1/section-8/"}]'),

('2025-04-11-military-parade-planning', 21, 'true_false', 'Civic Participation', 'Citizens should automatically support all military parade decisions as patriotic duty.', '', '', '', '', 'False', 'Democratic citizenship includes the right and responsibility to evaluate government actions.', 'False. Democratic citizenship includes the right and responsibility to critically evaluate government actions, including military parades, based on constitutional principles, fiscal responsibility, and appropriate use of military resources, rather than automatic support.', '["democratic evaluation", "critical citizenship", "government accountability"]', '[{"name": "Center for Civic Education", "url": "https://www.civiced.org/"}, {"name": "American Democracy Project", "url": "https://www.aascu.org/programs/adp/"}, {"name": "Congressional Research Service - Civic Participation", "url": "https://crsreports.congress.gov/product/pdf/R/R45031"}]'),

('2025-04-11-military-parade-planning', 22, 'true_false', 'Government', 'The United States has a long tradition of regular large-scale military parades.', '', '', '', '', 'False', 'The U.S. has limited tradition of large military parades compared to some other nations.', 'False. The United States has a limited tradition of large-scale military parades, with such events typically reserved for specific occasions rather than regular displays, unlike some countries with established traditions of frequent military parades.', '["limited tradition", "occasional events", "U.S. military culture"]', '[{"name": "National Archives - Military History", "url": "https://www.archives.gov/research/military"}, {"name": "American Military History", "url": "https://history.army.mil/"}, {"name": "Congressional Research Service - Military Traditions", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}]'),

-- Short Answer Questions (3 questions)
('2025-04-11-military-parade-planning', 23, 'short_answer', 'Constitutional Law', 'What constitutional provision gives the President authority over military ceremonies?', '', '', '', '', 'Commander-in-Chief Clause', 'This authority is found in Article II, Section 2 of the Constitution.', 'The Commander-in-Chief Clause in Article II, Section 2 gives the President constitutional authority over military ceremonies and activities as the supreme commander of the armed forces, including directing military participation in parades and official events.', '["Commander-in-Chief", "Article II", "military authority"]', '[{"name": "Constitution - Commander-in-Chief Clause", "url": "https://constitution.congress.gov/browse/essay/artII-S2-C1-1/"}, {"name": "Congressional Research Service - Presidential Military Authority", "url": "https://crsreports.congress.gov/product/pdf/R/R42699"}, {"name": "Federalist Papers - Executive Power", "url": "https://guides.loc.gov/federalist-papers/executive-branch"}]'),

('2025-04-11-military-parade-planning', 24, 'short_answer', 'Government', 'What law limits the domestic use of military forces?', '', '', '', '', 'Posse Comitatus Act', 'This federal law restricts military involvement in domestic law enforcement.', 'The Posse Comitatus Act limits the domestic use of military forces by restricting their involvement in civilian law enforcement activities, though it generally allows ceremonial activities while maintaining important principles about military-civilian separation.', '["Posse Comitatus Act", "domestic military limits", "civilian law enforcement"]', '[{"name": "Posse Comitatus Act", "url": "https://www.law.cornell.edu/uscode/text/18/1385"}, {"name": "Congressional Research Service - Posse Comitatus", "url": "https://crsreports.congress.gov/product/pdf/R/R42659"}, {"name": "Department of Defense - Domestic Operations", "url": "https://www.defense.gov/News/domestic-operations/"}]'),

('2025-04-11-military-parade-planning', 25, 'short_answer', 'Government', 'What government agency typically audits federal spending on military events?', '', '', '', '', 'Government Accountability Office', 'This congressional agency provides oversight of federal spending and operations.', 'The Government Accountability Office (GAO) typically audits federal spending on military events as part of its congressional oversight role, examining costs, efficiency, and appropriate use of taxpayer funds for government activities including military ceremonies.', '["Government Accountability Office", "GAO", "federal spending oversight"]', '[{"name": "Government Accountability Office", "url": "https://www.gao.gov/"}, {"name": "GAO - Military Spending Reviews", "url": "https://www.gao.gov/products/military-spending"}, {"name": "Congressional Research Service - GAO Role", "url": "https://crsreports.congress.gov/product/pdf/R/R45442"}]');