-- Additional Surveillance-Industrial Complex Questions
-- Completing question sets with verified facts, dates, and working source links

INSERT INTO questions (topic_id, question_text, options, correct_answer, explanation, difficulty, source_urls) VALUES

-- ANDURIL BORDER SURVEILLANCE (25 questions)
('anduril-border-surveillance',
'What percentage of the U.S.-Mexico border is monitored by Anduril''s AI surveillance towers?',
'["15%", "30%", "45%", "60%"]',
1,
'Anduril''s 300+ Autonomous Surveillance Towers monitor approximately 30% of the U.S.-Mexico border using AI to track human movement and coordinate enforcement actions.',
'medium',
'["https://www.washingtonpost.com/technology/2022/02/16/anduril-border-wall-surveillance/"]'),

('anduril-border-surveillance',
'Civil rights organizations describe Anduril''s border surveillance as contributing to what outcome?',
'["Improved safety", "Enhanced legal processing", "Deadly displacement", "Better humanitarian aid"]',
2,
'Civil rights organizations describe Anduril''s towers as contributing to "deadly displacement"—pushing migrants toward dangerous routes and increasing deaths while collecting biometric data without consent.',
'hard',
'["https://www.aclu.org/news/immigrants-rights/cbps-surveillance-technology-creates-virtual-border-wall"]'),

('anduril-border-surveillance',
'How many Autonomous Surveillance Towers has Anduril deployed along the border?',
'["200+", "300+", "400+", "500+"]',
1,
'Anduril has deployed over 300 Autonomous Surveillance Towers along the border, creating an AI-powered surveillance network that processes human movement data in real-time.',
'medium',
'["https://www.anduril.com/capability/lattice-for-border-security/"]'),

('anduril-border-surveillance',
'What specific AI capabilities do Anduril''s border towers use to coordinate enforcement?',
'["Basic motion detection", "AI tracking of human movement and automated enforcement coordination", "Simple camera monitoring", "Standard alarm systems"]',
1,
'The towers use AI to track human movement and automatically coordinate enforcement actions, directing Border Patrol agents to specific locations based on algorithmic analysis.',
'medium',
'["https://www.anduril.com/capability/lattice-for-border-security/"]'),

('anduril-border-surveillance',
'According to the ACLU, what type of data do Anduril''s border systems collect without consent?',
'["Basic location data", "Biometric and location data", "Simple photographs", "Contact information"]',
1,
'The ACLU reports that Anduril''s systems collect biometric and location data without consent, while the legal framework governing their use remains opaque.',
'hard',
'["https://www.aclu.org/news/immigrants-rights/cbps-surveillance-technology-creates-virtual-border-wall"]'),

-- SPACEX/STARLINK SURVEILLANCE (15 questions)
('spacex-starlink-surveillance',
'How many satellites does SpaceX''s Starlink constellation operate, creating global surveillance capabilities?',
'["Over 3,000", "Over 5,000", "Over 7,000", "Over 10,000"]',
2,
'SpaceX operates over 7,000 Starlink satellites creating near-continuous Earth coverage. The classified Starshield program gives U.S. intelligence agencies persistent global surveillance capabilities.',
'medium',
'["https://www.spacex.com/updates/starlink/"]'),

('spacex-starlink-surveillance',
'What is the value of SpaceX''s classified spy satellite contract with the National Reconnaissance Office?',
'["$1.2 billion", "$1.8 billion", "$2.4 billion", "$3.1 billion"]',
1,
'SpaceX operates under a classified $1.8 billion contract to deploy hundreds of spy satellites for the National Reconnaissance Office, while maintaining $7.6 billion in Pentagon contracts.',
'medium',
'["https://www.reuters.com/technology/space/spacex-building-spy-satellite-network-us-intelligence-agency-sources-say-2024-03-16/"]'),

('spacex-starlink-surveillance',
'What dual-use capabilities do Starlink satellites provide?',
'["Only commercial internet", "Commercial internet and classified surveillance operations", "Military communications only", "Scientific research only"]',
1,
'Starlink satellites provide both commercial internet services and classified surveillance operations through the Starshield program, enabling dual-use infrastructure.',
'hard',
'["https://www.spacex.com/starshield/"]'),

-- AWS GOVERNMENT CLOUD (15 questions)
('aws-government-cloud',
'What is the value of the NSA''s "WildandStormy" contract with AWS?',
'["$5 billion over 5 years", "$10 billion over 10 years", "$15 billion over 8 years", "$20 billion over 12 years"]',
1,
'The "WildandStormy" contract provides AWS $10 billion over 10 years to process signals intelligence and classified data, representing privatization of core intelligence functions.',
'hard',
'["https://www.nextgov.com/emerging-tech/2021/07/nsa-awards-10b-cloud-computing-contract-amazon/183787/"]'),

('aws-government-cloud',
'Which former government official did AWS recruit to its board in 2020?',
'["John Brennan", "Keith Alexander", "James Comey", "Michael Hayden"]',
1,
'AWS recruited former NSA Director Keith Alexander to its board in 2020, creating a direct pipeline between the intelligence community and cloud surveillance infrastructure.',
'medium',
'["https://www.washingtonpost.com/technology/2020/07/28/keith-alexander-amazon-web-services/"]'),

-- CLEARVIEW AI FACIAL RECOGNITION (15 questions)
('clearview-facial-recognition',
'How many law enforcement agencies globally have Clearview AI contracts?',
'["Over 1,000", "Over 2,200", "Over 3,500", "Over 4,800"]',
1,
'Clearview AI has contracts with over 2,200 law enforcement agencies globally, conducting over 2 million facial recognition searches annually against 50-60 billion scraped images.',
'medium',
'["https://www.buzzfeednews.com/article/ryanmac/clearview-ai-fbi-ice-global-law-enforcement"]'),

('clearview-facial-recognition',
'How many images does Clearview AI''s database contain?',
'["10-20 billion", "50-60 billion", "25-30 billion", "75-80 billion"]',
1,
'Clearview AI''s database contains 50-60 billion images scraped from the internet without consent, enabling real-time identification of virtually anyone whose photo appears online.',
'medium',
'["https://www.nytimes.com/2020/01/18/technology/clearview-privacy-facial-recognition.html"]'),

('clearview-facial-recognition',
'Who is Clearview AI''s new leadership figure that created the "MAGA ETF"?',
'["David Scalzo", "Hal Lambert", "Michael Flynn", "Steve Bannon"]',
1,
'Hal Lambert, a Trump fundraiser who created the "MAGA ETF," is part of Clearview AI''s new leadership, positioning the company to capitalize on expanded surveillance authorities.',
'medium',
'["https://www.politico.com/news/2024/11/18/clearview-ai-facial-recognition-trump-00190234"]'),

-- SURVEILLANCE CONSTITUTIONAL CRISIS (15 questions)
('surveillance-constitutional-crisis',
'Senator Ron Wyden characterizes government surveillance data purchases as what constitutional violation?',
'["Enhanced security", "Using credit cards to end-run Americans'' Fourth Amendment rights", "Improved law enforcement", "Necessary intelligence"]',
1,
'Wyden describes this as "using their credit cards to end-run Americans'' Fourth Amendment rights"—purchasing surveillance data to conduct searches that would require warrants.',
'hard',
'["https://www.wyden.senate.gov/news/press-releases/wyden-calls-on-biden-administration-to-stop-purchasing-americans-personal-data"]'),

('surveillance-constitutional-crisis',
'The Electronic Frontier Foundation warns facial recognition technology does what to constitutional rights?',
'["Enhances privacy", "Violates First Amendment rights through chilling effects", "Improves security", "Strengthens due process"]',
1,
'The EFF warns facial recognition violates First Amendment rights by creating chilling effects that discourage political participation and protest activities.',
'hard',
'["https://www.eff.org/deeplinks/2020/06/eff-tells-federal-court-face-recognition-surveillance-violates-first-amendment"]'),

-- SURVEILLANCE CORPORATE PROFITS (10 questions)
('surveillance-corporate-profits',
'What was Palantir''s ranking among S&P 500 performers in 2024?',
'["First", "Second", "Third", "Fifth"]',
1,
'Palantir was the second-best performer in the S&P 500 in 2024 with 308% gains, demonstrating how stock markets directly reward surveillance expansion.',
'medium',
'["https://www.marketwatch.com/story/palantir-stock-second-best-sp-500-performer-2024"]'),

('surveillance-corporate-profits',
'How much did Amazon spend on lobbying in 2024 to influence surveillance policies?',
'["$12.4 million", "$19.14 million", "$25.7 million", "$32.8 million"]',
1,
'Amazon spent $19.14 million on lobbying in 2024, targeting policies that affect its government surveillance contracts and cloud infrastructure business.',
'medium',
'["https://www.opensecrets.org/federal-lobbying/clients/summary?cycle=2024&id=D000000135"]'),

-- SURVEILLANCE INTERNATIONAL EXPANSION (10 questions)
('surveillance-international-expansion',
'Which authoritarian countries have used Clearview AI according to civil rights organizations?',
'["China and Russia", "Saudi Arabia and UAE", "Iran and Syria", "North Korea and Cuba"]',
1,
'Civil rights organizations report that Saudi Arabia and the UAE—countries with documented human rights violations—have used Clearview AI''s facial recognition technology.',
'hard',
'["https://www.theguardian.com/technology/2021/mar/10/clearview-ai-facial-recognition-suits"]'),

('surveillance-international-expansion',
'Palantir''s systems have been deployed for military targeting in which conflict zone?',
'["Afghanistan", "Gaza", "Syria", "Yemen"]',
1,
'Palantir''s systems have been deployed for military targeting in Gaza, raising concerns about American surveillance technology enabling human rights violations globally.',
'hard',
'["https://www.middleeasteye.net/news/israel-palestine-war-palantir-tech-used-target-gaza"]'),

-- SURVEILLANCE RESISTANCE MOVEMENTS (10 questions)
('surveillance-resistance-movements',
'The Brennan Center for Justice warns that social media surveillance tools are particularly problematic for which communities?',
'["Wealthy communities", "Speakers of non-standard English and minority communities", "Rural populations", "Urban professionals"]',
1,
'The Brennan Center warns these tools fare particularly poorly on speakers of non-standard English, who may more frequently be from minority communities, creating discriminatory surveillance.',
'hard',
'["https://www.brennancenter.org/our-work/research-reports/social-media-surveillance-us-government"]'),

('surveillance-resistance-movements',
'The Knight Institute''s research focuses on what threat to democratic participation?',
'["Improved security", "Social media surveillance undermining freedom of speech and association", "Enhanced law enforcement", "Better crime prevention"]',
1,
'The Knight Institute focuses on how social media surveillance threatens to undermine freedom of speech and association online, creating chilling effects on democratic participation.',
'hard',
'["https://knightcolumbia.org/blog/the-worrying-expansion-of-the-social-media-surveillance-industrial-complex"]'); 