-- ============================================================================
-- SURVEILLANCE-INDUSTRIAL COMPLEX QUESTION TOPICS FOR CIVICSENSE
-- 11 Topics Revealing How Tech Giants Control Government Surveillance
-- Created: December 2024
-- Purpose: Civic education about corporate surveillance integration with government
-- ============================================================================

-- Topics Overview:
-- 1-2: Palantir (Government contracts & Data compilation)
-- 3-4: Anduril (Border surveillance & Military AI)
-- 5-6: Clearview AI (Facial recognition database & Law enforcement)
-- 7-8: SpaceX/Starlink (Military satellites & Communication control)
-- 9-10: AWS (NSA contracts & Intelligence integration)
-- 11: Overview (Complete surveillance-industrial complex)

INSERT INTO "public"."question_topics" ("id", "topic_id", "topic_title", "description", "why_this_matters", "emoji", "date", "day_of_week", "categories", "is_active", "created_at", "updated_at", "is_breaking") VALUES 

-- PALANTIR TOPIC 1: Government Contracts Empire
(gen_random_uuid(), 'palantir-government-contracts-2025', 'Palantir''s $1.2 Billion Government Surveillance Empire', 'Peter Thiel''s Palantir Technologies has secured over $1.2 billion in federal contracts, with their stock surging 200%+ after Trump''s 2024 election victory. The company''s AI-powered surveillance systems now monitor American citizens through dozens of government agencies, from ICE deportation operations to military intelligence gathering.', '<ul><li><strong>Your Privacy Rights:</strong> Palantir''s surveillance technology directly affects your privacy, civil liberties, and due process rights—their algorithms help determine who gets investigated, deported, or flagged as a security risk.</li><li><strong>Your Tax Dollars:</strong> Over $1.2 billion in federal contracts funded by your taxes now power surveillance systems that monitor American citizens without meaningful oversight or accountability.</li><li><strong>Your Political Influence:</strong> Peter Thiel''s protégés now occupy the highest levels of government, with J.D. Vance as Vice President ensuring continued contract expansion while monitoring citizens.</li><li><strong>Your Democratic Voice:</strong> Understanding this government integration reveals how corporate surveillance has become government policy, affecting your ability to participate freely in democracy.</li></ul>', '🕵️', '2025-01-20', 'Monday', '["Surveillance","Technology","Government Contracts","Privacy","Civil Liberties"]', true, NOW(), NOW(), null),

-- PALANTIR TOPIC 2: Data Compilation on Americans
(gen_random_uuid(), 'palantir-data-compilation-americans', 'How Palantir Builds Files on Ordinary Americans', 'Palantir''s Gotham and Foundry platforms compile extensive digital profiles on American citizens by integrating data from social media, financial records, location tracking, and government databases. Their "predictive policing" algorithms flag individuals for investigation based on associations, online activity, and behavioral patterns—often without any criminal wrongdoing.', '<ul><li><strong>Your Digital Privacy:</strong> Palantir''s data compilation directly affects your digital privacy and freedom of association—their systems may have already created a profile on you based on your online activity and social connections.</li><li><strong>Your Employment Future:</strong> These digital profiles affect everything from employment background checks to travel screening, potentially limiting your opportunities based on algorithmic judgments.</li><li><strong>Your Constitutional Rights:</strong> Data collection operates without warrant requirements or judicial oversight, effectively circumventing Fourth Amendment protections through corporate surveillance.</li><li><strong>Your Community Safety:</strong> Algorithmic bias in Palantir systems disproportionately affects marginalized communities, making some neighborhoods targets for increased surveillance and enforcement.</li></ul>', '🗂️', '2025-01-21', 'Tuesday', '["Surveillance","Data Privacy","Algorithmic Bias","Civil Liberties","Technology"]', true, NOW(), NOW(), null),

-- ANDURIL TOPIC 1: Border Surveillance Network
(gen_random_uuid(), 'anduril-border-surveillance-2025', 'Anduril''s AI-Powered Border Surveillance Network', 'Palmer Luckey''s Anduril Industries has deployed autonomous surveillance towers monitoring 30% of the US-Mexico border, with AI systems tracking human movement across 200+ mile stretches. Their technology integrates with ICE and CBP operations, using machine learning to predict migration patterns and direct enforcement actions.', '<ul><li><strong>Your Immigration Policy:</strong> Anduril''s border surveillance directly affects immigration enforcement in your community—their AI systems determine which areas get increased patrol presence and which individuals get flagged for investigation.</li><li><strong>Your Human Rights:</strong> Autonomous AI systems operate 24/7 without human oversight, treating immigration as a warfare problem rather than a humanitarian issue while generating billions in profits from human suffering.</li><li><strong>Your Tax Investment:</strong> Over $1 billion in border and military surveillance contracts funded by your taxes support technology that has contributed to what civil rights organizations call "deadly displacement."</li><li><strong>Your Constitutional Values:</strong> This technology shapes how America treats immigrants and asylum seekers, affecting your community''s relationship with democratic values of due process and human dignity.</li></ul>', '🤖', '2025-01-22', 'Wednesday', '["Immigration","Surveillance","Artificial Intelligence","Border Security","Human Rights"]', true, NOW(), NOW(), null),

-- ANDURIL TOPIC 2: Military AI and Autonomous Weapons
(gen_random_uuid(), 'anduril-military-ai-expansion', 'Anduril''s Autonomous Weapons and Military AI Empire', 'Anduril Industries is expanding beyond border surveillance into autonomous military systems, including AI-powered drones, missile defense systems, and battlefield robotics. Their contracts with the Department of Defense aim to revolutionize warfare through artificial intelligence, raising profound questions about machines making kill decisions.', '<ul><li><strong>Your Tax Dollars:</strong> As a taxpayer, you''re funding the development of weapons that could fundamentally change how wars are fought—autonomous weapons systems that could lower the threshold for armed conflict.</li><li><strong>Your Global Security:</strong> Anduril''s military AI development affects global stability and your safety—their autonomous weapons systems could make wars more likely by reducing human cost calculations.</li><li><strong>Your Ethical Responsibility:</strong> The company is building foundations for AI-controlled warfare where machines can identify, target, and potentially eliminate human beings without direct human authorization.</li><li><strong>Your Democratic Oversight:</strong> Understanding these contracts helps you evaluate whether defense decisions serve America or private profits, as Silicon Valley culture of "move fast and break things" gets applied to lethal military technology.</li></ul>', '⚔️', '2025-01-23', 'Thursday', '["Military","Artificial Intelligence","Autonomous Weapons","Defense Spending","Ethics"]', true, NOW(), NOW(), null),

-- CLEARVIEW AI TOPIC 1: Facial Recognition Database
(gen_random_uuid(), 'clearview-ai-database-2025', 'Clearview AI''s 60 Billion Image Facial Recognition Database', 'Clearview AI has scraped over 60 billion images from social media, websites, and public cameras to create the world''s largest facial recognition database. Used by 2,200+ law enforcement agencies, their system can identify anyone from a single photo with claimed 99%+ accuracy across all demographics.', '<ul><li><strong>Your Anonymity:</strong> Clearview AI affects your anonymity in public spaces—every photo of you online may be in their database, allowing police to identify you from security camera footage, protest photos, or any image where your face appears.</li><li><strong>Your Consent:</strong> The company has created a comprehensive surveillance state where every American can be instantly identified from any photo, without consent, judicial oversight, or accuracy verification.</li><li><strong>Your Constitutional Rights:</strong> This system fundamentally ends anonymous participation in public life, affecting your freedom of association, protest participation, and basic privacy in public spaces.</li><li><strong>Your Equal Treatment:</strong> Facial recognition accuracy claims mask significant bias against minorities and women, while law enforcement gains unprecedented identification power without warrant requirements.</li></ul>', '👁️', '2025-01-24', 'Friday', '["Facial Recognition","Privacy","Surveillance","Biometric Data","Law Enforcement"]', true, NOW(), NOW(), null),

-- CLEARVIEW AI TOPIC 2: Law Enforcement Transformation
(gen_random_uuid(), 'clearview-ai-law-enforcement-expansion', 'How Clearview AI Transformed Police Surveillance Power', 'Clearview AI has fundamentally changed law enforcement by giving officers instant facial recognition capability through smartphone apps. Departments can identify suspects, witnesses, and bystanders from any photo, turning every security camera and social media image into a surveillance tool for police investigations.', '<ul><li><strong>Your Police Interactions:</strong> Clearview AI changes how police interact with communities and individuals—officers can now identify you from protest photos, traffic cameras, or background appearances in others'' social media posts.</li><li><strong>Your Community Trust:</strong> Local police departments gain federal-level surveillance capabilities without federal oversight, while police unions and departments resist transparency about how this technology is used.</li><li><strong>Your Civil Rights:</strong> The technology has given police departments surveillance capabilities rivaling intelligence agencies, without training, oversight, or accuracy verification, while affecting your freedom of association and basic privacy.</li><li><strong>Your Democratic Participation:</strong> Facial recognition use in policing disproportionately impacts communities of color and creates surveillance that discourages political participation and protest attendance.</li></ul>', '🚔', '2025-01-25', 'Saturday', '["Law Enforcement","Facial Recognition","Community Surveillance","Police Accountability","Civil Liberties"]', true, NOW(), NOW(), null),

-- SPACEX/STARLINK TOPIC 1: Military Spy Satellites
(gen_random_uuid(), 'spacex-starlink-military-surveillance', 'SpaceX''s $1.8 Billion Spy Satellite Network for Military Surveillance', 'SpaceX has secured a classified $1.8 billion contract with the National Reconnaissance Office to build a network of hundreds of spy satellites capable of tracking targets anywhere on Earth in real-time. Their Starshield program integrates military intelligence gathering with the commercial Starlink constellation.', '<ul><li><strong>Your Global Privacy:</strong> SpaceX''s military satellite network affects global privacy and your digital communications—their constellation can potentially monitor internet traffic, track device locations, and provide real-time surveillance of any location on Earth.</li><li><strong>Your Communication Security:</strong> The company has created a dual-use satellite constellation where commercial internet service provides cover for the most comprehensive surveillance network ever deployed, with the ability to monitor communications globally.</li><li><strong>Your Tax Investment:</strong> The classified $1.8 billion contract funded by your taxes builds spy satellites while maintaining commercial relationships that create unprecedented conflicts of interest between private business and government surveillance.</li><li><strong>Your Democratic Oversight:</strong> Military satellite surveillance operates without civilian oversight or transparency, while Elon Musk''s personal political views influence access to critical communications infrastructure.</li></ul>', '🛰️', '2025-01-26', 'Sunday', '["Space Surveillance","Military Contracts","Satellite Communications","Global Monitoring","Dual Use Technology"]', true, NOW(), NOW(), null),

-- SPACEX/STARLINK TOPIC 2: Geopolitical Communication Control
(gen_random_uuid(), 'starlink-internet-control-geopolitics', 'How Starlink Became a Geopolitical Weapon and Communication Controller', 'Starlink''s control over satellite internet gives SpaceX unprecedented power to influence global conflicts and communications. Elon Musk has personally made decisions about Starlink access during the Ukraine war, Internet connectivity in Iran, and service availability that affect millions of people''s access to information.', '<ul><li><strong>Your Communication Freedom:</strong> Starlink''s communication control affects global information access and democratic movements—one person''s decisions about satellite internet can determine whether protesters can organize, journalists can report, or civilians can communicate during crises.</li><li><strong>Your Democratic Accountability:</strong> A single private individual now controls critical communications infrastructure used by militaries, governments, and civilians worldwide, with no democratic oversight or accountability for decisions affecting global conflicts.</li><li><strong>Your National Security:</strong> Democratic governments depend on private companies for military and civilian communications, while tech billionaires make unilateral decisions affecting global conflicts and human rights.</li><li><strong>Your Internet Independence:</strong> Commercial satellite systems have become tools of geopolitical influence and control, with concentrated power over global communications that is unprecedented in human history.</li></ul>', '🌐', '2025-01-27', 'Monday', '["Communications Control","Geopolitics","Internet Governance","Private Power","Global Infrastructure"]', true, NOW(), NOW(), null),

-- AWS TOPIC 1: NSA Cloud Contract
(gen_random_uuid(), 'aws-nsa-cloud-contract-2025', 'Amazon''s $10 Billion NSA Cloud Contract for Intelligence Processing', 'Amazon Web Services (AWS) has secured a $10 billion contract with the National Security Agency called "WildandStormy" to provide cloud computing infrastructure for processing classified intelligence data. This contract gives Amazon access to some of America''s most sensitive surveillance information and intelligence operations.', '<ul><li><strong>Your Data Security:</strong> AWS''s NSA contract affects the privacy and security of your personal data—the same company providing cloud services to businesses and individuals worldwide now processes America''s most sensitive intelligence data.</li><li><strong>Your Business Trust:</strong> Amazon has become the backbone of America''s intelligence operations, processing classified surveillance data through the same infrastructure that powers commercial services, creating potential conflicts of interest and security vulnerabilities.</li><li><strong>Your Tax Investment:</strong> The $10 billion contract funded by your taxes gives commercial cloud providers access to classified intelligence, while tech companies profit from both commercial services and intelligence operations simultaneously.</li><li><strong>Your Constitutional Oversight:</strong> Intelligence agencies outsource core functions to private companies with global business interests, creating single points of failure for both commercial and intelligence operations without adequate democratic accountability.</li></ul>', '☁️', '2025-01-28', 'Tuesday', '["Cloud Computing","Intelligence Agencies","Data Processing","Government Contracts","National Security"]', true, NOW(), NOW(), null),

-- AWS TOPIC 2: Intelligence Community Integration
(gen_random_uuid(), 'aws-intelligence-community-integration', 'How Amazon Became the CIA''s Technology Partner', 'Amazon Web Services has become deeply integrated with U.S. intelligence agencies through a decade-long partnership that began with a $600 million CIA contract. AWS now provides cloud infrastructure for multiple intelligence agencies, creating the Intelligence Community GovCloud that processes classified data and surveillance information.', '<ul><li><strong>Your Privacy Concentration:</strong> AWS''s intelligence community integration affects government transparency and accountability—the same company that knows your shopping habits and business information also processes America''s most sensitive intelligence data about you.</li><li><strong>Your Democratic Transparency:</strong> Amazon has created a unified surveillance infrastructure where commercial data collection and intelligence operations share the same technological foundation, giving one company access to both personal and government intelligence.</li><li><strong>Your Oversight Rights:</strong> Tech companies leverage government contracts to gain privileged access to surveillance data, while intelligence agencies become dependent on private companies for core operational capabilities without public accountability.</li><li><strong>Your Constitutional Balance:</strong> Commercial and intelligence surveillance merge into unified data collection systems, while private companies gain insights into government surveillance that can benefit commercial operations and threaten democratic governance.</li></ul>', '🔍', '2025-01-29', 'Wednesday', '["Intelligence Agencies","Corporate Surveillance","Government Transparency","Data Integration","Accountability"]', true, NOW(), NOW(), null),

-- SURVEILLANCE-INDUSTRIAL COMPLEX OVERVIEW
(gen_random_uuid(), 'surveillance-industrial-complex-2025', 'America''s Surveillance-Industrial Complex: How Five Tech Giants Control Government Monitoring', 'Five major technology companies—Palantir, Anduril, Clearview AI, SpaceX, and Amazon—have created an integrated surveillance-industrial complex worth billions in government contracts. Together, they provide comprehensive surveillance capabilities from facial recognition and predictive policing to satellite monitoring and intelligence processing, fundamentally transforming how government monitors American citizens.', '<ul><li><strong>Your Complete Privacy Loss:</strong> The surveillance-industrial complex affects every aspect of your privacy and civil liberties—these five companies can collectively track your movements, identify your face, analyze your data, monitor your communications, and predict your behavior through government contracts funded by your tax dollars.</li><li><strong>Your Democratic Participation:</strong> America has outsourced its surveillance state to private companies that profit from monitoring citizens while maintaining the legal fiction that government surveillance is limited, when corporate surveillance has eliminated most privacy protections.</li><li><strong>Your Constitutional Rights:</strong> Government circumvents constitutional limits on surveillance by purchasing data from private companies, while tech entrepreneurs become surveillance state architects and democratic oversight mechanisms fail to regulate corporate surveillance.</li><li><strong>Your Systemic Power:</strong> Understanding this complete system helps you recognize how surveillance capitalism merges with government power to create total information awareness, requiring comprehensive reform to restore democratic accountability and constitutional protections.</li></ul>', '🏛️', '2025-01-30', 'Thursday', '["Surveillance State","Corporate Power","Civil Liberties","Government Accountability","Systemic Change"]', true, NOW(), NOW(), null);

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================

-- Verify all 11 topics were inserted successfully
SELECT 
    COUNT(*) as total_topics_inserted,
    COUNT(CASE WHEN topic_id LIKE 'palantir%' THEN 1 END) as palantir_topics,
    COUNT(CASE WHEN topic_id LIKE 'anduril%' THEN 1 END) as anduril_topics,
    COUNT(CASE WHEN topic_id LIKE 'clearview%' THEN 1 END) as clearview_topics,
    COUNT(CASE WHEN topic_id LIKE 'spacex%' OR topic_id LIKE 'starlink%' THEN 1 END) as spacex_topics,
    COUNT(CASE WHEN topic_id LIKE 'aws%' THEN 1 END) as aws_topics,
    COUNT(CASE WHEN topic_id = 'surveillance-industrial-complex-2025' THEN 1 END) as overview_topics
FROM question_topics 
WHERE topic_id IN (
    'palantir-government-contracts-2025',
    'palantir-data-compilation-americans',
    'anduril-border-surveillance-2025',
    'anduril-military-ai-expansion',
    'clearview-ai-database-2025',
    'clearview-ai-law-enforcement-expansion',
    'spacex-starlink-military-surveillance',
    'starlink-internet-control-geopolitics',
    'aws-nsa-cloud-contract-2025',
    'aws-intelligence-community-integration',
    'surveillance-industrial-complex-2025'
);

-- ============================================================================
-- TOPIC SUMMARY
-- ============================================================================

-- Display all created topics with key metadata
SELECT 
    topic_id,
    topic_title,
    emoji,
    date,
    array_length(categories, 1) as num_categories,
    created_at
FROM question_topics 
WHERE topic_id IN (
    'palantir-government-contracts-2025',
    'palantir-data-compilation-americans',
    'anduril-border-surveillance-2025',
    'anduril-military-ai-expansion',
    'clearview-ai-database-2025',
    'clearview-ai-law-enforcement-expansion',
    'spacex-starlink-military-surveillance',
    'starlink-internet-control-geopolitics',
    'aws-nsa-cloud-contract-2025',
    'aws-intelligence-community-integration',
    'surveillance-industrial-complex-2025'
)
ORDER BY topic_id; 