-- Seed data for crossword puzzle questions
-- Run after crossword schema migration

INSERT INTO questions (
    topic_id,
    question_number,
    question_type,
    category,
    question,
    correct_answer,
    hint,
    explanation,
    tags,
    crossword_data
) VALUES (
    'crossword_demo',
    1,
    'crossword',
    'Government',
    'Crossword: Basic Civics Terms',
    NULL, -- correct_answer generated by trigger
    'Think about fundamental civics concepts.',
    'Each correct word reveals a key civics term.',
    ARRAY['crossword','demo'],
    '{
      "metadata": {
        "title": "Civic Basics",
        "author": "Seed Script",
        "difficulty": "easy",
        "created_at": "2024-06-16"
      },
      "size": { "rows": 5, "cols": 5 },
      "layout": [
        ".....",
        "..#..",
        "#...#",
        "..#..",
        "....."
      ],
      "words": [
        {
          "number": 1,
          "word": "CIVIC",
          "clue": "Relating to citizens",
          "position": { "row": 0, "col": 0 },
          "direction": "across"
        },
        {
          "number": 2,
          "word": "VOTE",
          "clue": "Choose in an election",
          "position": { "row": 1, "col": 0 },
          "direction": "down"
        },
        {
          "number": 3,
          "word": "LAW",
          "clue": "Rules enacted by a government",
          "position": { "row": 0, "col": 2 },
          "direction": "down"
        }
      ]
    }'::jsonb
);

-- Example of a second (harder) crossword with a full 10×10 layout
INSERT INTO questions (
    topic_id,
    question_number,
    question_type,
    category,
    question,
    correct_answer,
    hint,
    explanation,
    tags,
    crossword_data
) VALUES (
    'crossword_demo',
    2,
    'crossword',
    'Government',
    'Crossword: Advanced Civics',
    NULL,
    'Focus on constitutional concepts.',
    'Demonstrates advanced crossword difficulty support.',
    ARRAY['crossword','advanced'],
    '{
      "metadata": {
        "title": "Constitution & Governance",
        "author": "Seed Script",
        "difficulty": "hard",
        "created_at": "2024-06-16"
      },
      "size": { "rows": 10, "cols": 10 },
      "layout": [
        "...#......",
        "..........",
        "..#....#..",
        "#.........",
        ".....##..#",
        "......#...",
        "..##......",
        ".....#....",
        "....#.....",
        "......##.."
      ],
      "words": [
        {
          "number": 1,
          "word": "CONGRESS",
          "clue": "Legislative branch",
          "position": { "row": 0, "col": 0 },
          "direction": "across"
        },
        {
          "number": 2,
          "word": "AMENDMENT",
          "clue": "A change to the constitution",
          "position": { "row": 1, "col": 2 },
          "direction": "across"
        },
        {
          "number": 3,
          "word": "VETO",
          "clue": "President can do this to a bill",
          "position": { "row": 4, "col": 0 },
          "direction": "across"
        },
        {
          "number": 4,
          "word": "JUSTICE",
          "clue": "Key concept of the judiciary",
          "position": { "row": 0, "col": 3 },
          "direction": "down"
        },
        {
          "number": 5,
          "word": "BALANCE",
          "clue": "Separation of powers aims for this",
          "position": { "row": 0, "col": 6 },
          "direction": "down"
        }
      ]
    }'::jsonb
); 