import type { UIStrings } from './ui-strings';

export const uiStringsES: UIStrings = {
  "navigation": {
    "back": "Volver",
    "close": "Cerrar",
    "menu": "Menú",
    "home": "Inicio",
    "topics": "Temas",
    "learn": "Explore",
    "profile": "Perfil",
    "settings": "Ajustes",
    "bookmarks": "Marcadores",
    "history": "Historia",
    "signInToPlay": "Iniciar sesión para jugar",
    "signInToSaveProgress": "Iniciar sesión para guardar el progreso"
  },
  "topic": {
    "loading": "Cargando detalles del tema...",
    "loadingDetails": "Cargando detalles...",
    "backToTopics": "Volver a Temas",
    "share": "Compartir tema",
    "bookmark": "Añadir a favoritos",
    "removeBookmark": "Eliminar marcador",
    "bookmarkThis": "Añadir a favoritos",
    "translateThisPage": "Traducir esta página",
    "showOriginal": "Mostrar original",
    "whyThisMatters": "Por qué es importante",
    "sourcesAndReferences": "Fuentes y referencias",
    "takingTheQuiz": "Hacer el test",
    "startQuiz": "Haz la prueba",
    "questionsLabel": "Preguntas",
    "estimatedMinutesLabel": "Est. Min.",
    "ratingLabel": "Clasificación",
    "publishedLabel": "Publicado en",
    "levelLabel": "Nivel",
    "difficultyLabel": "Dificultad",
    "questionsCount": "Total de preguntas",
    "estimatedTime": "Tiempo estimado",
    "level": "Nivel",
    "difficulty": "Dificultad",
    "easy": "Fácil",
    "medium": "Medio",
    "hard": "Duro",
    "beginner": "Principiante",
    "intermediate": "Intermedio",
    "advanced": "Avanzado",
    "thinkYouGotIt": "¿Crees que lo tienes?",
    "testYourUnderstanding": "Ponga a prueba su comprensión de este tema y compruebe lo bien que entiende los conceptos clave que hemos tratado.",
    "noSourcesAvailable": "Aún no hay fuentes disponibles",
    "noSourcesDescription": "Las fuentes y referencias se irán añadiendo a medida que se revisen y verifiquen los contenidos.",
    "understandingSourceAnalysis": "Comprender el análisis de fuentes",
    "biasRatingsMeaning": "¿Qué significan los índices de parcialidad?",
    "credibilityPercentageMeaning": "¿Qué significa el porcentaje de credibilidad?",
    "howRatingsDetermined": "¿Cómo se determinan estas clasificaciones?",
    "areRatingsPermanent": "¿Son permanentes estas clasificaciones?",
    "sourceAnalysisImportance": "¿Por qué es importante?",
    "ratingsAndReviews": "Valoraciones y reseñas",
    "communityFeedback": "Comentarios de la comunidad",
    "communityReviews": "Comentarios de la comunidad",
    "rateThisTopic": "Valore este tema",
    "howHelpfulWasThis": "¿Qué tan útil fue esto?",
    "noRatingsYet": "Aún no hay valoraciones",
    "recentReviews": "Reseñas recientes",
    "noReviewsYet": "Aún no hay opiniones",
    "noReviewsDescription": "Sea el primero en compartir su opinión sobre este tema.",
    "writeFirstReview": "Escribe la primera opinión",
    "viewAllReviews": "Ver todos los comentarios",
    "editRating": "Editar clasificación",
    "ratingBreakdown": "Clasificación",
    "shareYourThoughts": "Comparte tus pensamientos...",
    "completeQuizToReview": "Completa el cuestionario para repasar",
    "takeQuizToShare": "Haz una prueba para compartir",
    "wasThisHelpful": "¿Te ha resultado útil?",
    "writeAReview": "Escriba un comentario",
    "rateAndReview": "Valore y revise",
    "selectRating": "Seleccione la clasificación",
    "submitReview": "Enviar opinión",
    "shareYourThoughtsDesc": "Comparta su opinión sobre este tema",
    "yourReview": "Su opinión",
    "recently": "Recientemente",
    "excellent": "Excelente",
    "veryGood": "Muy buena",
    "good": "Bien",
    "fair": "Feria",
    "poor": "Pobre",
    "checkingProgress": "Comprobar el progreso",
    "loadingReviews": "Cargando Reseñas",
    "submittingReview": "Enviar revisión",
    "reviewSubmitted": "Revisión enviada",
    "thankYouForReview": "Gracias por su comentario",
    "helpful": "Útil",
    "notHelpful": "No es útil",
    "markAsHelpful": "Marcar como útil",
    "markAsNotHelpful": "Marcar como no útil",
    "completeToReview": "Completa el cuestionario para repasar",
    "takeQuizFirst": "Realice primero un cuestionario",
    "finishTopicToReview": "Finalizar el tema a revisar"
  },
  "translation": {
    "selectLanguage": "Seleccionar idioma",
    "languagePreferenceSaved": "Su preferencia de idioma se guardará para futuras visitas",
    "translating": "Traducir...",
    "translationComplete": "Traducción completa",
    "translationError": "Error de traducción",
    "helpTranslate": "Ayuda a traducir esto",
    "noTranslationAvailable": "No hay traducción disponible",
    "loadingTranslations": "Cargando traducciones...",
    "checkingTranslations": "Comprobación de las traducciones existentes...",
    "savingTranslations": "Guardar traducciones...",
    "autoTranslating": "Traducción automática...",
    "translatingQuestion": "Traducir pregunta",
    "originalText": "Original",
    "loadingExistingTranslations": "Cargando traducciones existentes...",
    "translateContent": "Traducir contenido",
    "allQuestionsTranslated": "Todas las preguntas ya traducidas",
    "translationNeeded": "Traducción necesaria",
    "helpTranslateContent": "¿Le gustaría ayudar a traducirlo?",
    "translationTest": "Prueba de traducción",
    "translationTestResult": "Resultado de la prueba de traducción",
    "translationTestFailed": "Error en la prueba de traducción",
    "initializingTranslationService": "Inicializando el servicio de traducción...",
    "translated": "Traducido",
    "original": "Original",
    "availableTranslations": "Traducciones disponibles",
    "fullyTranslated": "Totalmente traducido",
    "helpTranslateDescription": "Ayude a que CivicSense sea accesible en más idiomas",
    "contributeTranslation": "Ayuda a traducir esto",
    "contributeTitle": "Ayuda a traducir CivicSense",
    "contributeMessage": "¿Quieres ayudar a que CivicSense sea accesible a más gente contribuyendo con traducciones?",
    "getStarted": "Comenzar",
    "thankYou": "Gracias",
    "contactInstructions": "Póngase en contacto con nosotros en translate@civicsense.com para empezar a contribuir con traducciones.",
    "dontSeeLanguage": "¿No ve su idioma?",
    "requestLanguage": "Solicite un nuevo idioma o preséntese voluntario para ayudar a traducir",
    "analyzingContent": "Analizar el contenido...",
    "translatingToLanguage": "Traduciendo a {{language}}...",
    "optimizingLayout": "Optimizar el diseño...",
    "elementsTranslated": "elementos {{count}} traducidos"
  },
  "sources": {
    "analysisOverview": "Análisis general",
    "politicalBias": "Sesgo político",
    "factualRating": "Valoración de los hechos",
    "transparency": "Transparencia",
    "analysisSummary": "Resumen del análisis",
    "topicRelevanceCheck": "Comprobación de la relevancia del tema",
    "validationDetails": "Detalles de validación",
    "strengths": "Puntos fuertes",
    "areasForImprovement": "Áreas de mejora",
    "redFlags": "Banderas rojas",
    "recommendations": "Recomendaciones",
    "readFullArticle": "Leer el artículo completo",
    "loadingAnalysis": "Cargando análisis...",
    "analyzed": "ANALIZADO",
    "credibility": "Credibilidad"
  },
  "languages": {
    "english": "Inglés",
    "spanish": "Español",
    "chinese": "Chino",
    "vietnamese": "Vietnamita",
    "arabic": "árabe",
    "hindi": "हिन्दी",
    "french": "Francés",
    "german": "Alemán",
    "portuguese": "Portugués",
    "russian": "Ruso",
    "japanese": "Japonés (idioma)",
    "korean": "coreano",
    "italian": "Italiano"
  },
  "actions": {
    "save": "Guardar",
    "cancel": "Cancelar",
    "delete": "Borrar",
    "edit": "Editar",
    "share": "Compartir",
    "copy": "Copia",
    "download": "Descargar",
    "upload": "Cargar",
    "refresh": "Actualizar",
    "retry": "Reintentar",
    "tryAgain": "Inténtelo de nuevo",
    "continue": "Continúe en",
    "next": "Siguiente",
    "previous": "Anterior",
    "finish": "Acabado",
    "submit": "Enviar",
    "confirm": "Confirme",
    "yes": "Sí",
    "no": "No",
    "ok": "OK",
    "dismiss": "Desestimar"
  },
  "status": {
    "loading": "Cargando...",
    "saving": "Ahorrar...",
    "saved": "Guardado",
    "error": "Error",
    "success": "Éxito",
    "warning": "Advertencia",
    "info": "Información",
    "completed": "Completado",
    "failed": "Fallido",
    "connecting": "Conectando...",
    "connected": "Conectado",
    "disconnected": "Desconectado",
    "offline": "Fuera de línea",
    "online": "En línea",
    "syncing": "Sincronización...",
    "synced": "Sincronizado"
  },
  "errors": {
    "networkError": "Error de red. Compruebe su conexión.",
    "serverError": "Error en el servidor. Vuelva a intentarlo más tarde.",
    "unknownError": "Se ha producido un error desconocido.",
    "notFound": "Contenido no encontrado.",
    "unauthorized": "No está autorizado a acceder a este contenido.",
    "forbidden": "El acceso a este contenido está prohibido.",
    "timeout": "Solicitud agotada. Por favor, inténtelo de nuevo.",
    "connectionLost": "Conexión perdida. Compruebe su conexión a Internet.",
    "invalidInput": "Entrada no válida. Por favor, compruebe su entrada.",
    "requiredField": "Este campo es obligatorio.",
    "loadingFailed": "Error al cargar el contenido.",
    "savingFailed": "No se han podido guardar los cambios.",
    "uploadFailed": "Carga fallida.",
    "downloadFailed": "Descarga fallida."
  },
  "time": {
    "now": "ahora",
    "today": "hoy",
    "yesterday": "ayer",
    "tomorrow": "tomorrow",
    "thisWeek": "esta semana",
    "lastWeek": "la semana pasada",
    "thisMonth": "este mes",
    "lastMonth": "último mes",
    "minutesAgo": "hace minutos",
    "hoursAgo": "hace horas",
    "daysAgo": "días atrás",
    "weeksAgo": "semanas atrás",
    "monthsAgo": "hace meses"
  },
  "quiz": {
    "question": "Pregunta",
    "questions": "Preguntas",
    "answer": "Respuesta",
    "answers": "Respuestas",
    "correct": "Correct",
    "incorrect": "Incorrecto",
    "explanation": "Explicación",
    "hint": "Sugerencia",
    "score": "Puntuación",
    "results": "Resultados",
    "startQuiz": "Iniciar Cuestionario",
    "nextQuestion": "Siguiente pregunta",
    "previousQuestion": "Pregunta anterior",
    "finishQuiz": "Finalizar Cuestionario",
    "retakeQuiz": "Volver al cuestionario",
    "reviewAnswers": "Revisar respuestas",
    "timeRemaining": "Tiempo restante",
    "questionNumber": "Pregunta",
    "totalQuestions": "Total de preguntas",
    "correctAnswers": "Respuestas correctas",
    "incorrectAnswers": "Respuestas incorrectas",
    "finalScore": "Puntuación final",
    "complete": "Cuestionario completado",
    "of": "de",
    "title": "Cuestionario",
    "loadingQuestion": "Pregunta de carga...",
    "unsupportedQuestionType": "Tipo de pregunta no admitida",
    "questionsComplete": "Preguntas completas",
    "timeUp": "¡Se acabó el tiempo!",
    "pauseQuiz": "Pausa Quiz",
    "resumeQuiz": "Cuestionario",
    "exitQuiz": "Prueba de salida",
    "saveProgress": "Salvar el progreso",
    "restoreProgress": "Restablecer el progreso",
    "quizMode": "Cuestionario de moda",
    "practiceMode": "Modo de práctica",
    "testMode": "Modo de prueba",
    "selectAnswer": "Seleccionar respuesta",
    "submitAnswer": "Enviar respuesta",
    "showExplanation": "Mostrar explicación",
    "hideExplanation": "Ocultar explicación",
    "yourAnswer": "Su respuesta",
    "correctAnswer": "Respuesta correcta",
    "continueToNext": "Continuar",
    "questionTypes": {
      "multipleChoice": "Elección múltiple",
      "trueFalse": "Verdadero/Falso",
      "shortAnswer": "Respuesta corta",
      "fillInBlank": "Rellene el espacio en blanco",
      "matching": "A juego",
      "ordering": "Pedidos",
      "crossword": "Crucigrama"
    },
    "multipleChoice": "Elección múltiple",
    "trueFalse": "Verdadero/Falso",
    "shortAnswer": "Respuesta corta",
    "fillInBlank": "Rellene el espacio en blanco",
    "matching": "A juego",
    "ordering": "Pedidos",
    "crossword": "Crucigrama",
    "accuracy": "Precisión",
    "timeSpent": "Tiempo empleado",
    "averageTime": "Tiempo medio",
    "breakdown": "Avería",
    "recommendations": "Recomendaciones",
    "questionsAnswered": "Preguntas contestadas",
    "questionsSkipped": "Preguntas omitidas",
    "percentageScore": "Porcentaje Puntuación",
    "passingScore": "Aprobado",
    "passed": "Aprobado",
    "failed": "Fallido",
    "tryAgain": "Inténtelo de nuevo",
    "viewReview": "Ver reseña",
    "backToTopics": "Volver a Temas",
    "difficulty": {
      "easy": "Fácil",
      "medium": "Medio",
      "hard": "Duro"
    }
  },
  "common": {
    "loading": "Cargando...",
    "error": "Error",
    "success": "Éxito",
    "cancel": "Cancelar",
    "confirm": "Confirme",
    "save": "Guardar",
    "delete": "Borrar",
    "edit": "Editar",
    "done": "Hecho",
    "close": "Cerrar",
    "back": "Volver",
    "next": "Siguiente",
    "previous": "Anterior",
    "skip": "Saltar",
    "retry": "Reintentar"
  },
  "gameRoom": {
    "questionsPreview": "Preguntas",
    "settings": "Ajustes",
    "sources": "Fuentes",
    "quizSettings": "Configuración del cuestionario",
    "showHints": "Mostrar consejos",
    "getHelpfulClues": "Obtén pistas útiles cuando estés atascado",
    "showExplanations": "Mostrar explicaciones",
    "learnWhyAnswersCorrect": "Saber por qué las respuestas son correctas o incorrectas",
    "hardMode": "Modo Difícil",
    "hardModeDescription": "Sin pistas/explicaciones, 15 por pregunta",
    "timeLimit": "Límite de tiempo",
    "noTimeLimit": "Sin límite de tiempo",
    "estimatedTime": "Tiempo estimado",
    "questionsAvailable": "preguntas disponibles",
    "getReady": "Prepárate para poner a prueba tus conocimientos",
    "trustedSources": "Fuentes de confianza detrás de este contenido",
    "credibilityStandards": "Todas las fuentes cumplen nuestras normas de credibilidad"
  },
  "onboarding": {
    "welcome": "¡Bienvenido a CivicSense!",
    "welcomeTitle": "Bienvenido a CivicSense",
    "welcomeSubtitle": "Pongamos en marcha experiencias personalizadas de aprendizaje cívico",
    "getStarted": "Comenzar",
    "skip": "Saltar",
    "exploreOnOwn": "Exploraré por mi cuenta",
    "timeToComplete": "5-10 minutos para completar",
    "personalizedLearning": "Aprendizaje personalizado",
    "personalizedLearningDesc": "Cuestionarios personalizados en función de sus intereses",
    "communityLearning": "Aprendizaje comunitario",
    "communityLearningDesc": "Aprenda con otras personas de su comunidad",
    "trackProgress": "Seguimiento del progreso",
    "trackProgressDesc": "Vea cómo crecen sus conocimientos cívicos con el tiempo",
    "learnTogether": "Aprender juntos",
    "learnTogetherDesc": "Desafía a tus amigos en pruebas multijugador",
    "earnAchievements": "Conseguir logros",
    "earnAchievementsDesc": "Desbloquea insignias a medida que domines temas",
    "personalizeExperience": "Personalizar la experiencia",
    "personalizeExperienceDesc": "Personalice su itinerario de aprendizaje",
    "learningStyle": "Estilo de aprendizaje",
    "learningStyleDesc": "¿Cómo prefiere aprender?",
    "visual": "Visual",
    "visualDesc": "Aprender a través de imágenes y diagramas",
    "reading": "Lectura",
    "readingDesc": "Aprender a través de textos y artículos",
    "mixed": "Mixto",
    "mixedDesc": "Combinar el aprendizaje visual y el textual",
    "difficultyLevel": "Nivel de dificultad",
    "difficultyLevelDesc": "Elige tu dificultad inicial",
    "beginner": "Principiante",
    "beginnerDesc": "Nuevo en temas cívicos",
    "intermediate": "Intermedio",
    "intermediateDesc": "Algunos conocimientos cívicos",
    "adaptive": "Adaptable",
    "adaptiveDesc": "Ajusta la dificultad a medida que aprendes",
    "location": "Ubicación",
    "locationOptional": "Ubicación (opcional)",
    "city": "Ciudad",
    "state": "Estado",
    "zipCode": "Código postal",
    "dailyReminders": "Recordatorios diarios",
    "dailyRemindersDesc": "Recibir notificaciones sobre nuevos contenidos",
    "whatsNext": "¿Y ahora qué?",
    "whatsNextDesc": "Comencemos su viaje de aprendizaje cívico",
    "completeSetup": "Configuración completa",
    "invalidZipCode": "Código postal no válido",
    "invalidZipCodeDesc": "Introduzca un código postal válido de 5 dígitos",
    "invalidState": "Estado no válido",
    "invalidStateDesc": "Introduzca un estado válido",
    "invalidCity": "Ciudad no válida",
    "invalidCityDesc": "Introduzca un nombre de ciudad válido",
    "zipCodePlaceholder": "Introduzca el código postal",
    "cityPlaceholder": "Introduzca la ciudad",
    "statePlaceholder": "Introduzca el estado",
    "stateLocationDesc": "Tu estado nos ayuda a mostrar contenido local relevante",
    "cityLocationDesc": "Tu ciudad nos ayuda a personalizar la información cívica",
    "zipCodeLocationDesc": "Su código postal nos ayuda a encontrar representantes locales",
    "categorySelectionTitle": "Elige tus intereses",
    "categorySelectionDesc": "Seleccione los temas sobre los que desea aprender",
    "chooseTopics": "Elegir temas",
    "selectInterests": "Seleccione sus intereses",
    "categoryLoading": "Cargando categorías...",
    "categoryLoadingError": "Error al cargar las categorías",
    "questionsAvailable": "preguntas disponibles",
    "atLeastOneCategory": "Seleccione al menos una categoría",
    "fallbackCategoryDesc": "Explorar diversos temas cívicos",
    "step": "Paso",
    "choosePlayStyle": "Elegir estilo de juego",
    "setChallenge": "Set Challenge",
    "customize": "Personalice",
    "soloChallenge": "Desafío en solitario",
    "soloChallengeDescription": "Ponga a prueba sus conocimientos individualmente",
    "orUseCustomSettings": "O utilizar ajustes personalizados"
  },
  "multiplayer": {
    "title": "Multijugador",
    "connectionError": "Error de conexión",
    "failedToJoin": "No se ha podido entrar en la sala. Por favor, inténtelo de nuevo.",
    "failedToStart": "No se ha podido iniciar el juego. Por favor, inténtelo de nuevo.",
    "leaveRoomConfirm": "¿Seguro que quieres salir de esta habitación?",
    "inviteMessage": "¡Únete a mi sala de concursos CivicSense! Código: {{roomCode}}\n\nDescarga la aplicación e introduce este código para jugar juntos.",
    "inviteTitle": "Únete a mi sala de concursos CivicSense",
    "aiPlayer": "Jugador IA",
    "humanPlayer": "Jugador humano",
    "sharingFailed": "No se ha podido compartir. Por favor, inténtelo de nuevo.",
    "getReadyToPlay": "Prepárate para jugar",
    "startReview": "Inicio Revisión",
    "waitingForPlayers": "A la espera de jugadores",
    "waitingForHost": "Esperando al anfitrión",
    "gameMode": "Modo de juego",
    "questions": "Preguntas",
    "features": "Características",
    "hints": "Sugerencias",
    "explanations": "Explicaciones",
    "teamMode": "Equipo Moda",
    "powerUps": "Subidas de tensión",
    "npcBattle": "Batalla NPC",
    "testYourKnowledge": "Pon a prueba tus conocimientos",
    "skillLevel": "Nivel de conocimientos",
    "roomCode": "Código de habitación",
    "maxPlayers": "Jugadores máximos",
    "currentPlayers": "Jugadores actuales",
    "leaderboard": "Clasificación",
    "chat": "Chat",
    "settings": "Ajustes",
    "gameStartingSoon": "El juego empieza pronto",
    "getReadyFirstQuestion": "Prepárese para la primera pregunta",
    "battleStarting": "Comienzo de la batalla",
    "firstQuestionLoading": "Carga de la primera pregunta",
    "question": "Pregunta",
    "questionNumber": "Pregunta",
    "hint": "Sugerencia",
    "showHint": "Mostrar pista",
    "submitAnswer": "Enviar respuesta",
    "explanation": "Explicación",
    "shield": "Escudo",
    "attack": "Ataque",
    "focus": "Enfoque",
    "correct": "Correct",
    "incorrect": "Incorrecto",
    "timeUp": "¡Se acabó el tiempo!",
    "finalScore": "Puntuación final",
    "gameComplete": "Juego Completo",
    "greatJobLearning": "¡Gran trabajo de aprendizaje!",
    "shareResults": "Compartir resultados",
    "continue": "Continúe en",
    "victory": "¡Victoria!",
    "goodTry": "¡Buen intento!",
    "correctAnswers": "Respuestas correctas",
    "accuracy": "Precisión",
    "playAgain": "Volver a jugar",
    "exit": "Salida",
    "ready": "Listo",
    "notReady": "No está listo",
    "thinking": "Pensar",
    "answered": "Respuesta",
    "roomChat": "Sala de chat",
    "players": "Jugadores",
    "typeMessage": "Tipo de mensaje",
    "enterToSend": "Entrar para enviar",
    "beRespectful": "Sea respetuoso",
    "playerJoined": "Jugador Incorporado",
    "playerLeft": "Jugador Izquierda",
    "gameStarting": "Inicio del juego",
    "welcomeToQuiz": "Bienvenido al Quiz",
    "allowNewPlayers": "Permitir nuevos jugadores",
    "allowNewPlayersDesc": "Permitir la entrada de nuevos jugadores",
    "enableBoosts": "Activar aumentos",
    "enableBoostsDesc": "Habilitar potenciadores para los jugadores",
    "showHints": "Mostrar consejos",
    "showHintsDesc": "Mostrar pistas a los jugadores",
    "autoAdvance": "Auto Advance",
    "autoAdvanceDesc": "Avanzar preguntas automáticamente",
    "realTimeScores": "Resultados en tiempo real",
    "realTimeScoresDesc": "Mostrar resultados en tiempo real",
    "enableChat": "Activar chat",
    "enableChatDesc": "Activar el chat para los jugadores",
    "connectionLost": "Conexión perdida",
    "failedToSubmitAnswer": "Respuesta fallida",
    "networkError": "Error de red",
    "ai": "AI",
    "host": "Anfitrión",
    "titleDescription": "Descripción",
    "liveGameScreen": "Juego en directo"
  },
  "analytics": {
    "loadingInsights": "Cargando opiniones...",
    "couldNotLoadInsights": "No se ha podido cargar la información de aprendizaje. Por favor, inténtelo de nuevo.",
    "couldNotRefreshInsights": "No se ha podido actualizar la información. Por favor, inténtelo de nuevo.",
    "excellentPerformance": "¡Excelente rendimiento! Ver próximos pasos personalizados.",
    "goodProgress": "¡Buen progreso! Descubre las áreas a mejorar.",
    "keepLearning": "Sigue aprendiendo Obtén consejos de estudio personalizados.",
    "needHelp": "¿Tienes problemas? Obtenga ayuda personalizada."
  },
  "news": {
    "dailyNews": "Noticias diarias",
    "latestNews": "Últimas noticias",
    "articles": "artículos",
    "fetchingFrom": "De AP, Reuters, NPR, BBC, Politico...",
    "noValidArticles": "No se han encontrado artículos válidos tras el filtrado",
    "failedToLoad": "Error al cargar noticias",
    "newsAPI": "Fallo de la API de noticias",
    "unknownError": "Error desconocido",
    "refreshNews": "Actualizar noticias",
    "updating": "Actualizando...",
    "today": "Hoy",
    "yesterday": "Ayer",
    "breakingNews": "Noticias de última hora",
    "newsUpdates": "Noticias",
    "readMore": "Seguir leyendo",
    "readFull": "Leer el artículo completo",
    "source": "Fuente",
    "publishedBy": "Publicado por",
    "lastUpdated": "Última actualización",
    "originalSource": "Fuente original",
    "previousArticle": "Artículo anterior",
    "nextArticle": "Artículo siguiente",
    "backToNews": "Volver a Noticias",
    "filterByCategory": "Filtrar por categoría",
    "sortBy": "Ordenar por",
    "newest": "Más reciente",
    "oldest": "Más antiguo",
    "mostRelevant": "Lo más relevante",
    "noArticlesFound": "No se han encontrado artículos",
    "loadingFailed": "Error al cargar artículos de noticias",
    "tryAgainLater": "Vuelva a intentarlo más tarde",
    "shareArticle": "Compartir artículo",
    "copyLink": "Copiar enlace",
    "linkCopied": "Enlace copiado en el portapapeles",
    "savedToDb": "guardado en BD",
    "ago": "hace"
  },
  "collections": {
    "takeAction": "Actúa",
    "planned": "previsto",
    "completed": "completado",
    "immediateActions": "Medidas inmediatas",
    "immediateActionsDesc": "Se trata de pasos concretos que puedes dar ahora mismo para aplicar lo que has aprendido.",
    "civicEngagementOpportunities": "Oportunidades de participación cívica",
    "civicEngagementDesc": "Conéctese con su comunidad y consiga una mayor repercusión a través de estas oportunidades.",
    "markAsCompleted": "Marcar como completado",
    "yourActionPlan": "Su plan de acción",
    "youvePlannedActions": "Has planeado {{count}} acción{{plural}}",
    "andCompleted": " y completado {{count}}",
    "greatJobTakingAction": "¡Gran trabajo tomando acción en tu aprendizaje cívico! 🎉",
    "keepGoing": "¡Sigue adelante! Actuando es como reforzamos la democracia.",
    "readyToTakeAction": "¿Preparado para pasar a la acción?",
    "checkOffActions": "Marca las acciones que piensas emprender. Cada pequeño paso fortalece la democracia.",
    "outstanding": "¡Excelente!",
    "completedAllActions": "Has completado todas las acciones sugeridas. ¡Estás marcando una verdadera diferencia en tu comunidad!",
    "quickCheck": "Comprobación rápida",
    "complete": "Complete",
    "submitAnswer": "Enviar respuesta",
    "correct": "Correct!",
    "notQuiteRight": "No del todo bien",
    "showHint": "Mostrar pista",
    "hideHint": "Ocultar indio",
    "selectAnAnswer": "Seleccione una respuesta",
    "answerSelected": "Respuesta seleccionada",
    "trueOrFalse": "¿Verdadero o falso?",
    "selectTrueFalse": "Seleccione Verdadero o Falso",
    "yourResponse": "Su respuesta",
    "enterYourAnswer": "Introduce tu respuesta...",
    "submitResponse": "Enviar respuesta",
    "responseRecorded": "Respuesta registrada",
    "thankYouForInput": "Gracias por su aportación. Su respuesta ha sido guardada.",
    "enterYourResponse": "Escriba su respuesta",
    "charactersCount": "{{count}} caracteres",
    "rankingExercise": "Ejercicio de clasificación",
    "dragToReorder": "Arrastre los elementos para reordenarlos de más a menos importante:",
    "rankingComplete": "Clasificación completa",
    "dragToReorderItems": "Arrastrar para reordenar elementos",
    "rankingExplanation": "Explicación de la clasificación",
    "interactiveTimeline": "Cronología interactiva",
    "clickEachEvent": "Haga clic en cada evento para explorarlo ({actual}/{total})",
    "exploreAllEvents": "Explorar todos los eventos",
    "reflection": "Reflexión",
    "reflectionPrompts": "Temas de reflexión",
    "shareYourThoughts": "Comparte tus pensamientos...",
    "saveReflection": "Guardar reflexión",
    "actionChecklist": "Lista de control",
    "actionsCompleted": "{realizadas} de {total} acciones realizadas",
    "primaryAction": "Acción Primaria",
    "bonusActions": "Acciones de bonificación (opcional)",
    "helpfulResources": "Recursos útiles",
    "markAsComplete": "Marcar como completo",
    "actionComplete": "Acción finalizada",
    "takeActionStatus": "Actúa",
    "pending": "Pendiente",
    "contactRepresentatives": "Contacte con sus representantes",
    "contactsReached": "{contactados} de {total} contactos alcanzados",
    "whoToContact": "Con quién ponerse en contacto",
    "messageTemplates": "Plantillas de mensajes",
    "sendWithTemplate": "Enviar con plantilla",
    "visitWebsite": "Visita el sitio web →",
    "alreadyContacted": "Ya contactado",
    "markAsContacted": "Marcar como Contactado",
    "quickPoll": "Encuesta rápida",
    "castVote": "Emitir voto",
    "thanksForVoting": "Gracias por votar",
    "results": "Resultados:",
    "votes": "vota",
    "surveyTitle": "Encuesta",
    "questionProgress": "Pregunta {actual} de {total}",
    "simulationResults": "Resultados de la simulación",
    "yourAnswer": "Tu respuesta...",
    "previous": "Anterior",
    "next": "Siguiente",
    "completeSurvey": "Encuesta completa",
    "externalSurveyDesc": "Esta encuesta está alojada externamente. Haga clic en el siguiente enlace para participar.",
    "openSurvey": "Encuesta abierta",
    "opinionScale": "Escala de opinión",
    "moveSlider": "Mueva el control deslizante para indicar su nivel de acuerdo",
    "submitOpinion": "Enviar opinión",
    "thanksForOpinion": "Gracias por compartir su opinión",
    "stronglyDisagree": "Totalmente en desacuerdo",
    "disagree": "En desacuerdo",
    "neutral": "Neutro",
    "agree": "De acuerdo",
    "stronglyAgree": "Totalmente de acuerdo",
    "policySimulation": "Simulación de políticas",
    "scenario": "Scenario",
    "adjustVariables": "Variables de ajuste",
    "runSimulation": "Ejecutar simulación",
    "rolePlayingExercise": "Ejercicio de rol",
    "chooseYourRole": "Elige tu papel",
    "objectives": "Objetivos:",
    "whatActionTake": "¿Qué acción realizarás esta ronda?",
    "negotiateStakeholders": "Negociar con otras partes interesadas",
    "gatherMoreInfo": "Recopilar más información",
    "rolePlayComplete": "Juego de rol ¡completado!",
    "yourDecisions": "Sus decisiones",
    "decisionPath": "Ruta de decisión",
    "decisionPoint": "Punto de decisión",
    "chooseResponse": "Elija su respuesta:",
    "finalOutcome": "Resultado final",
    "reflectionNote": "Considere cómo diferentes opciones podrían haber conducido a diferentes resultados. Las decisiones políticas reales suelen tener consecuencias complejas que no son evidentes a primera vista.",
    "tryDifferentPath": "Probar un camino diferente",
    "yourPath": "Tu camino:",
    "compareAndContrast": "Comparar y contrastar",
    "continueLearning": "Seguir aprendiendo",
    "viewAllCards": "Ver todas las tarjetas",
    "nextCard": "Próxima tarjeta",
    "previousCard": "Anterior",
    "exploreImage": "Explorar la imagen",
    "dragAndDrop": "Arrastrar y soltar",
    "availableItems": "Artículos disponibles",
    "interactiveMap": "Mapa interactivo",
    "checkAnswers": "Comprobar respuestas",
    "allItemsAssigned": "Todas las partidas asignadas",
    "assigned": "asignado",
    "adjustParameters": "Ajustar parámetros",
    "viewResults": "Ver resultados",
    "resetSimulation": "Simulación de reinicio",
    "fillInTheBlanks": "Rellene los espacios en blanco",
    "matchingPairs": "Emparejamiento de parejas",
    "categorizeItems": "Clasificar artículos",
    "progressUpdate": "Avances",
    "wellDone": "Bien hecho",
    "goodEffort": "¡Buen esfuerzo!",
    "keepTrying": "¡Sigue intentándolo!",
    "perfect": "¡Perfecto!",
    "almostThere": "Ya casi está"
  },
  "accessibility": {
    "skipToContent": "Ir al contenido",
    "mainNavigation": "Navegación principal",
    "userMenu": "Menú de usuario",
    "darkModeToggle": "Activar el modo oscuro",
    "languageSelector": "Seleccionar idioma",
    "closeDialog": "Cerrar el diálogo",
    "openMenu": "Abrir menú",
    "closeMenu": "Cerrar menú",
    "loadingContent": "Cargar contenido",
    "expandSection": "Ampliar sección",
    "collapseSection": "Contraer sección",
    "playAudio": "Reproducir audio",
    "pauseAudio": "Pausar audio",
    "stopAudio": "Detener audio",
    "increaseSpeed": "Aumentar la velocidad",
    "decreaseSpeed": "Disminuir la velocidad",
    "goBack": "Volver atrás",
    "openLink": "Abrir enlace",
    "bookmark": "Marcar este tema como favorito",
    "removeBookmark": "Eliminar marcador"
  },
  "settings": {
    "title": "Ajustes",
    "account": "Cuenta",
    "preferences": "Preferencias",
    "notifications": "Notificaciones",
    "privacy": "Privacidad",
    "accessibility": "Accesibilidad",
    "language": "Idioma",
    "theme": "Tema",
    "themes": {
      "light": "Luz",
      "dark": "Oscuro",
      "system": "Sistema"
    },
    "email": "Correo electrónico",
    "password": "Contraseña",
    "changePassword": "Cambiar contraseña",
    "deleteAccount": "Eliminar cuenta",
    "exportData": "Exportar datos",
    "saveChanges": "Guardar cambios",
    "saved": "Ajustes guardados",
    "emailNotifications": "Notificaciones por correo electrónico",
    "pushNotifications": "Notificaciones Push",
    "weeklyDigest": "Resumen semanal",
    "achievementAlerts": "Alertas de logros",
    "soundEffects": "Efectos sonoros",
    "animations": "Animaciones",
    "highContrast": "Alto contraste",
    "largeText": "Texto grande",
    "reducedMotion": "Movimiento reducido",
    "keyboardShortcuts": "Atajos de teclado",
    "timezone": "Zona horaria",
    "dateFormat": "Formato de fecha",
    "giftCredits": "Créditos de regalo",
    "premium": "Premium",
    "subscription": "Suscripción",
    "features": "Características",
    "upgrade": "Actualizar",
    "manage": "Gestione",
    "cancel": "Cancelar",
    "signOut": "Cerrar sesión",
    "accountData": "Datos de la cuenta",
    "displayName": "Mostrar nombre",
    "currentPassword": "Contraseña actual",
    "newPassword": "Nueva contraseña",
    "confirmPassword": "Confirmar contraseña",
    "updateAccount": "Actualizar cuenta",
    "pleaseSignIn": "Inicia sesión para acceder a la configuración",
    "signInToAccess": "Inicia sesión para acceder a la configuración",
    "editProfile": "Editar perfil",
    "fullName": "Nombre y apellidos",
    "fullNameRequired": "Se requiere el nombre completo",
    "bio": "Bio",
    "location": "Ubicación",
    "website": "Página web",
    "country": "País",
    "stateProvince": "Estado/Provincia",
    "city": "Ciudad",
    "profileUpdated": "¡Perfil actualizado! ✅",
    "profileUpdatedMessage": "Los cambios se han guardado correctamente.",
    "great": "¡Estupendo!",
    "discardChanges": "¿Descartar cambios?",
    "discardChangesMessage": "Tienes cambios sin guardar. ¿Estás seguro de que quieres descartarlos?",
    "keepEditing": "Seguir editando",
    "discard": "Descartar",
    "permissionRequired": "Permiso necesario",
    "photoLibraryPermission": "Por favor, permite el acceso a tu biblioteca de fotos para cambiar tu avatar.",
    "uploadFailed": "No se ha podido cargar el avatar. Por favor, inténtalo de nuevo.",
    "autoTranslateContent": "Traducción automática de contenidos",
    "autoTranslateContentDesc": "Traducir automáticamente las preguntas de los cuestionarios y las lecciones",
    "preserveCivicTerms": "Preservar los términos cívicos",
    "preserveCivicTermsDesc": "Mantener la exactitud de los términos cívicos importantes en las traducciones",
    "clearTranslationCache": "Borrar caché de traducción",
    "clearTranslationCacheDesc": "Restablece las traducciones guardadas para obtener contenido nuevo",
    "translationCacheCleared": "La caché de traducción se ha borrado correctamente",
    "translationCacheClearError": "Error al borrar la caché de traducción"
  },
  "survey": {
    "question": "Pregunta",
    "questions": "Preguntas",
    "required": "Requerido",
    "optional": "Opcional",
    "progress": "Progreso",
    "complete": "Complete",
    "submit": "Enviar",
    "next": "Siguiente",
    "previous": "Anterior",
    "skip": "Saltar",
    "save": "Guardar",
    "saveProgress": "Salvar el progreso",
    "loading": "Cargando...",
    "error": "Error",
    "success": "Éxito",
    "pleaseSelectOption": "Seleccione una opción",
    "pleaseProvideAnswer": "Por favor, responda",
    "invalidEmail": "Introduzca una dirección de correo electrónico válida",
    "invalidPhone": "Introduzca un número de teléfono válido",
    "tooManySelections": "Demasiadas selecciones",
    "maxSelections": "Selecciones máximas alcanzadas",
    "selectAtLeast": "Seleccione al menos",
    "selectAtMost": "Seleccione como máximo",
    "charactersRemaining": "caracteres restantes",
    "wordLimit": "Límite de palabras superado",
    "fileUpload": "Carga de archivos",
    "chooseFile": "Elegir archivo",
    "removeFile": "Eliminar archivo",
    "uploadError": "Error de carga",
    "stronglyDisagree": "Totalmente en desacuerdo",
    "disagree": "En desacuerdo",
    "neutral": "Neutro",
    "agree": "De acuerdo",
    "stronglyAgree": "Totalmente de acuerdo",
    "pleaseSpecify": "Por favor, especifique...",
    "other": "Otros",
    "none": "Ninguno",
    "all": "Todos",
    "completed": "Completado",
    "thankYou": "Gracias",
    "submissionComplete": "Su envío se ha completado",
    "viewResults": "Ver resultados",
    "retake": "Retomar",
    "share": "Compartir"
  },
  "audio": {
    "play": "Jugar",
    "pause": "Pausa",
    "stop": "Stop",
    "resume": "Currículum",
    "restart": "Reinicie",
    "mute": "Silenciar",
    "unmute": "Desactivar",
    "volume": "Volumen",
    "speed": "Velocidad",
    "voice": "Voz",
    "settings": "Ajustes",
    "audioControls": "Controles de audio",
    "voiceSettings": "Ajustes de voz",
    "quality": "Calidad",
    "high": "Alta",
    "medium": "Medio",
    "low": "Bajo",
    "autoPlay": "Reproducción automática",
    "loop": "Bucle",
    "highlighting": "Resaltado de palabras",
    "cloudTTS": "Nube TTS",
    "browserTTS": "Navegador TTS",
    "language": "Idioma",
    "male": "Hombre",
    "female": "Mujer",
    "neutral": "Neutro",
    "loading": "Cargando...",
    "error": "Error de audio",
    "notSupported": "Audio no compatible",
    "recovery": "Recuperar audio",
    "testAudio": "Audio de prueba",
    "readPage": "Leer la página",
    "readSelection": "Leer selección",
    "keyboardShortcuts": "Atajos de teclado",
    "diagnostics": "Diagnóstico",
    "usage": "Utilización",
    "charactersUsed": "Personajes utilizados",
    "estimatedCost": "Coste estimado",
    "voiceCount": "Recuento de voces",
    "speaking": "En",
    "pending": "Pendiente",
    "paused": "En pausa",
    "lastUpdate": "Última actualización"
  },
  "profileScreenTitle": "Mi perfil",
  "loadingProfile": "Cargando tu perfil...",
  "redirectingToLogin": "Redirigiendo al inicio de sesión...",
  "leaderboard": {
    "title": "Clasificación",
    "loadingLeaderboard": "Cargando clasificación...",
    "yourRanking": "Su clasificación",
    "currentRank": "Rango actual",
    "topPercentile": "Percentil superior",
    "totalUsers": "Usuarios totales",
    "today": "Hoy",
    "thisWeek": "Esta semana",
    "thisMonth": "Este mes",
    "allTime": "Todos los tiempos",
    "score": "Puntuación",
    "xp": "XP",
    "streak": "Raya",
    "quizzes": "cuestionarios",
    "achievements": "logros",
    "you": "(Tú)",
    "takeQuizToClimb": "¡Haz una prueba para subir!",
    "new": "NUEVO"
  },
  "search": {
    "title": "Buscar en",
    "placeholder": "Buscar colecciones y temas...",
    "clearHistory": "Borrar el historial de búsqueda",
    "analytics": "{{count}} búsquedas - {{viewed}} artículos vistos",
    "streak": "{{count}} racha de días",
    "loadingData": "Cargando datos de búsqueda...",
    "searching": "Búsqueda de colecciones y temas...",
    "keepTyping": "Sigue escribiendo...",
    "minCharacters": "Introduzca al menos 2 caracteres para iniciar la búsqueda",
    "filterAll": "Todos",
    "filterCollections": "Colecciones",
    "filterTopics": "Temas",
    "noResults": "No se han encontrado resultados",
    "noResultsHint": "Intente buscar otras palabras clave, como \"Constitución\", \"Elecciones\" o \"Tribunal Supremo\"",
    "continueLearning": "Seguir aprendiendo",
    "pickUpWhereLeft": "Continúa donde lo dejaste",
    "recommended": "Recomendado",
    "recentSearches": "Búsquedas recientes",
    "clearAll": "Borrar todo",
    "popularTopics": "Temas populares",
    "tapToSearch": "Toque para buscar rápidamente",
    "searchTips": "Consejos de búsqueda",
    "tip1": "Pruebe temas específicos como \"Primera Enmienda\" o \"Colegio Electoral\"",
    "tip2": "Los artículos que has visto recientemente aparecen primero en los resultados",
    "tip3": "Tu historial de búsqueda nos ayuda a mostrarte mejores recomendaciones",
    "collection": "Colección",
    "topic": "Tema",
    "questionCount": "{{count}} preguntas",
    "recent": "Recientes"
  },
  "profile": {
    "title": "Mi perfil",
    "loadingProfile": "Cargando tu perfil...",
    "redirectingToLogin": "Redirigiendo al inicio de sesión...",
    "yourProgress": "Tu progreso",
    "calendarIntegration": "Integración del calendario",
    "googleCalendarSync": "Sincronización con Google Calendar",
    "googleCalendarSyncDesc": "Sincroniza tu calendario de estudio con Google Calendar",
    "dailyQuizReminders": "Recordatorios diarios",
    "dailyQuizRemindersDesc": "Recibir recordatorios sobre los cuestionarios diarios",
    "smartScheduling": "Programación inteligente",
    "smartSchedulingDesc": "Tiempos de estudio óptimos basados en IA",
    "learningPodSessions": "Sesiones de formación",
    "learningPodSessionsDesc": "Recordatorios de las sesiones de estudio en grupo",
    "lastSynced": "Última sincronización",
    "smartStudyRecommendations": "Recomendaciones del estudio Smart",
    "scheduleThisTime": "Programar este momento",
    "learningPods": "Módulos de aprendizaje",
    "constitutionalLawStudyGroup": "Grupo de Estudio de Derecho Constitucional",
    "membersOnline": "miembros - {{online}} en línea ahora",
    "billOfRightsReviewSession": "Sesión de revisión de la Carta de Derechos",
    "managePods": "Gestionar Pods",
    "editProfile": "Editar perfil",
    "updateYourInformation": "Actualice su información",
    "preferences": "Preferencias",
    "learningAndNotifications": "Aprendizaje y notificaciones",
    "exportLearningProgress": "Exportar el progreso del aprendizaje",
    "howWouldYouLikeToShare": "¿Cómo le gustaría compartir sus progresos?",
    "exportAsPDF": "Exportar como PDF",
    "shareWithPod": "Compartir con Pod",
    "generateReport": "Generación del informe analítico de CivicSense",
    "shareReport": "Compartir informe",
    "exportFailed": "Exportación fallida",
    "exportError": "No se ha podido generar el informe de análisis del aprendizaje. Inténtelo de nuevo.",
    "updateProfilePhoto": "Actualizar foto de perfil",
    "choosePhotoMethod": "Elige cómo quieres añadir tu foto",
    "camera": "Cámara",
    "photoLibrary": "Fototeca",
    "profilePhotoUpdated": "¡Foto de perfil actualizada correctamente!",
    "uploadPhotoFailed": "No se ha podido subir la foto de perfil",
    "profileCompletion": "Perfil {{percent}}% completo",
    "profileCompletePercent": "Perfil {{percent}}% completo",
    "quizzes": "Cuestionarios",
    "avgScore": "Puntuación media",
    "dayStreak": "Racha diurna",
    "studyTime": "Tiempo de estudio",
    "achievements": "Logros",
    "viewDetailedStats": "Ver estadísticas detalladas",
    "connectedViaGoogle": "Conectado a través de Google",
    "appVersion": "CivicSense v1.0.0 - Hecho con ❤️ para la democracia",
    "madeWithLoveForDemocracy": "Hecho con ❤️ para la democracia"
  },
  "saved": {
    "title": "Guardado",
    "subtitle": "Tus favoritos y progresos",
    "loadingSavedContent": "Cargando el contenido guardado...",
    "collections": "Colecciones",
    "createCollection": "Cree",
    "organizeYourLearning": "Organice su aprendizaje",
    "organizeYourLearningDesc": "Crea colecciones para organizar los contenidos guardados en carpetas temáticas y estudiar más fácilmente.",
    "lessons": "Lecciones aprendidas",
    "lessonsDesc": "Cursos de varios pasos de CivicSense",
    "myCollections": "Mis colecciones",
    "myCollectionsDesc": "Tus carpetas de contenido organizadas",
    "createYourFirstCollection": "Crea tu primera colección para organizar los contenidos guardados",
    "filterContent": "Filtrar contenido",
    "allContent": "Todos",
    "topics": "Temas",
    "quizResults": "Quiz Results",
    "customQuizzes": "Cuestionarios personalizados",
    "bookmarks": "Marcadores",
    "noSavedLessons": "Sin lecciones guardadas",
    "noSavedTopics": "No hay temas guardados",
    "noQuizResults": "No Quiz Results",
    "noBookmarks": "Sin marcadores",
    "noSavedItems": "No hay elementos guardados",
    "exploreContent": "Explorar contenido",
    "selectItems": "Seleccionar artículos",
    "itemsSelected": "{{count}} item{{plural}} seleccionado",
    "selectItemsToOrganize": "Seleccionar elementos para organizar",
    "organizeSelectedItems": "Organizar los elementos seleccionados",
    "moveToCollection": "Pasar a Recogida",
    "removeItem": "Quitar artículo",
    "removeItemConfirm": "¿Estás seguro de que quieres eliminar este elemento guardado?",
    "highlightedText": "Texto resaltado",
    "textSnippet": "Fragmento de texto",
    "customQuiz": "Cuestionario personalizado",
    "continueYourCivicsAssessment": "Continúa tu evaluación de educación cívica",
    "questionsCompleted": "{{completed}} de {{total}} preguntas contestadas",
    "started": "Iniciado {{date}}",
    "scoreLabel": "Puntuación",
    "xpEarned": "+__MARCADOR_0__ XP",
    "questions": "Preguntas",
    "draft": "PROYECTO",
    "published": "PUBLICADO",
    "savedRecently": "Guardado {{time}}",
    "savedTime": "Guardado {{time}} hace",
    "keepGoing": "¡Adelante! 🎯",
    "nothingNewToday": "¿Nada nuevo hoy? ¡Momento perfecto para explorar! 📚",
    "nothingNewTodayDesc": "Pruebe a navegar a otras fechas utilizando las flechas de arriba, o explore estas opciones de aprendizaje a continuación.",
    "currentEvents": "Actualidad",
    "currentEventsDesc": "Toca cualquier historia para crear un cuestionario sobre ese tema",
    "findingCurrentEvents": "Encontrar eventos actuales para {{date}}...",
    "continueWhereLeftOff": "Continúa donde lo dejaste",
    "orExploreMore": "O explore más",
    "continueLearning": "Seguir aprendiendo",
    "exploreQuizTopics": "Explorar los temas del concurso",
    "exploreQuizTopicsDesc": "Descubra cuestionarios sobre gobierno, derechos y participación ciudadana",
    "takeCivicsAssessment": "Realizar la evaluación de educación cívica",
    "takeCivicsAssessmentDesc": "Ponga a prueba sus conocimientos sobre el gobierno y la democracia estadounidenses",
    "reviewSavedContent": "Revisar contenido guardado",
    "reviewSavedContentDesc": "Sigue aprendiendo de tus temas favoritos",
    "createCustomContent": "Crear contenido personalizado",
    "createCustomContentDesc": "Diseñe sus propios temas y preguntas",
    "pro": "PRO"
  },
  "learn": {
    "title": "Aprenda",
    "loadingQuizCollections": "Cargando colecciones de concursos...",
    "usingOfflineData": "Uso de los datos del cuestionario sin conexión - red no disponible",
    "featuredLessons": "Lecciones destacadas",
    "featuredLessonsDesc": "Colección de lecciones sobre temas de actualidad",
    "allCollections": "Todas las colecciones",
    "allCollectionsDesc": "Pruebas exhaustivas de conocimientos cívicos",
    "collections": "{{count}} colecciones",
    "topics": "Temas",
    "topicsDesc": "Explorar temas cívicos concretos con preguntas específicas",
    "noQuizCollections": "No hay colecciones de cuestionarios disponibles",
    "noQuizCollectionsOffline": "Compruebe su conexión a Internet y vuelva a intentarlo",
    "noQuizCollectionsOnline": "Las nuevas colecciones de concursos aparecerán aquí cuando estén disponibles",
    "quizDataSource": "Fuente de datos del cuestionario: {{source}}",
    "liveAPI": "API en directo",
    "offlineCache": "Caché fuera de línea",
    "showingRealTimeData": "Mostrar en tiempo real las colecciones de cuestionarios del servidor",
    "usingCachedData": "Uso de los datos del cuestionario en caché: algunos contenidos pueden estar obsoletos",
    "new": "Nuevo",
    "featured": "Destacados",
    "estimatedTime": "{{time}} min",
    "completionRate": "{{rate}}% finalización",
    "completion": "finalización",
    "continue": "Continúe en",
    "start": "Inicio",
    "available": "Disponible",
    "difficulty": "Dificultad",
    "searchTopics": "Buscar temas"
  },
  "home": {
    "welcomeBack": "Bienvenido de nuevo, {{name}}",
    "welcome": "CivicSense",
    "citizen": "Ciudadano",
    "loadingYourCivicJourney": "Cargando tu viaje cívico...",
    "loadingContent": "Cargando contenido...",
    "today": "Hoy",
    "dailyChallenge": "Reto diario ({{completed}} de {{total}})",
    "questionsOf": "{{completed}} de {{total}}",
    "dayStreak": "{{count}} day{{plural}}",
    "days": "días",
    "day": "día",
    "loadingDate": "Cargando {{date}}",
    "noFeaturedToday": "Hoy no hay temas destacados",
    "noFeaturedTodayDesc": "Vuelve más tarde para ver noticias de última hora y contenidos destacados",
    "checkBackLater": "Vuelve más tarde para ver noticias de última hora y contenidos destacados",
    "keepGoingTarget": "¡Adelante! 🎯",
    "navigateToOtherDates": "Pruebe a navegar a otras fechas utilizando las flechas de arriba, o explore estas opciones de aprendizaje a continuación.",
    "exploreMoreOptions": "explore estas opciones de aprendizaje",
    "todaysCurrentEvents": "Actualidad",
    "currentEventsForDate": "{{date}} Actualidad",
    "tapAnyStoryToCreate": "Toca cualquier historia para crear un cuestionario sobre ese tema",
    "findingCurrentEventsFor": "Encontrar eventos actuales para {{date}}...",
    "exploreQuizTopics": "Explorar los temas del concurso",
    "exploreQuizTopicsDesc": "Descubra cuestionarios sobre gobierno, derechos y participación ciudadana",
    "takeCivicsAssessment": "Realizar la evaluación de educación cívica",
    "takeCivicsAssessmentDesc": "Ponga a prueba sus conocimientos sobre el gobierno y la democracia estadounidenses",
    "reviewSavedContent": "Revisar contenido guardado",
    "reviewSavedContentDesc": "Sigue aprendiendo de tus temas favoritos",
    "createCustomContent": "Crear contenido personalizado",
    "createCustomContentDesc": "Diseñe sus propios temas y preguntas",
    "designYourOwnTopics": "Diseñe sus propios temas y preguntas",
    "proFeature": "PRO",
    "startReview": "Inicio Revisión",
    "readMore": "Seguir leyendo",
    "signUpToSaveProgress": "Regístrate para guardar tus progresos y desbloquear logros",
    "yourProgressMatters": "Tu progreso importa",
    "preserveYourLearning": "Conserve su itinerario de aprendizaje y siga ampliando sus conocimientos cívicos",
    "getStarted": "Comenzar",
    "nothingNewToday": "¿Nada nuevo hoy? ¡Momento perfecto para explorar! 📚",
    "keepGoing": "¡Adelante! 🎯"
  }
};

export default uiStringsES;
