import type { UIStrings } from './ui-strings';

export const uiStringsFR: UIStrings = {
  "navigation": {
    "back": "Retour",
    "close": "Fermer",
    "menu": "Menu",
    "home": "Accueil",
    "topics": "Thèmes",
    "learn": "Explorer",
    "profile": "Profil",
    "settings": "Paramètres",
    "bookmarks": "Signets",
    "history": "L'histoire",
    "signInToPlay": "Se connecter pour jouer",
    "signInToSaveProgress": "S'identifier pour sauvegarder la progression"
  },
  "topic": {
    "loading": "Chargement des détails du sujet...",
    "loadingDetails": "Chargement des détails...",
    "backToTopics": "Retour aux thèmes",
    "share": "Partager le sujet",
    "bookmark": "Ajouter aux favoris",
    "removeBookmark": "Supprimer un signet",
    "bookmarkThis": "Ajouter aux favoris",
    "translateThisPage": "Traduire cette page",
    "showOriginal": "Montrer l'original",
    "whyThisMatters": "Pourquoi c'est important",
    "sourcesAndReferences": "Sources et références",
    "takingTheQuiz": "Répondre au questionnaire",
    "startQuiz": "Répondre au quiz",
    "questionsLabel": "Questions",
    "estimatedMinutesLabel": "Est. Min.",
    "ratingLabel": "Evaluation",
    "publishedLabel": "Publié",
    "levelLabel": "Niveau",
    "difficultyLabel": "Difficulté",
    "questionsCount": "Total Questions",
    "estimatedTime": "Temps estimé",
    "level": "Niveau",
    "difficulty": "Difficulté",
    "easy": "Facile",
    "medium": "Moyen",
    "hard": "Hard",
    "beginner": "Débutant",
    "intermediate": "Intermédiaire",
    "advanced": "Avancé",
    "thinkYouGotIt": "Vous pensez avoir compris ?",
    "testYourUnderstanding": "Testez votre compréhension de ce sujet et voyez si vous maîtrisez les concepts clés que nous avons abordés.",
    "noSourcesAvailable": "Aucune source disponible pour l'instant",
    "noSourcesDescription": "Les sources et les références seront ajoutées au fur et à mesure de la révision et de la vérification du contenu.",
    "understandingSourceAnalysis": "Comprendre l'analyse des sources",
    "biasRatingsMeaning": "Que signifient les notes de partialité ?",
    "credibilityPercentageMeaning": "Que signifie le pourcentage de crédibilité ?",
    "howRatingsDetermined": "Comment ces notes sont-elles déterminées ?",
    "areRatingsPermanent": "Ces évaluations sont-elles permanentes ?",
    "sourceAnalysisImportance": "Pourquoi cela est-il important ?",
    "ratingsAndReviews": "Évaluations et commentaires",
    "communityFeedback": "Retour d'information de la communauté",
    "communityReviews": "Examens de la Communauté",
    "rateThisTopic": "Notez ce sujet",
    "howHelpfulWasThis": "Dans quelle mesure cela a-t-il été utile ?",
    "noRatingsYet": "Pas encore d'évaluation",
    "recentReviews": "Examens récents",
    "noReviewsYet": "Pas encore de commentaires",
    "noReviewsDescription": "Soyez le premier à partager vos réflexions sur ce sujet.",
    "writeFirstReview": "Rédiger le premier commentaire",
    "viewAllReviews": "Voir tous les commentaires",
    "editRating": "Edit Rating",
    "ratingBreakdown": "Ventilation des notes",
    "shareYourThoughts": "Faites-nous part de vos réflexions...",
    "completeQuizToReview": "Compléter le quiz pour réviser",
    "takeQuizToShare": "Répondre à un quiz pour partager",
    "wasThisHelpful": "Cela a-t-il été utile ?",
    "writeAReview": "Rédiger un commentaire",
    "rateAndReview": "Noter et évaluer",
    "selectRating": "Sélectionner la note",
    "submitReview": "Soumettre un avis",
    "shareYourThoughtsDesc": "Partagez vos réflexions sur ce sujet",
    "yourReview": "Votre avis",
    "recently": "Récemment",
    "excellent": "Excellent",
    "veryGood": "Très bon",
    "good": "Bon",
    "fair": "Juste",
    "poor": "Pauvre",
    "checkingProgress": "Vérification de l'état d'avancement",
    "loadingReviews": "Critiques de chargement",
    "submittingReview": "Soumettre une révision",
    "reviewSubmitted": "Examen soumis",
    "thankYouForReview": "Merci pour votre commentaire !",
    "helpful": "Utile",
    "notHelpful": "Pas utile",
    "markAsHelpful": "Marquer comme utile",
    "markAsNotHelpful": "Marquer comme non utile",
    "completeToReview": "Compléter le quiz pour réviser",
    "takeQuizFirst": "Faites d'abord un quiz",
    "finishTopicToReview": "Terminer le sujet à réviser"
  },
  "translation": {
    "selectLanguage": "Sélectionner la langue",
    "languagePreferenceSaved": "Votre choix de langue sera sauvegardé pour vos prochaines visites",
    "translating": "Traduire...",
    "translationComplete": "Traduction terminée",
    "translationError": "Erreur de traduction",
    "helpTranslate": "Aidez-nous à traduire ceci",
    "noTranslationAvailable": "Pas de traduction disponible",
    "loadingTranslations": "Chargement des traductions...",
    "checkingTranslations": "Vérification des traductions existantes...",
    "savingTranslations": "Sauvegarde des traductions...",
    "autoTranslating": "Traduction automatique...",
    "translatingQuestion": "Question de traduction",
    "originalText": "Original",
    "loadingExistingTranslations": "Chargement des traductions existantes...",
    "translateContent": "Traduire le contenu",
    "allQuestionsTranslated": "Toutes les questions sont déjà traduites",
    "translationNeeded": "Besoin de traduction",
    "helpTranslateContent": "Voulez-vous participer à sa traduction ?",
    "translationTest": "Test de traduction",
    "translationTestResult": "Résultat du test de traduction",
    "translationTestFailed": "Échec du test de traduction",
    "initializingTranslationService": "Initialisation du service de traduction...",
    "translated": "Traduit de l'anglais",
    "original": "Original",
    "availableTranslations": "Traductions disponibles",
    "fullyTranslated": "Entièrement traduit",
    "helpTranslateDescription": "Contribuer à rendre CivicSense accessible dans davantage de langues",
    "contributeTranslation": "Aidez-nous à traduire ceci",
    "contributeTitle": "Aidez-nous à traduire CivicSense",
    "contributeMessage": "Souhaitez-vous contribuer à rendre CivicSense accessible à un plus grand nombre de personnes en fournissant des traductions ?",
    "getStarted": "Commencer",
    "thankYou": "Merci de votre attention !",
    "contactInstructions": "Veuillez nous contacter à l'adresse translate@civicsense.com pour commencer à contribuer à la traduction.",
    "dontSeeLanguage": "Vous ne voyez pas votre langue ?",
    "requestLanguage": "Demander une nouvelle langue ou se porter volontaire pour aider à la traduction",
    "analyzingContent": "Analyser le contenu...",
    "translatingToLanguage": "Traduire en {{language}}...",
    "optimizingLayout": "Optimiser la mise en page...",
    "elementsTranslated": "les éléments {{count}} traduits"
  },
  "sources": {
    "analysisOverview": "Aperçu de l'analyse",
    "politicalBias": "Préjugés politiques",
    "factualRating": "Note factuelle",
    "transparency": "Transparence",
    "analysisSummary": "Résumé de l'analyse",
    "topicRelevanceCheck": "Vérification de la pertinence du sujet",
    "validationDetails": "Détails de la validation",
    "strengths": "Points forts",
    "areasForImprovement": "Domaines d'amélioration",
    "redFlags": "Drapeaux rouges",
    "recommendations": "Recommendations",
    "readFullArticle": "Lire l'article complet",
    "loadingAnalysis": "Chargement de l'analyse...",
    "analyzed": "ANALYSE",
    "credibility": "Crédibilité"
  },
  "languages": {
    "english": "Anglais",
    "spanish": "Anglais",
    "chinese": "Chinois",
    "vietnamese": "Vietnamien",
    "arabic": "l'arabe",
    "hindi": "हिन्दी",
    "french": "Français",
    "german": "Allemand",
    "portuguese": "Portugais",
    "russian": "Russie",
    "japanese": "Japonais (langue)",
    "korean": "coréen",
    "italian": "Italien"
  },
  "actions": {
    "save": "Économiser",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "edit": "Editer",
    "share": "Partager",
    "copy": "Copie",
    "download": "Télécharger",
    "upload": "Télécharger",
    "refresh": "Rafraîchir",
    "retry": "Réessayer",
    "tryAgain": "Réessayer",
    "continue": "Continuer",
    "next": "Suivant",
    "previous": "Précédent",
    "finish": "Finition",
    "submit": "Soumettre",
    "confirm": "Confirmer",
    "yes": "Oui",
    "no": "Non",
    "ok": "OK",
    "dismiss": "Rejeter"
  },
  "status": {
    "loading": "Chargement...",
    "saving": "Économiser...",
    "saved": "Sauvegardé",
    "error": "Erreur",
    "success": "Succès",
    "warning": "Avertissement",
    "info": "Info",
    "completed": "Terminé",
    "failed": "Échec",
    "connecting": "Connexion...",
    "connected": "Connecté",
    "disconnected": "Déconnecté",
    "offline": "Hors ligne",
    "online": "En ligne",
    "syncing": "Synchronisation...",
    "synced": "Synchronisé"
  },
  "errors": {
    "networkError": "Erreur de réseau. Veuillez vérifier votre connexion.",
    "serverError": "Erreur de serveur. Veuillez réessayer plus tard.",
    "unknownError": "Une erreur inconnue s'est produite.",
    "notFound": "Contenu non trouvé.",
    "unauthorized": "Vous n'êtes pas autorisé à accéder à ce contenu.",
    "forbidden": "L'accès à ce contenu est interdit.",
    "timeout": "La demande a expiré. Veuillez réessayer.",
    "connectionLost": "Connexion perdue. Veuillez vérifier votre connexion internet.",
    "invalidInput": "Entrée invalide. Veuillez vérifier votre saisie.",
    "requiredField": "Ce champ est obligatoire.",
    "loadingFailed": "Échec du chargement du contenu.",
    "savingFailed": "Échec de l'enregistrement des modifications.",
    "uploadFailed": "Le téléchargement a échoué.",
    "downloadFailed": "Le téléchargement a échoué."
  },
  "time": {
    "now": "maintenant",
    "today": "aujourd'hui",
    "yesterday": "hier",
    "tomorrow": "demain",
    "thisWeek": "cette semaine",
    "lastWeek": "la semaine dernière",
    "thisMonth": "ce mois-ci",
    "lastMonth": "le mois dernier",
    "minutesAgo": "il y a quelques minutes",
    "hoursAgo": "il y a quelques heures",
    "daysAgo": "il y a quelques jours",
    "weeksAgo": "il y a quelques semaines",
    "monthsAgo": "il y a quelques mois"
  },
  "quiz": {
    "question": "Question",
    "questions": "Questions",
    "answer": "Réponse",
    "answers": "Réponses",
    "correct": "Correct",
    "incorrect": "Incorrect",
    "explanation": "Explication",
    "hint": "Hint",
    "score": "Score",
    "results": "Résultats",
    "startQuiz": "Quiz de départ",
    "nextQuestion": "Question suivante",
    "previousQuestion": "Question précédente",
    "finishQuiz": "Quiz final",
    "retakeQuiz": "Quiz de rattrapage",
    "reviewAnswers": "Révision des réponses",
    "timeRemaining": "Temps restant",
    "questionNumber": "Question",
    "totalQuestions": "Total Questions",
    "correctAnswers": "Réponses correctes",
    "incorrectAnswers": "Réponses incorrectes",
    "finalScore": "Score final",
    "complete": "Quiz terminé !",
    "of": "de",
    "title": "Quiz",
    "loadingQuestion": "Question sur le chargement...",
    "unsupportedQuestionType": "Type de question non pris en charge",
    "questionsComplete": "Les questions sont terminées",
    "timeUp": "Le temps est écoulé !",
    "pauseQuiz": "Pause Quiz",
    "resumeQuiz": "Quiz sur les CV",
    "exitQuiz": "Quiz de sortie",
    "saveProgress": "Sauvegarder les progrès",
    "restoreProgress": "Rétablir les progrès",
    "quizMode": "Quiz mode",
    "practiceMode": "Mode pratique",
    "testMode": "Mode test",
    "selectAnswer": "Sélectionner la réponse",
    "submitAnswer": "Submit Answer",
    "showExplanation": "Afficher l'explication",
    "hideExplanation": "Cacher l'explication",
    "yourAnswer": "Votre réponse",
    "correctAnswer": "Réponse correcte",
    "continueToNext": "Continuer au suivant",
    "questionTypes": {
      "multipleChoice": "Choix multiple",
      "trueFalse": "True/False",
      "shortAnswer": "Réponse courte",
      "fillInBlank": "Remplir le vide",
      "matching": "Correspondance",
      "ordering": "Commande",
      "crossword": "Mots croisés"
    },
    "multipleChoice": "Choix multiple",
    "trueFalse": "True/False",
    "shortAnswer": "Réponse courte",
    "fillInBlank": "Remplir le vide",
    "matching": "Correspondance",
    "ordering": "Commande",
    "crossword": "Mots croisés",
    "accuracy": "Précision",
    "timeSpent": "Temps passé",
    "averageTime": "Durée moyenne",
    "breakdown": "Ventilation",
    "recommendations": "Recommendations",
    "questionsAnswered": "Réponses aux questions",
    "questionsSkipped": "Questions ignorées",
    "percentageScore": "Score en pourcentage",
    "passingScore": "Note de passage",
    "passed": "Adopté",
    "failed": "Échec",
    "tryAgain": "Réessayer",
    "viewReview": "Voir la revue",
    "backToTopics": "Retour aux thèmes",
    "difficulty": {
      "easy": "Facile",
      "medium": "Moyen",
      "hard": "Hard"
    }
  },
  "common": {
    "loading": "Chargement...",
    "error": "Erreur",
    "success": "Succès",
    "cancel": "Annuler",
    "confirm": "Confirmer",
    "save": "Économiser",
    "delete": "Supprimer",
    "edit": "Editer",
    "done": "Terminé",
    "close": "Fermer",
    "back": "Retour",
    "next": "Suivant",
    "previous": "Précédent",
    "skip": "Sauter",
    "retry": "Réessayer"
  },
  "gameRoom": {
    "questionsPreview": "Questions",
    "settings": "Paramètres",
    "sources": "Sources d'information",
    "quizSettings": "Paramètres du Quiz",
    "showHints": "Afficher les conseils",
    "getHelpfulClues": "Obtenir des indices utiles en cas de blocage",
    "showExplanations": "Explications de l'émission",
    "learnWhyAnswersCorrect": "Apprendre pourquoi les réponses sont correctes ou incorrectes",
    "hardMode": "Mode difficile",
    "hardModeDescription": "Pas d'indices/explications, 15 par question",
    "timeLimit": "Délai",
    "noTimeLimit": "Pas de limite de temps",
    "estimatedTime": "Temps estimé",
    "questionsAvailable": "questions available",
    "getReady": "Préparez-vous à tester vos connaissances",
    "trustedSources": "Sources de confiance à l'origine de ce contenu",
    "credibilityStandards": "Toutes les sources répondent à nos critères de crédibilité"
  },
  "onboarding": {
    "welcome": "Bienvenue à CivicSense !",
    "welcomeTitle": "Bienvenue à CivicSense",
    "welcomeSubtitle": "Mettons en place des expériences d'apprentissage civique personnalisées",
    "getStarted": "Commencer",
    "skip": "Sauter",
    "exploreOnOwn": "J'explorerai par moi-même",
    "timeToComplete": "5 à 10 minutes de travail",
    "personalizedLearning": "Apprentissage personnalisé",
    "personalizedLearningDesc": "Des quiz personnalisés en fonction de vos centres d'intérêt",
    "communityLearning": "Apprentissage de proximité",
    "communityLearningDesc": "Apprendre avec d'autres personnes de votre communauté",
    "trackProgress": "Suivre les progrès",
    "trackProgressDesc": "Voyez vos connaissances civiques s'enrichir au fil du temps",
    "learnTogether": "Apprendre ensemble",
    "learnTogetherDesc": "Défiez vos amis dans des quiz multijoueurs",
    "earnAchievements": "Obtenir des résultats",
    "earnAchievementsDesc": "Débloquez des badges à mesure que vous maîtrisez les sujets",
    "personalizeExperience": "Personnaliser l'expérience",
    "personalizeExperienceDesc": "Personnalisez votre parcours d'apprentissage",
    "learningStyle": "Style d'apprentissage",
    "learningStyleDesc": "Comment préférez-vous apprendre ?",
    "visual": "Visuel",
    "visualDesc": "Apprendre à l'aide d'images et de diagrammes",
    "reading": "Lecture",
    "readingDesc": "Apprendre par le biais de textes et d'articles",
    "mixed": "Mixte",
    "mixedDesc": "Combiner l'apprentissage visuel et textuel",
    "difficultyLevel": "Niveau de difficulté",
    "difficultyLevelDesc": "Choisissez votre difficulté de départ",
    "beginner": "Débutant",
    "beginnerDesc": "Nouveaux thèmes civiques",
    "intermediate": "Intermédiaire",
    "intermediateDesc": "Quelques connaissances civiques",
    "adaptive": "Adaptatif",
    "adaptiveDesc": "Ajustez la difficulté au fur et à mesure que vous apprenez",
    "location": "Localisation",
    "locationOptional": "Lieu (facultatif)",
    "city": "Ville",
    "state": "État",
    "zipCode": "Code ZIP",
    "dailyReminders": "Rappels quotidiens",
    "dailyRemindersDesc": "Recevoir des notifications sur les nouveaux contenus",
    "whatsNext": "Quelle est la prochaine étape ?",
    "whatsNextDesc": "Commençons votre voyage d'apprentissage civique",
    "completeSetup": "Configuration complète",
    "invalidZipCode": "Code postal invalide",
    "invalidZipCodeDesc": "Veuillez saisir un code postal valide à 5 chiffres",
    "invalidState": "État non valide",
    "invalidStateDesc": "Veuillez saisir un état valide",
    "invalidCity": "Ville invalide",
    "invalidCityDesc": "Veuillez saisir un nom de ville valide",
    "zipCodePlaceholder": "Saisir le code postal",
    "cityPlaceholder": "Saisir la ville",
    "statePlaceholder": "Saisir l'État",
    "stateLocationDesc": "Votre pays nous aide à afficher un contenu local pertinent",
    "cityLocationDesc": "Votre ville nous aide à personnaliser l'information civique",
    "zipCodeLocationDesc": "Votre code postal nous aide à trouver des représentants locaux",
    "categorySelectionTitle": "Choisissez vos centres d'intérêt",
    "categorySelectionDesc": "Sélectionnez les sujets sur lesquels vous souhaitez vous informer",
    "chooseTopics": "Choisir les thèmes",
    "selectInterests": "Sélectionnez vos centres d'intérêt",
    "categoryLoading": "Chargement des catégories...",
    "categoryLoadingError": "Échec du chargement des catégories",
    "questionsAvailable": "questions available",
    "atLeastOneCategory": "Veuillez sélectionner au moins une catégorie",
    "fallbackCategoryDesc": "Explorer une variété de sujets civiques",
    "step": "Étape",
    "choosePlayStyle": "Choisir le style de jeu",
    "setChallenge": "Défi à relever",
    "customize": "Personnaliser",
    "soloChallenge": "Défi solo",
    "soloChallengeDescription": "Testez vos connaissances individuellement",
    "orUseCustomSettings": "Ou utiliser des paramètres personnalisés"
  },
  "multiplayer": {
    "title": "Multijoueurs",
    "connectionError": "Erreur de connexion",
    "failedToJoin": "Échec de la connexion à la salle. Veuillez réessayer.",
    "failedToStart": "Le jeu n'a pas démarré. Veuillez réessayer.",
    "leaveRoomConfirm": "Êtes-vous sûr de vouloir quitter cette pièce ?",
    "inviteMessage": "Rejoignez ma salle de quiz CivicSense ! Code : {{roomCode}}\n\nTéléchargez l'application et entrez ce code pour jouer ensemble.",
    "inviteTitle": "Rejoignez ma salle de quiz CivicSense !",
    "aiPlayer": "Joueur IA",
    "humanPlayer": "Joueur humain",
    "sharingFailed": "Le partage a échoué. Veuillez réessayer.",
    "getReadyToPlay": "Préparez-vous à jouer",
    "startReview": "Début de l'examen",
    "waitingForPlayers": "En attente de joueurs",
    "waitingForHost": "Attente de l'hôte",
    "gameMode": "Mode de jeu",
    "questions": "Questions",
    "features": "Caractéristiques",
    "hints": "Conseils",
    "explanations": "Explications",
    "teamMode": "Mode d'équipe",
    "powerUps": "Les bonus",
    "npcBattle": "Combat de PNJ",
    "testYourKnowledge": "Testez vos connaissances",
    "skillLevel": "Niveau de compétence",
    "roomCode": "Code de la chambre",
    "maxPlayers": "Nombre maximal de joueurs",
    "currentPlayers": "Joueurs actuels",
    "leaderboard": "Tableau de bord",
    "chat": "Chat",
    "settings": "Paramètres",
    "gameStartingSoon": "Le jeu commence bientôt",
    "getReadyFirstQuestion": "Préparez-vous à la première question",
    "battleStarting": "Début de la bataille",
    "firstQuestionLoading": "Première question Chargement",
    "question": "Question",
    "questionNumber": "Question",
    "hint": "Hint",
    "showHint": "Afficher l'indice",
    "submitAnswer": "Submit Answer",
    "explanation": "Explication",
    "shield": "Bouclier",
    "attack": "Attaque",
    "focus": "Focus",
    "correct": "Correct",
    "incorrect": "Incorrect",
    "timeUp": "Le temps est écoulé !",
    "finalScore": "Score final",
    "gameComplete": "Jeu terminé",
    "greatJobLearning": "Bon travail d'apprentissage !",
    "shareResults": "Partager les résultats",
    "continue": "Continuer",
    "victory": "Victoire !",
    "goodTry": "Bien essayé !",
    "correctAnswers": "Réponses correctes",
    "accuracy": "Précision",
    "playAgain": "Jouer à nouveau",
    "exit": "Sortie",
    "ready": "Prêt",
    "notReady": "Pas prêt",
    "thinking": "Réflexion",
    "answered": "Répondu",
    "roomChat": "Salle de discussion",
    "players": "Joueurs",
    "typeMessage": "Type Message",
    "enterToSend": "Entrer pour envoyer",
    "beRespectful": "Soyez respectueux",
    "playerJoined": "Joueur inscrit",
    "playerLeft": "Joueur gauche",
    "gameStarting": "Début du jeu",
    "welcomeToQuiz": "Bienvenue au quiz",
    "allowNewPlayers": "Autoriser les nouveaux joueurs",
    "allowNewPlayersDesc": "Permettre à de nouveaux joueurs de rejoindre le jeu",
    "enableBoosts": "Activer les boosters",
    "enableBoostsDesc": "Activer les bonus pour les joueurs",
    "showHints": "Afficher les conseils",
    "showHintsDesc": "Montrer des indices aux joueurs",
    "autoAdvance": "Auto Advance",
    "autoAdvanceDesc": "Avancer automatiquement les questions",
    "realTimeScores": "Scores en temps réel",
    "realTimeScoresDesc": "Afficher les scores en temps réel",
    "enableChat": "Activer le chat",
    "enableChatDesc": "Activer le chat pour les joueurs",
    "connectionLost": "Perte de connexion",
    "failedToSubmitAnswer": "La réponse n'a pas été soumise",
    "networkError": "Erreur de réseau",
    "ai": "AI",
    "host": "Hôte",
    "titleDescription": "Description",
    "liveGameScreen": "Jeu en direct"
  },
  "analytics": {
    "loadingInsights": "Chargement des informations...",
    "couldNotLoadInsights": "Impossible de charger les connaissances sur l'apprentissage. Veuillez réessayer.",
    "couldNotRefreshInsights": "Impossible d'actualiser les informations. Veuillez réessayer.",
    "excellentPerformance": "Excellente performance ! Voir les prochaines étapes personnalisées.",
    "goodProgress": "De bons progrès ! Découvrez les points à améliorer.",
    "keepLearning": "Continuez à apprendre ! Obtenez des conseils d'étude personnalisés.",
    "needHelp": "Vous avez des difficultés ? Obtenez une aide personnalisée."
  },
  "news": {
    "dailyNews": "Actualités quotidiennes",
    "latestNews": "Dernières nouvelles",
    "articles": "articles",
    "fetchingFrom": "Recherche dans AP, Reuters, NPR, BBC, Politico...",
    "noValidArticles": "Aucun article valide n'a été trouvé après le filtrage",
    "failedToLoad": "Échec du chargement de l'actualité",
    "newsAPI": "Échec de l'API des actualités",
    "unknownError": "Erreur inconnue",
    "refreshNews": "Nouvelles de Refresh",
    "updating": "Mise à jour...",
    "today": "Aujourd'hui",
    "yesterday": "Hier",
    "breakingNews": "Dernières nouvelles",
    "newsUpdates": "Actualités",
    "readMore": "Lire la suite",
    "readFull": "Lire l'article complet",
    "source": "Source",
    "publishedBy": "Publié par",
    "lastUpdated": "Dernière mise à jour",
    "originalSource": "Source originale",
    "previousArticle": "Article précédent",
    "nextArticle": "Article suivant",
    "backToNews": "Retour aux actualités",
    "filterByCategory": "Filtrer par catégorie",
    "sortBy": "Trier par",
    "newest": "Le plus récent",
    "oldest": "Le plus ancien",
    "mostRelevant": "Le plus pertinent",
    "noArticlesFound": "Aucun article trouvé",
    "loadingFailed": "Échec du chargement des articles de presse",
    "tryAgainLater": "Veuillez réessayer plus tard",
    "shareArticle": "Partager l'article",
    "copyLink": "Copier le lien",
    "linkCopied": "Lien copié dans le presse-papiers",
    "savedToDb": "enregistré dans la base de données",
    "ago": "il y a"
  },
  "collections": {
    "takeAction": "Agir",
    "planned": "prévu",
    "completed": "achevé",
    "immediateActions": "Actions immédiates",
    "immediateActionsDesc": "Il s'agit de mesures spécifiques que vous pouvez prendre dès maintenant pour appliquer ce que vous avez appris.",
    "civicEngagementOpportunities": "Possibilités d'engagement civique",
    "civicEngagementDesc": "Entrez en contact avec votre communauté et ayez un impact plus large grâce à ces opportunités.",
    "markAsCompleted": "Marquer comme terminé",
    "yourActionPlan": "Votre plan d'action",
    "youvePlannedActions": "Vous avez planifié {{count}} action{{plural}}",
    "andCompleted": " et complété {{count}}",
    "greatJobTakingAction": "Bravo pour votre action en faveur de l'apprentissage civique ! 🎉",
    "keepGoing": "Continuez ! C'est en agissant que nous renforçons la démocratie.",
    "readyToTakeAction": "Prêt à passer à l'action ?",
    "checkOffActions": "Cochez les actions que vous comptez entreprendre. Chaque petit pas rend la démocratie plus forte.",
    "outstanding": "Remarquable !",
    "completedAllActions": "Vous avez mené à bien toutes les actions proposées. Vous faites une réelle différence dans votre communauté !",
    "quickCheck": "Vérification rapide",
    "complete": "Compléter",
    "submitAnswer": "Submit Answer",
    "correct": "C'est exact !",
    "notQuiteRight": "Not quite right",
    "showHint": "Afficher l'indice",
    "hideHint": "Cacher l'Indien",
    "selectAnAnswer": "Sélectionnez une réponse",
    "answerSelected": "Réponse sélectionnée",
    "trueOrFalse": "Vrai ou faux ?",
    "selectTrueFalse": "Sélectionnez Vrai ou Faux",
    "yourResponse": "Votre réponse",
    "enterYourAnswer": "Saisissez votre réponse...",
    "submitResponse": "Soumettre une réponse",
    "responseRecorded": "Réponse enregistrée",
    "thankYouForInput": "Nous vous remercions pour votre contribution. Votre réponse a été enregistrée.",
    "enterYourResponse": "Saisissez votre réponse",
    "charactersCount": "caractères {{count}} __PLACEHOLDER_0__ __PLACEHOLDER_0___",
    "rankingExercise": "Exercice de classement",
    "dragToReorder": "Faites glisser les éléments pour les réorganiser du plus important au moins important :",
    "rankingComplete": "Classement complet",
    "dragToReorderItems": "Faire glisser pour réorganiser les éléments",
    "rankingExplanation": "Explication du classement",
    "interactiveTimeline": "Chronologie interactive",
    "clickEachEvent": "Cliquez sur chaque événement pour le découvrir ({actuel}/{total})",
    "exploreAllEvents": "Explorer tous les événements",
    "reflection": "Réflexion",
    "reflectionPrompts": "Pistes de réflexion",
    "shareYourThoughts": "Faites-nous part de vos réflexions...",
    "saveReflection": "Sauvegarder la réflexion",
    "actionChecklist": "Liste de contrôle des actions",
    "actionsCompleted": "{réalisé} sur {total} actions réalisées",
    "primaryAction": "Action primaire",
    "bonusActions": "Actions bonus (facultatif)",
    "helpfulResources": "Ressources utiles",
    "markAsComplete": "Marquer comme complet",
    "actionComplete": "Action terminée",
    "takeActionStatus": "Agir",
    "pending": "En attente",
    "contactRepresentatives": "Contactez vos représentants",
    "contactsReached": "{contactés} de {total} contacts atteints",
    "whoToContact": "Qui contacter ?",
    "messageTemplates": "Modèles de messages",
    "sendWithTemplate": "Envoyer avec le modèle",
    "visitWebsite": "Visiter le site web →",
    "alreadyContacted": "Déjà contacté",
    "markAsContacted": "Marquer comme contacté",
    "quickPoll": "Sondage rapide",
    "castVote": "Vote par correspondance",
    "thanksForVoting": "Merci de voter !",
    "results": "Résultats :",
    "votes": "votes",
    "surveyTitle": "Enquête",
    "questionProgress": "Question {actuelle} de {total}",
    "simulationResults": "Résultats de la simulation",
    "yourAnswer": "Votre réponse...",
    "previous": "Précédent",
    "next": "Suivant",
    "completeSurvey": "Enquête complète",
    "externalSurveyDesc": "Cette enquête est hébergée en externe. Cliquez sur le lien ci-dessous pour y participer.",
    "openSurvey": "Enquête ouverte",
    "opinionScale": "Échelle d'opinion",
    "moveSlider": "Déplacez le curseur pour indiquer votre niveau d'accord",
    "submitOpinion": "Soumettre un avis",
    "thanksForOpinion": "Merci de nous faire part de votre avis !",
    "stronglyDisagree": "Pas du tout d'accord",
    "disagree": "Pas d'accord",
    "neutral": "Neutre",
    "agree": "Accorder",
    "stronglyAgree": "Tout à fait d'accord",
    "policySimulation": "Simulation de politique",
    "scenario": "Scénario",
    "adjustVariables": "Ajuster les variables",
    "runSimulation": "Exécuter la simulation",
    "rolePlayingExercise": "Exercice de jeu de rôle",
    "chooseYourRole": "Choisissez votre rôle",
    "objectives": "Objectifs :",
    "whatActionTake": "Quelle action entreprenez-vous lors de ce tour ?",
    "negotiateStakeholders": "Négocier avec les autres parties prenantes",
    "gatherMoreInfo": "Recueillir plus d'informations",
    "rolePlayComplete": "Jeu de rôle terminé !",
    "yourDecisions": "Vos décisions",
    "decisionPath": "Voie de décision",
    "decisionPoint": "Point de décision",
    "chooseResponse": "Choisissez votre réponse :",
    "finalOutcome": "Résultat final",
    "reflectionNote": "Examinez comment des choix différents auraient pu conduire à des résultats différents. Les décisions politiques réelles ont souvent des conséquences complexes qui ne sont pas immédiatement apparentes.",
    "tryDifferentPath": "Essayer une autre voie",
    "yourPath": "Votre chemin :",
    "compareAndContrast": "Comparaison et contraste",
    "continueLearning": "Poursuivre l'apprentissage",
    "viewAllCards": "Voir toutes les cartes",
    "nextCard": "Carte suivante",
    "previousCard": "Précédent",
    "exploreImage": "Explorer l'image",
    "dragAndDrop": "Glisser-déposer",
    "availableItems": "Articles disponibles",
    "interactiveMap": "Carte interactive",
    "checkAnswers": "Vérifier les réponses",
    "allItemsAssigned": "Tous les éléments attribués",
    "assigned": "attribuée",
    "adjustParameters": "Ajuster les paramètres",
    "viewResults": "Voir les résultats",
    "resetSimulation": "Réinitialisation de la simulation",
    "fillInTheBlanks": "Remplir les blancs",
    "matchingPairs": "Paires assorties",
    "categorizeItems": "Catégoriser les articles",
    "progressUpdate": "État d'avancement des travaux",
    "wellDone": "Bravo !",
    "goodEffort": "Bel effort !",
    "keepTrying": "Continuez à essayer !",
    "perfect": "Parfait !",
    "almostThere": "Nous y sommes presque !"
  },
  "accessibility": {
    "skipToContent": "Skip to content",
    "mainNavigation": "Navigation principale",
    "userMenu": "Menu utilisateur",
    "darkModeToggle": "Basculer en mode sombre",
    "languageSelector": "Sélection de la langue",
    "closeDialog": "Fermer le dialogue",
    "openMenu": "Ouvrir le menu",
    "closeMenu": "Fermer le menu",
    "loadingContent": "Chargement du contenu",
    "expandSection": "Agrandir la section",
    "collapseSection": "Réduire la section",
    "playAudio": "Écouter l'audio",
    "pauseAudio": "Pause audio",
    "stopAudio": "Arrêter l'audio",
    "increaseSpeed": "Augmenter la vitesse",
    "decreaseSpeed": "Diminuer la vitesse",
    "goBack": "Retourner",
    "openLink": "Ouvrir le lien",
    "bookmark": "Ajouter ce sujet à vos favoris",
    "removeBookmark": "Supprimer un signet"
  },
  "settings": {
    "title": "Paramètres",
    "account": "Compte",
    "preferences": "Préférences",
    "notifications": "Notifications",
    "privacy": "Vie privée",
    "accessibility": "Accessibilité",
    "language": "Langue",
    "theme": "Thème",
    "themes": {
      "light": "Lumière",
      "dark": "Sombre",
      "system": "Système"
    },
    "email": "Courriel",
    "password": "Mot de passe",
    "changePassword": "Modifier le mot de passe",
    "deleteAccount": "Supprimer le compte",
    "exportData": "Export Data",
    "saveChanges": "Enregistrer les modifications",
    "saved": "Paramètres sauvegardés",
    "emailNotifications": "Notifications par courrier électronique",
    "pushNotifications": "Notifications push",
    "weeklyDigest": "Résumé de la semaine",
    "achievementAlerts": "Alertes sur les réalisations",
    "soundEffects": "Effets sonores",
    "animations": "Animations",
    "highContrast": "Contraste élevé",
    "largeText": "Texte large",
    "reducedMotion": "Mouvement réduit",
    "keyboardShortcuts": "Raccourcis clavier",
    "timezone": "Fuseau horaire",
    "dateFormat": "Format de la date",
    "giftCredits": "Crédits cadeaux",
    "premium": "Prime",
    "subscription": "Abonnement",
    "features": "Caractéristiques",
    "upgrade": "Mise à niveau",
    "manage": "Gérer",
    "cancel": "Annuler",
    "signOut": "S'inscrire",
    "accountData": "Données du compte",
    "displayName": "Nom d'affichage",
    "currentPassword": "Mot de passe actuel",
    "newPassword": "Nouveau mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "updateAccount": "Mise à jour du compte",
    "pleaseSignIn": "Veuillez vous connecter pour accéder aux paramètres",
    "signInToAccess": "Veuillez vous connecter pour accéder aux paramètres",
    "editProfile": "Edit Profile",
    "fullName": "Nom complet",
    "fullNameRequired": "Le nom complet est requis",
    "bio": "Bio",
    "location": "Localisation",
    "website": "Site web",
    "country": "Pays",
    "stateProvince": "État/Province",
    "city": "Ville",
    "profileUpdated": "Profil mis à jour ! ✅",
    "profileUpdatedMessage": "Vos modifications ont été enregistrées avec succès.",
    "great": "Excellent !",
    "discardChanges": "Changements dans les rejets ?",
    "discardChangesMessage": "Vous avez des modifications non enregistrées. Êtes-vous sûr de vouloir les supprimer ?",
    "keepEditing": "Continuer à éditer",
    "discard": "Rejeter",
    "permissionRequired": "Autorisation requise",
    "photoLibraryPermission": "Veuillez autoriser l'accès à votre bibliothèque de photos pour modifier votre avatar.",
    "uploadFailed": "Le téléchargement de l'avatar a échoué. Veuillez réessayer.",
    "autoTranslateContent": "Traduire automatiquement le contenu",
    "autoTranslateContentDesc": "Traduire automatiquement les questions de quiz et les leçons",
    "preserveCivicTerms": "Préserver les termes civiques",
    "preserveCivicTermsDesc": "Veiller à l'exactitude des termes civiques importants dans les traductions",
    "clearTranslationCache": "Effacer le cache de traduction",
    "clearTranslationCacheDesc": "Réinitialiser les traductions enregistrées pour obtenir un nouveau contenu",
    "translationCacheCleared": "Le cache de traduction a été effacé avec succès",
    "translationCacheClearError": "Échec de l'effacement du cache de traduction"
  },
  "survey": {
    "question": "Question",
    "questions": "Questions",
    "required": "Exigée",
    "optional": "En option",
    "progress": "Progrès",
    "complete": "Compléter",
    "submit": "Soumettre",
    "next": "Suivant",
    "previous": "Précédent",
    "skip": "Sauter",
    "save": "Économiser",
    "saveProgress": "Sauvegarder les progrès",
    "loading": "Chargement...",
    "error": "Erreur",
    "success": "Succès",
    "pleaseSelectOption": "Veuillez sélectionner une option",
    "pleaseProvideAnswer": "Veuillez fournir une réponse",
    "invalidEmail": "Veuillez saisir une adresse électronique valide",
    "invalidPhone": "Veuillez saisir un numéro de téléphone valide",
    "tooManySelections": "Trop de sélections",
    "maxSelections": "Sélections maximales atteintes",
    "selectAtLeast": "Veuillez sélectionner au moins",
    "selectAtMost": "Veuillez sélectionner au maximum",
    "charactersRemaining": "caractères restants",
    "wordLimit": "Limite de mots dépassée",
    "fileUpload": "Téléchargement de fichiers",
    "chooseFile": "Choisir un fichier",
    "removeFile": "Supprimer le fichier",
    "uploadError": "Échec du téléchargement",
    "stronglyDisagree": "Pas du tout d'accord",
    "disagree": "Pas d'accord",
    "neutral": "Neutre",
    "agree": "Accorder",
    "stronglyAgree": "Tout à fait d'accord",
    "pleaseSpecify": "Veuillez préciser...",
    "other": "Autres",
    "none": "Aucun",
    "all": "Tous",
    "completed": "Terminé",
    "thankYou": "Merci de votre attention !",
    "submissionComplete": "Votre demande a été complétée",
    "viewResults": "Voir les résultats",
    "retake": "Reprise",
    "share": "Partager"
  },
  "audio": {
    "play": "Jouer",
    "pause": "Pause",
    "stop": "Arrêter",
    "resume": "Curriculum vitae",
    "restart": "Redémarrage",
    "mute": "Mute",
    "unmute": "Mauvaise humeur",
    "volume": "Volume",
    "speed": "Vitesse",
    "voice": "Voix",
    "settings": "Paramètres",
    "audioControls": "Commandes audio",
    "voiceSettings": "Paramètres vocaux",
    "quality": "Qualité",
    "high": "Haut",
    "medium": "Moyen",
    "low": "Faible",
    "autoPlay": "Lecture automatique",
    "loop": "Boucle",
    "highlighting": "Mise en évidence des mots",
    "cloudTTS": "Cloud TTS",
    "browserTTS": "Navigateur TTS",
    "language": "Langue",
    "male": "Homme",
    "female": "Femme",
    "neutral": "Neutre",
    "loading": "Chargement...",
    "error": "Erreur audio",
    "notSupported": "L'audio n'est pas pris en charge",
    "recovery": "Récupérer l'audio",
    "testAudio": "Test Audio",
    "readPage": "Lire la page",
    "readSelection": "Lire la sélection",
    "keyboardShortcuts": "Raccourcis clavier",
    "diagnostics": "Diagnostics",
    "usage": "Utilisation",
    "charactersUsed": "Personnages utilisés",
    "estimatedCost": "Coût estimé",
    "voiceCount": "Nombre de voix",
    "speaking": "Parler",
    "pending": "En attente",
    "paused": "En pause",
    "lastUpdate": "Dernière mise à jour"
  },
  "profileScreenTitle": "Mon profil",
  "loadingProfile": "Chargement de votre profil...",
  "redirectingToLogin": "Redirection vers le login...",
  "leaderboard": {
    "title": "Tableau de bord",
    "loadingLeaderboard": "Chargement du classement...",
    "yourRanking": "Votre classement",
    "currentRank": "Rang actuel",
    "topPercentile": "Premier percentile",
    "totalUsers": "Total des utilisateurs",
    "today": "Aujourd'hui",
    "thisWeek": "Cette semaine",
    "thisMonth": "Ce mois-ci",
    "allTime": "Tout le temps",
    "score": "Score",
    "xp": "XP",
    "streak": "Trait",
    "quizzes": "quiz",
    "achievements": "réalisations",
    "you": "(Vous)",
    "takeQuizToClimb": "Participez à un quiz pour grimper !",
    "new": "NOUVEAU"
  },
  "search": {
    "title": "Recherche",
    "placeholder": "Recherche de collections et de sujets...",
    "clearHistory": "Effacer l'historique des recherches",
    "analytics": "recherches {{count}} - Articles consultés {{viewed}}",
    "streak": "la journée de l'homme de la rue",
    "loadingData": "Chargement des données de recherche...",
    "searching": "Recherche de collections et de sujets...",
    "keepTyping": "Continuez à taper...",
    "minCharacters": "Saisissez au moins 2 caractères pour commencer la recherche",
    "filterAll": "Tous",
    "filterCollections": "Collections",
    "filterTopics": "Thèmes",
    "noResults": "Aucun résultat trouvé",
    "noResultsHint": "Essayez de chercher d'autres mots-clés comme \"Constitution\", \"Elections\" ou \"Cour suprême\"",
    "continueLearning": "Poursuivre l'apprentissage",
    "pickUpWhereLeft": "Reprendre là où on s'est arrêté",
    "recommended": "Recommandé",
    "recentSearches": "Recherches récentes",
    "clearAll": "Tout effacer",
    "popularTopics": "Sujets populaires",
    "tapToSearch": "Touchez pour effectuer une recherche rapide",
    "searchTips": "Conseils de recherche",
    "tip1": "Essayez des sujets spécifiques tels que le \"premier amendement\" ou le \"collège électoral\"",
    "tip2": "Les éléments que vous avez consultés récemment apparaissent en premier dans les résultats",
    "tip3": "L'historique de vos recherches nous aide à vous proposer de meilleures recommandations",
    "collection": "Collection",
    "topic": "Sujet",
    "questionCount": "{{count}} questions",
    "recent": "Récents"
  },
  "profile": {
    "title": "Mon profil",
    "loadingProfile": "Chargement de votre profil...",
    "redirectingToLogin": "Redirection vers le login...",
    "yourProgress": "Vos progrès",
    "calendarIntegration": "Intégration du calendrier",
    "googleCalendarSync": "Google Calendar Sync",
    "googleCalendarSyncDesc": "Synchronisez votre programme d'études avec Google Calendar",
    "dailyQuizReminders": "Rappels de l'interrogation quotidienne",
    "dailyQuizRemindersDesc": "Se faire rappeler les quiz quotidiens",
    "smartScheduling": "Programmation intelligente",
    "smartSchedulingDesc": "Heures d'étude optimales pilotées par l'IA",
    "learningPodSessions": "Sessions d'apprentissage en pods",
    "learningPodSessionsDesc": "Rappels pour les sessions d'étude en groupe",
    "lastSynced": "Dernière synchronisation",
    "smartStudyRecommendations": "Recommandations de l'étude Smart",
    "scheduleThisTime": "Programmer cette période",
    "learningPods": "Pods d'apprentissage",
    "constitutionalLawStudyGroup": "Groupe d'étude sur le droit constitutionnel",
    "membersOnline": "membres - {{online}} en ligne maintenant",
    "billOfRightsReviewSession": "Session de révision de la déclaration des droits",
    "managePods": "Manage Pods",
    "editProfile": "Edit Profile",
    "updateYourInformation": "Mise à jour de vos informations",
    "preferences": "Préférences",
    "learningAndNotifications": "Apprentissage et notifications",
    "exportLearningProgress": "Progrès de l'apprentissage à l'exportation",
    "howWouldYouLikeToShare": "Comment souhaitez-vous partager vos progrès ?",
    "exportAsPDF": "Exporter en PDF",
    "shareWithPod": "Partager avec Pod",
    "generateReport": "Générer votre rapport d'analyse CivicSense",
    "shareReport": "Rapport de partage",
    "exportFailed": "Échec de l'exportation",
    "exportError": "Échec de la génération de votre rapport d'analyse de l'apprentissage. Veuillez réessayer.",
    "updateProfilePhoto": "Mise à jour de la photo de profil",
    "choosePhotoMethod": "Choisissez la manière dont vous souhaitez ajouter votre photo",
    "camera": "Appareil photo",
    "photoLibrary": "Photothèque",
    "profilePhotoUpdated": "La photo de profil a été mise à jour avec succès !",
    "uploadPhotoFailed": "Échec du téléchargement de la photo de profil",
    "profileCompletion": "Profil {{percent}}% terminé",
    "profileCompletePercent": "Profil {{percent}}% terminé",
    "quizzes": "Quiz",
    "avgScore": "Score moyen",
    "dayStreak": "Traînée de jours",
    "studyTime": "Temps d'étude",
    "achievements": "Réalisations",
    "viewDetailedStats": "Voir les statistiques détaillées",
    "connectedViaGoogle": "Connecté via Google",
    "appVersion": "CivicSense v1.0.0 - Fabriqué avec ❤️ pour la démocratie",
    "madeWithLoveForDemocracy": "Fabriqué avec ❤️ pour la démocratie"
  },
  "saved": {
    "title": "Sauvegardé",
    "subtitle": "Vos signets et votre progression",
    "loadingSavedContent": "Chargement du contenu sauvegardé...",
    "collections": "Collections",
    "createCollection": "Créer",
    "organizeYourLearning": "Organisez votre apprentissage",
    "organizeYourLearningDesc": "Créez des collections pour organiser votre contenu sauvegardé dans des dossiers thématiques afin de faciliter l'étude.",
    "lessons": "Enseignements tirés",
    "lessonsDesc": "Cours en plusieurs étapes de CivicSense",
    "myCollections": "Mes collections",
    "myCollectionsDesc": "Vos dossiers de contenu organisés",
    "createYourFirstCollection": "Créez votre première collection pour organiser votre contenu sauvegardé",
    "filterContent": "Contenu du filtre",
    "allContent": "Tous",
    "topics": "Thèmes",
    "quizResults": "Résultats du Quiz",
    "customQuizzes": "Quiz personnalisés",
    "bookmarks": "Signets",
    "noSavedLessons": "Pas de leçons sauvegardées",
    "noSavedTopics": "Pas de sujets sauvegardés",
    "noQuizResults": "Pas de résultats au quiz",
    "noBookmarks": "Pas de signets",
    "noSavedItems": "Pas d'éléments sauvegardés",
    "exploreContent": "Explorer le contenu",
    "selectItems": "Sélectionner les éléments",
    "itemsSelected": "pLACEHOLDER_0__ item{{plural}} sélectionné",
    "selectItemsToOrganize": "Sélectionner les éléments à organiser",
    "organizeSelectedItems": "Organiser les éléments sélectionnés",
    "moveToCollection": "Déplacer vers la collection",
    "removeItem": "Supprimer l'article",
    "removeItemConfirm": "Êtes-vous sûr de vouloir supprimer cet élément sauvegardé ?",
    "highlightedText": "Texte surligné",
    "textSnippet": "Extrait de texte",
    "customQuiz": "Quiz personnalisé",
    "continueYourCivicsAssessment": "Poursuivre l'évaluation de l'éducation civique",
    "questionsCompleted": "le {{completed}} de {{total}} a répondu aux questions",
    "started": "Démarré {{date}}",
    "scoreLabel": "Score",
    "xpEarned": "+{{xp}} XP",
    "questions": "Questions",
    "draft": "PROJET",
    "published": "PUBLIÉ",
    "savedRecently": "Sauvegardé {{time}}",
    "savedTime": "Sauvegardé il y a {{time}}",
    "keepGoing": "Continuez ! 🎯",
    "nothingNewToday": "Rien de nouveau aujourd'hui ? C'est le moment idéal pour explorer ! 📚",
    "nothingNewTodayDesc": "Essayez de naviguer vers d'autres dates en utilisant les flèches ci-dessus, ou explorez les options d'apprentissage ci-dessous.",
    "currentEvents": "Actualité",
    "currentEventsDesc": "Touchez n'importe quelle histoire pour créer un quiz sur ce sujet",
    "findingCurrentEvents": "Trouver des événements d'actualité pour {{date}}...",
    "continueWhereLeftOff": "Poursuivre là où vous vous êtes arrêté",
    "orExploreMore": "Ou en savoir plus",
    "continueLearning": "Poursuivre l'apprentissage",
    "exploreQuizTopics": "Explorer les thèmes du quiz",
    "exploreQuizTopicsDesc": "Découvrez les quiz sur le gouvernement, les droits et la participation civique",
    "takeCivicsAssessment": "Passer l'évaluation de l'éducation civique",
    "takeCivicsAssessmentDesc": "Testez vos connaissances sur le gouvernement américain et la démocratie",
    "reviewSavedContent": "Révision du contenu sauvegardé",
    "reviewSavedContentDesc": "Poursuivre l'apprentissage à partir des sujets que vous avez mis en signet",
    "createCustomContent": "Créer un contenu personnalisé",
    "createCustomContentDesc": "Créez vos propres sujets et questions",
    "pro": "PRO"
  },
  "learn": {
    "title": "Apprendre",
    "loadingQuizCollections": "Chargement des collections de quiz...",
    "usingOfflineData": "Utilisation des données du quiz hors ligne - réseau indisponible",
    "featuredLessons": "Leçons en vedette",
    "featuredLessonsDesc": "Collections de leçons sur des sujets d'actualité",
    "allCollections": "Toutes les collections",
    "allCollectionsDesc": "Test complet de connaissances civiques",
    "collections": "collections {{count}}",
    "topics": "Thèmes",
    "topicsDesc": "Explorer des thèmes civiques individuels à l'aide de questions ciblées",
    "noQuizCollections": "No quiz collections available",
    "noQuizCollectionsOffline": "Vérifiez votre connexion internet et réessayez",
    "noQuizCollectionsOnline": "Les nouvelles collections de quiz apparaîtront ici dès qu'elles seront disponibles",
    "quizDataSource": "Source des données du quiz : {{source}}",
    "liveAPI": "API en direct",
    "offlineCache": "Cache hors ligne",
    "showingRealTimeData": "Affichage en temps réel des collections de quiz provenant du serveur",
    "usingCachedData": "Utilisation de données de quiz mises en cache - certains contenus peuvent être obsolètes",
    "new": "Nouveau",
    "featured": "En vedette",
    "estimatedTime": "{{time}} min",
    "completionRate": "{{rate}}% d'achèvement",
    "completion": "achèvement",
    "continue": "Continuer",
    "start": "Démarrage",
    "available": "Disponible",
    "difficulty": "Difficulté",
    "searchTopics": "Thèmes de recherche"
  },
  "home": {
    "welcomeBack": "Bienvenue, {{name}}",
    "welcome": "CivicSense",
    "citizen": "Citoyen",
    "loadingYourCivicJourney": "Chargement de votre voyage civique...",
    "loadingContent": "Chargement du contenu...",
    "today": "Aujourd'hui",
    "dailyChallenge": "Défi quotidien ({{completed}} de {{total}})",
    "questionsOf": "{{completed}} de {{total}}",
    "dayStreak": "{{count}} day{{plural}}",
    "days": "jours",
    "day": "jour",
    "loadingDate": "Chargement de {{date}}",
    "noFeaturedToday": "Pas de thèmes à l'honneur aujourd'hui",
    "noFeaturedTodayDesc": "Revenez plus tard pour les dernières nouvelles et le contenu en vedette",
    "checkBackLater": "Revenez plus tard pour les dernières nouvelles et le contenu en vedette",
    "keepGoingTarget": "Continuez ! 🎯",
    "navigateToOtherDates": "Essayez de naviguer vers d'autres dates en utilisant les flèches ci-dessus, ou explorez les options d'apprentissage ci-dessous.",
    "exploreMoreOptions": "explorer ces options d'apprentissage ci-dessous",
    "todaysCurrentEvents": "L'actualité d'aujourd'hui",
    "currentEventsForDate": "événements d'actualité",
    "tapAnyStoryToCreate": "Touchez n'importe quelle histoire pour créer un quiz sur ce sujet",
    "findingCurrentEventsFor": "Trouver des événements d'actualité pour {{date}}...",
    "exploreQuizTopics": "Explorer les thèmes du quiz",
    "exploreQuizTopicsDesc": "Découvrez les quiz sur le gouvernement, les droits et la participation civique",
    "takeCivicsAssessment": "Passer l'évaluation de l'éducation civique",
    "takeCivicsAssessmentDesc": "Testez vos connaissances sur le gouvernement et la démocratie américains",
    "reviewSavedContent": "Révision du contenu sauvegardé",
    "reviewSavedContentDesc": "Poursuivre l'apprentissage à partir des sujets que vous avez mis en signet",
    "createCustomContent": "Créer un contenu personnalisé",
    "createCustomContentDesc": "Créez vos propres sujets et questions",
    "designYourOwnTopics": "Créez vos propres sujets et questions",
    "proFeature": "PRO",
    "startReview": "Début de l'examen",
    "readMore": "Lire la suite",
    "signUpToSaveProgress": "Inscrivez-vous pour enregistrer vos progrès et débloquer des réalisations",
    "yourProgressMatters": "Vos progrès sont importants",
    "preserveYourLearning": "Préservez votre parcours d'apprentissage et continuez à développer vos connaissances civiques",
    "getStarted": "Commencer",
    "nothingNewToday": "Rien de nouveau aujourd'hui ? C'est le moment idéal pour explorer ! 📚",
    "keepGoing": "Continuez ! 🎯"
  }
};

export default uiStringsFR;
