/**
 * Database Types for CivicSense Mobile
 * 
 * This file re-exports database types from the main app to ensure
 * consistency between web and mobile applications.
 */

// Re-export all core types from the main app
export type { 
  Database,
  Tables,
  TablesInsert,
  TablesUpdate
} from '../../../lib/database.types'

// Import types for internal use
import type { Tables, TablesInsert, TablesUpdate } from '../../../lib/database.types'

// For convenience, also re-export the specific table types that are commonly used in mobile
// These match the naming convention generated by our sync script

// Assessment types
export type DbAssessmentQuestions = Tables<'user_assessment_questions'>
export type DbAssessmentQuestionsInsert = TablesInsert<'user_assessment_questions'>
export type DbAssessmentQuestionsUpdate = TablesUpdate<'user_assessment_questions'>

export type DbAssessmentAnalytics = Tables<'assessment_analytics'>
export type DbUserAssessments = Tables<'user_assessments'>
export type DbUserOnboardingState = Tables<'user_onboarding_state'>

// Core quiz types
export type DbQuestionTopics = Tables<'question_topics'>
export type DbQuestions = Tables<'questions'>
export type DbUserQuizAttempts = Tables<'user_quiz_attempts'>
export type DbUserProgress = Tables<'user_progress'>
export type DbUserQuestionResponses = Tables<'user_question_responses'>
export type DbProfiles = Tables<'profiles'>
export type DbCategories = Tables<'categories'>

// Multiplayer types
export type DbMultiplayerRooms = Tables<'multiplayer_rooms'>
export type DbMultiplayerRoomPlayers = Tables<'multiplayer_room_players'>
export type DbMultiplayerQuizAttempts = Tables<'multiplayer_quiz_attempts'>
export type DbMultiplayerQuestionResponses = Tables<'multiplayer_question_responses'>
export type DbMultiplayerGameEvents = Tables<'multiplayer_game_events'>
export type DbMultiplayerChatMessages = Tables<'multiplayer_chat_messages'>

// Skills types
export type DbSkills = Tables<'skills'>
export type DbUserSkillProgress = Tables<'user_skill_progress'>
export type DbUserSkillPreferences = Tables<'user_skill_preferences'>

// Guest access types
export type DbGuestUsageTracking = Tables<'guest_usage_tracking'>
export type DbGuestCivicsTestResults = Tables<'guest_civics_test_results'>

// Survey types
export type DbSurveys = Tables<'surveys'>
export type DbSurveyQuestions = Tables<'survey_questions'>
export type DbSurveyResponses = Tables<'survey_responses'>
export type DbSurveyAnswers = Tables<'survey_answers'>

// Insert types for commonly used tables
export type DbUserQuizAttemptsInsert = TablesInsert<'user_quiz_attempts'>
export type DbUserProgressInsert = TablesInsert<'user_progress'>
export type DbUserQuestionResponsesInsert = TablesInsert<'user_question_responses'>
export type DbMultiplayerRoomsInsert = TablesInsert<'multiplayer_rooms'>
export type DbMultiplayerRoomPlayersInsert = TablesInsert<'multiplayer_room_players'>
export type DbGuestUsageTrackingInsert = TablesInsert<'guest_usage_tracking'>

// Update types for commonly used tables
export type DbUserQuizAttemptsUpdate = TablesUpdate<'user_quiz_attempts'>
export type DbUserProgressUpdate = TablesUpdate<'user_progress'>
export type DbMultiplayerRoomsUpdate = TablesUpdate<'multiplayer_rooms'>
export type DbMultiplayerRoomPlayersUpdate = TablesUpdate<'multiplayer_room_players'> 