import type { UIStrings } from './ui-strings';

export const uiStringsDE: UIStrings = {
  navigation: {
    back: 'Zurück',
    close: 'Schließen Sie',
    menu: 'Menü',
    home: 'Startseite',
    topics: 'Themen',
    learn: 'Erkunden Sie',
    profile: 'Profil',
    settings: 'Einstellungen',
    bookmarks: 'Lesezeichen',
    history: 'Geschichte',
    signInToPlay: 'Zum Spielen anmelden',
    signInToSaveProgress: 'Anmelden, um Fortschritt zu speichern',
  },
  topic: {
    loading: 'Details zum Thema laden...',
    loadingDetails: 'Details laden...',
    backToTopics: 'Zurück zu Themen',
    share: 'Thema teilen',
    bookmark: 'Dieses Lesezeichen',
    removeBookmark: 'Lesezeichen entfernen',
    bookmarkThis: 'Dieses Lesezeichen',
    translateThisPage: 'Diese Seite übersetzen',
    showOriginal: 'Original anzeigen',
    whyThisMatters: 'Warum das wichtig ist',
    sourcesAndReferences: 'Quellen und Referenzen',
    takingTheQuiz: 'Das Quiz absolvieren',
    startQuiz: 'Machen Sie das Quiz',
    questionsLabel: 'Fragen',
    estimatedMinutesLabel: 'Est. Min.',
    ratingLabel: 'Bewertung',
    publishedLabel: 'Veröffentlicht',
    levelLabel: 'Ebene',
    difficultyLabel: 'Schwierigkeitsgrad',
    questionsCount: 'Fragen insgesamt',
    estimatedTime: 'Geschätzte Zeit',
    level: 'Ebene',
    difficulty: 'Schwierigkeitsgrad',
    easy: 'Einfach',
    medium: 'Mittel',
    hard: 'Hart',
    beginner: 'Anfänger',
    intermediate: 'Zwischenbericht',
    advanced: 'Fortgeschrittene',
    thinkYouGotIt: 'Haben Sie es verstanden?',
    testYourUnderstanding: 'Testen Sie Ihr Verständnis dieses Themas und sehen Sie, wie gut Sie die wichtigsten Konzepte, die wir behandelt haben, verstanden haben.',
    noSourcesAvailable: 'Noch keine Quellen verfügbar',
    noSourcesDescription: 'Quellen und Verweise werden nach und nach hinzugefügt, sobald der Inhalt geprüft und verifiziert ist.',
    understandingSourceAnalysis: 'Verstehen der Quellenanalyse',
    biasRatingsMeaning: 'Was bedeuten die Verzerrungswerte?',
    credibilityPercentageMeaning: 'Was bedeutet der Prozentsatz der Glaubwürdigkeit?',
    howRatingsDetermined: 'Wie werden diese Bewertungen ermittelt?',
    areRatingsPermanent: 'Sind diese Bewertungen dauerhaft?',
    sourceAnalysisImportance: 'Warum ist das wichtig?',
    ratingsAndReviews: 'Bewertungen und Rezensionen',
    communityFeedback: 'Feedback der Gemeinschaft',
    communityReviews: 'Gemeinschaftliche Bewertungen',
    rateThisTopic: 'Dieses Thema bewerten',
    howHelpfulWasThis: 'Wie hilfreich war das?',
    noRatingsYet: 'Noch keine Bewertungen',
    recentReviews: 'Neueste Bewertungen',
    noReviewsYet: 'Noch keine Bewertungen',
    noReviewsDescription: 'Seien Sie der Erste, der seine Gedanken zu diesem Thema mit anderen teilt.',
    writeFirstReview: 'Schreiben Sie die erste Bewertung',
    viewAllReviews: 'Alle Bewertungen anzeigen',
    editRating: 'Bewertung bearbeiten',
    ratingBreakdown: 'Aufschlüsselung des Ratings',
    shareYourThoughts: 'Teilen Sie Ihre Gedanken mit...',
    completeQuizToReview: 'Füllen Sie das Quiz zur Überprüfung aus',
    takeQuizToShare: 'Machen Sie ein Quiz zum Teilen',
    wasThisHelpful: 'War dies hilfreich?',
    writeAReview: 'Eine Bewertung schreiben',
    rateAndReview: 'Bewertung und Rezension',
    selectRating: 'Bewertung auswählen',
    submitReview: 'Rezension einreichen',
    shareYourThoughtsDesc: 'Teilen Sie Ihre Gedanken zu diesem Thema',
    yourReview: 'Ihre Bewertung',
    recently: 'Kürzlich',
    excellent: 'Ausgezeichnet',
    veryGood: 'Sehr gut',
    good: 'Gut',
    fair: 'Messe',
    poor: 'Schlecht',
    checkingProgress: 'Kontrolle des Fortschritts',
    loadingReviews: 'Bewertungen laden',
    submittingReview: 'Überprüfung einreichen',
    reviewSubmitted: 'Rezension eingereicht',
    thankYouForReview: 'Vielen Dank für Ihre Bewertung!',
    helpful: 'Hilfreich',
    notHelpful: 'Nicht hilfreich',
    markAsHelpful: 'Als hilfreich markieren',
    markAsNotHelpful: 'Als nicht hilfreich markieren',
    completeToReview: 'Füllen Sie das Quiz zur Überprüfung aus',
    takeQuizFirst: 'Machen Sie zuerst ein Quiz',
    finishTopicToReview: 'Beenden Sie das Thema zur Überprüfung',
  },
  translation: {
    selectLanguage: 'Sprache auswählen',
    languagePreferenceSaved: 'Ihre Sprachpräferenz wird für zukünftige Besuche gespeichert',
    translating: 'Übersetzen...',
    translationComplete: 'Übersetzung abgeschlossen',
    translationError: 'Übersetzungsfehler',
    helpTranslate: 'Hilfe bei der Übersetzung',
    noTranslationAvailable: 'Keine Übersetzung verfügbar',
    loadingTranslations: 'Laden von Übersetzungen...',
    checkingTranslations: 'Überprüfung vorhandener Übersetzungen...',
    savingTranslations: 'Speichern von Übersetzungen...',
    autoTranslating: 'Auto-Übersetzung...',
    translatingQuestion: 'Frage übersetzen',
    originalText: 'Original',
    loadingExistingTranslations: 'Vorhandene Übersetzungen laden...',
    translateContent: 'Inhalt übersetzen',
    allQuestionsTranslated: 'Alle Fragen bereits übersetzt',
    translationNeeded: 'Übersetzung erforderlich',
    helpTranslateContent: 'Möchten Sie bei der Übersetzung helfen?',
    translationTest: 'Übersetzungstest',
    translationTestResult: 'Ergebnis der Übersetzungsprüfung',
    translationTestFailed: 'Übersetzungstest fehlgeschlagen',
    initializingTranslationService: 'Initialisierung des Übersetzungsdienstes...',
    translated: 'Übersetzt',
    original: 'Original',
    availableTranslations: 'Verfügbare Übersetzungen',
    fullyTranslated: 'Vollständig übersetzt',
    helpTranslateDescription: 'Helfen Sie, CivicSense in mehr Sprachen zugänglich zu machen',
    contributeTranslation: 'Hilfe bei der Übersetzung',
    contributeTitle: 'Helfen Sie bei der Übersetzung von CivicSense',
    contributeMessage: 'Möchten Sie helfen, CivicSense für mehr Menschen zugänglich zu machen, indem Sie Übersetzungen beisteuern?',
    getStarted: 'Los geht\'s',
    thankYou: 'Ich danke Ihnen!',
    contactInstructions: 'Bitte kontaktieren Sie uns unter translate@civicsense.com, um mit den Übersetzungsbeiträgen zu beginnen.',
    dontSeeLanguage: 'Sie sehen Ihre Sprache nicht?',
    requestLanguage: 'Fordern Sie eine neue Sprache an oder helfen Sie bei der Übersetzung',
    analyzingContent: 'Analyse des Inhalts...',
    translatingToLanguage: 'Übersetzen in {{Sprache}}...',
    optimizingLayout: 'Optimierung des Layouts...',
    elementsTranslated: '{{count}} Elemente übersetzt',
  },
  sources: {
    analysisOverview: 'Analyse Überblick',
    politicalBias: 'Politische Voreingenommenheit',
    factualRating: 'Sachliche Bewertung',
    transparency: 'Transparenz',
    analysisSummary: 'Zusammenfassung der Analyse',
    topicRelevanceCheck: 'Prüfung der Themenrelevanz',
    validationDetails: 'Details zur Validierung',
    strengths: 'Stärken',
    areasForImprovement: 'Bereiche mit Verbesserungspotenzial',
    redFlags: 'Rote Fahnen',
    recommendations: 'Empfehlungen',
    readFullArticle: 'Vollständigen Artikel lesen',
    loadingAnalysis: 'Ladeanalyse...',
    analyzed: 'ANALYSE',
    credibility: 'Glaubwürdigkeit',
  },
  languages: {
    english: 'Englisch',
    spanish: 'Español',
    chinese: '中文',
    vietnamese: 'Tiếng Việt',
    arabic: 'العربية',
    hindi: 'हिन्दी',
    french: 'Französisch',
    german: 'Deutsch',
    portuguese: 'Portugiesisch',
    russian: 'Русский',
    japanese: '日本語',
    korean: '한국어',
    italian: 'Italiano',
  },
  actions: {
    save: 'Speichern Sie',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'bearbeiten',
    share: 'Teilen Sie',
    copy: 'Kopieren',
    download: 'Herunterladen',
    upload: 'Hochladen',
    refresh: 'Auffrischen',
    retry: 'Wiederholung',
    tryAgain: 'Erneut versuchen',
    continue: 'Weiter',
    next: 'Weiter',
    previous: 'Vorherige',
    finish: 'Oberfläche',
    submit: 'Einreichen',
    confirm: 'Bestätigen Sie',
    yes: 'Ja',
    no: 'Nein',
    ok: 'OK',
    dismiss: 'Ablehnen',
  },
  status: {
    loading: 'Laden...',
    saving: 'Sparen...',
    saved: 'Gerettet',
    error: 'Fehler',
    success: 'Erfolg',
    warning: 'Warnung',
    info: 'Infos',
    completed: 'Abgeschlossen',
    failed: 'Gescheitert',
    connecting: 'Verbinden...',
    connected: 'Verbunden',
    disconnected: 'Getrennt',
    offline: 'Offline',
    online: 'Online',
    syncing: 'Synchronisieren...',
    synced: 'Synchronisiert',
  },
  errors: {
    networkError: 'Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.',
    serverError: 'Server-Fehler. Bitte versuchen Sie es später noch einmal.',
    unknownError: 'Ein unbekannter Fehler ist aufgetreten.',
    notFound: 'Inhalt nicht gefunden.',
    unauthorized: 'Sie sind nicht berechtigt, auf diesen Inhalt zuzugreifen.',
    forbidden: 'Der Zugriff auf diesen Inhalt ist verboten.',
    timeout: 'Anfrage wurde abgebrochen. Bitte versuchen Sie es erneut.',
    connectionLost: 'Verbindung unterbrochen. Bitte überprüfen Sie Ihr Internet.',
    invalidInput: 'Ungültige Eingabe. Bitte überprüfen Sie Ihre Eingabe.',
    requiredField: 'Dieses Feld ist erforderlich.',
    loadingFailed: 'Der Inhalt konnte nicht geladen werden.',
    savingFailed: 'Änderungen konnten nicht gespeichert werden.',
    uploadFailed: 'Upload fehlgeschlagen.',
    downloadFailed: 'Download fehlgeschlagen.',
  },
  time: {
    now: 'jetzt',
    today: 'heute',
    yesterday: 'gestern',
    tomorrow: 'morgen',
    thisWeek: 'diese Woche',
    lastWeek: 'letzte Woche',
    thisMonth: 'diesen Monat',
    lastMonth: 'letzten Monat',
    minutesAgo: 'Minuten zuvor',
    hoursAgo: 'vor Stunden',
    daysAgo: 'vor Tagen',
    weeksAgo: 'vor Wochen',
    monthsAgo: 'vor Monaten',
  },
  quiz: {
    question: 'Frage',
    questions: 'Fragen',
    answer: 'Antwort',
    answers: 'Antworten',
    correct: 'Richtig',
    incorrect: 'Falsch',
    explanation: 'Erläuterung',
    hint: 'Hinweis',
    score: 'Ergebnis',
    results: 'Ergebnisse',
    startQuiz: 'Quiz starten',
    nextQuestion: 'Nächste Frage',
    previousQuestion: 'Vorherige Frage',
    finishQuiz: 'Quiz beenden',
    retakeQuiz: 'Quiz wiederholen',
    reviewAnswers: 'Überprüfung Antworten',
    timeRemaining: 'Verbleibende Zeit',
    questionNumber: 'Frage',
    totalQuestions: 'Fragen insgesamt',
    correctAnswers: 'Richtige Antworten',
    incorrectAnswers: 'Falsche Antworten',
    finalScore: 'Endstand',
    complete: 'Quiz abgeschlossen!',
    of: 'von',
    title: 'Quiz',
    loadingQuestion: 'Frage laden...',
    unsupportedQuestionType: 'Nicht unterstützter Fragetyp',
    questionsComplete: 'Fragen vollständig',
    timeUp: 'Die Zeit ist um!',
    pauseQuiz: 'Pause Quiz',
    resumeQuiz: 'Lebenslauf-Quiz',
    exitQuiz: 'Exit-Quiz',
    saveProgress: 'Fortschritt speichern',
    restoreProgress: 'Fortschritt wiederherstellen',
    quizMode: 'Quiz-Modus',
    practiceMode: 'Praxis-Modus',
    testMode: 'Test-Modus',
    selectAnswer: 'Antwort auswählen',
    submitAnswer: 'Antwort abschicken',
    showExplanation: 'Erläuterung anzeigen',
    hideExplanation: 'Erläuterung ausblenden',
    yourAnswer: 'Ihre Antwort',
    correctAnswer: 'Richtige Antwort',
    continueToNext: 'Weiter zum nächsten',
    questionTypes: {
      multipleChoice: 'Multiple Choice',
      trueFalse: 'Richtig/Falsch',
      shortAnswer: 'Kurze Antwort',
      fillInBlank: 'Füllen Sie das Feld aus',
      matching: 'Passend dazu',
      ordering: 'Bestellung',
      crossword: 'Kreuzworträtsel',
    },
    multipleChoice: 'Multiple Choice',
    trueFalse: 'Richtig/Falsch',
    shortAnswer: 'Kurze Antwort',
    fillInBlank: 'Füllen Sie das Feld aus',
    matching: 'Passend dazu',
    ordering: 'Bestellung',
    crossword: 'Kreuzworträtsel',
    accuracy: 'Genauigkeit',
    timeSpent: 'Verwendete Zeit',
    averageTime: 'Durchschnittliche Zeit',
    breakdown: 'Aufschlüsselung',
    recommendations: 'Empfehlungen',
    questionsAnswered: 'Beantwortete Fragen',
    questionsSkipped: 'Übersprungene Fragen',
    percentageScore: 'Prozentuale Punktzahl',
    passingScore: 'Bestehendes Ergebnis',
    passed: 'Bestanden',
    failed: 'Gescheitert',
    tryAgain: 'Erneut versuchen',
    viewReview: 'Rezension ansehen',
    backToTopics: 'Zurück zu Themen',
    difficulty: {
      easy: 'Einfach',
      medium: 'Mittel',
      hard: 'Hart',
    },
  },
  common: {
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen Sie',
    save: 'Speichern Sie',
    delete: 'Löschen',
    edit: 'bearbeiten',
    done: 'Erledigt',
    close: 'Schließen Sie',
    back: 'Zurück',
    next: 'Weiter',
    previous: 'Vorherige',
    skip: 'Überspringen',
    retry: 'Wiederholung',
  },
  gameRoom: {
    questionsPreview: 'Fragen',
    settings: 'Einstellungen',
    sources: 'Quellen',
    quizSettings: 'Quiz-Einstellungen',
    showHints: 'Hinweise anzeigen',
    getHelpfulClues: 'Erhalten Sie hilfreiche Hinweise, wenn Sie nicht weiterkommen',
    showExplanations: 'Erklärungen anzeigen',
    learnWhyAnswersCorrect: 'Erfahren Sie, warum Antworten richtig oder falsch sind',
    hardMode: 'Schwerer Modus',
    hardModeDescription: 'Keine Hinweise/Erklärungen, 15s/Frage',
    timeLimit: 'Zeitliche Begrenzung',
    noTimeLimit: 'Keine zeitliche Begrenzung',
    estimatedTime: 'Geschätzte Zeit',
    questionsAvailable: 'Fragen vorhanden',
    getReady: 'Machen Sie sich bereit, Ihr Wissen zu testen',
    trustedSources: 'Vertrauenswürdige Quellen hinter diesem Inhalt',
    credibilityStandards: 'Alle Quellen erfüllen unsere Glaubwürdigkeitsstandards',
  },
  onboarding: {
    welcome: 'Willkommen bei CivicSense!',
    welcomeTitle: 'Willkommen bei CivicSense',
    welcomeSubtitle: 'Wir helfen Ihnen bei der Einrichtung von personalisierten Lernangeboten für Bürgerinnen und Bürger',
    getStarted: 'Los geht\'s',
    skip: 'Überspringen',
    exploreOnOwn: 'Ich werde auf eigene Faust erkunden',
    timeToComplete: '5-10 Minuten zum Ausfüllen',
    personalizedLearning: 'Personalisiertes Lernen',
    personalizedLearningDesc: 'Maßgeschneiderte Quizze basierend auf Ihren Interessen',
    communityLearning: 'Gemeinschaftliches Lernen',
    communityLearningDesc: 'Lernen Sie mit anderen in Ihrer Gemeinschaft',
    trackProgress: 'Fortschritt verfolgen',
    trackProgressDesc: 'Erleben Sie, wie Ihr staatsbürgerliches Wissen mit der Zeit wächst',
    learnTogether: 'Gemeinsam lernen',
    learnTogetherDesc: 'Fordere deine Freunde in Multiplayer-Quizspielen heraus',
    earnAchievements: 'Errungenschaften verdienen',
    earnAchievementsDesc: 'Schalten Sie Abzeichen frei, wenn Sie Themen meistern',
    personalizeExperience: 'Erfahrung personalisieren',
    personalizeExperienceDesc: 'Passen Sie Ihre Lernreise an',
    learningStyle: 'Lernstil',
    learningStyleDesc: 'Wie möchten Sie am liebsten lernen?',
    visual: 'Visuell',
    visualDesc: 'Lernen durch Bilder und Diagramme',
    reading: 'Lesen',
    readingDesc: 'Lernen durch Texte und Artikel',
    mixed: 'Gemischt',
    mixedDesc: 'Kombinieren Sie visuelles und textbasiertes Lernen',
    difficultyLevel: 'Schwierigkeitsgrad',
    difficultyLevelDesc: 'Wählen Sie Ihre Startschwierigkeit',
    beginner: 'Anfänger',
    beginnerDesc: 'Neu bei bürgerlichen Themen',
    intermediate: 'Zwischenbericht',
    intermediateDesc: 'Einige staatsbürgerliche Kenntnisse',
    adaptive: 'Anpassungsfähig',
    adaptiveDesc: 'Anpassung des Schwierigkeitsgrads beim Lernen',
    location: 'Standort',
    locationOptional: 'Standort (fakultativ)',
    city: 'Stadt',
    state: 'Staat',
    zipCode: 'Postleitzahl',
    dailyReminders: 'Tägliche Mahnungen',
    dailyRemindersDesc: 'Über neue Inhalte benachrichtigt werden',
    whatsNext: 'Was kommt als Nächstes?',
    whatsNextDesc: 'Beginnen Sie Ihre Reise zum bürgerschaftlichen Lernen',
    completeSetup: 'Vollständige Einrichtung',
    invalidZipCode: 'Ungültige Postleitzahl',
    invalidZipCodeDesc: 'Bitte geben Sie eine gültige 5-stellige Postleitzahl ein',
    invalidState: 'Ungültiger Zustand',
    invalidStateDesc: 'Bitte geben Sie einen gültigen Staat ein',
    invalidCity: 'Ungültige Stadt',
    invalidCityDesc: 'Bitte geben Sie einen gültigen Städtenamen ein',
    zipCodePlaceholder: 'Postleitzahl eingeben',
    cityPlaceholder: 'Stadt eingeben',
    statePlaceholder: 'Staat eingeben',
    stateLocationDesc: 'Ihr Bundesland hilft uns, relevante lokale Inhalte anzuzeigen',
    cityLocationDesc: 'Ihre Stadt hilft uns, Bürgerinformationen zu personalisieren',
    zipCodeLocationDesc: 'Ihre Postleitzahl hilft uns, lokale Vertreter zu finden',
    categorySelectionTitle: 'Wählen Sie Ihre Interessen',
    categorySelectionDesc: 'Wählen Sie die Themen, über die Sie etwas erfahren möchten',
    chooseTopics: 'Themen auswählen',
    selectInterests: 'Wählen Sie Ihre Interessen',
    categoryLoading: 'Kategorien laden...',
    categoryLoadingError: 'Kategorien konnten nicht geladen werden',
    questionsAvailable: 'Fragen vorhanden',
    atLeastOneCategory: 'Bitte wählen Sie mindestens eine Kategorie',
    fallbackCategoryDesc: 'Erkundung einer Vielzahl von staatsbürgerlichen Themen',
    step: 'Schritt',
    choosePlayStyle: 'Spielstil wählen',
    setChallenge: 'Herausforderung stellen',
    customize: 'Anpassen',
    soloChallenge: 'Solo-Herausforderung',
    soloChallengeDescription: 'Testen Sie Ihr Wissen individuell',
    orUseCustomSettings: 'Oder benutzerdefinierte Einstellungen verwenden',
  },
  multiplayer: {
    title: 'Multiplayer',
    connectionError: 'Verbindungsfehler',
    failedToJoin: 'Sie konnten dem Raum nicht beitreten. Bitte versuchen Sie es erneut.',
    failedToStart: 'Das Spiel konnte nicht gestartet werden. Bitte versuchen Sie es erneut.',
    leaveRoomConfirm: 'Sind Sie sicher, dass Sie diesen Raum verlassen wollen?',
    inviteMessage: 'Treten Sie meinem CivicSense-Quizraum bei! Code: {{roomCode}}\n\nLade die App herunter und gib diesen Code ein, um gemeinsam zu spielen.',
    inviteTitle: 'Treten Sie meinem CivicSense-Quizraum bei!',
    aiPlayer: 'KI-Spieler',
    humanPlayer: 'Menschlicher Spieler',
    sharingFailed: 'Freigabe fehlgeschlagen. Bitte versuchen Sie es erneut.',
    getReadyToPlay: 'Bereit zum Spielen',
    startReview: 'Start Rückblick',
    waitingForPlayers: 'Warten auf Spieler',
    waitingForHost: 'Warten auf den Gastgeber',
    gameMode: 'Spiel-Modus',
    questions: 'Fragen',
    features: 'Eigenschaften',
    hints: 'Hinweise',
    explanations: 'Erklärungen',
    teamMode: 'Team-Modus',
    powerUps: 'Power Ups',
    npcBattle: 'NPC-Schlacht',
    testYourKnowledge: 'Testen Sie Ihr Wissen',
    skillLevel: 'Qualifikationsniveau',
    roomCode: 'Zimmer Code',
    maxPlayers: 'Maximale Spieler',
    currentPlayers: 'Aktuelle Spieler',
    leaderboard: 'Bestenliste',
    chat: 'Chat',
    settings: 'Einstellungen',
    gameStartingSoon: 'Spiel beginnt bald',
    getReadyFirstQuestion: 'Bereiten Sie sich auf die erste Frage vor',
    battleStarting: 'Beginn der Schlacht',
    firstQuestionLoading: 'Erste Frage Laden',
    question: 'Frage',
    questionNumber: 'Frage',
    hint: 'Hinweis',
    showHint: 'Hinweis anzeigen',
    submitAnswer: 'Antwort abschicken',
    explanation: 'Erläuterung',
    shield: 'Schild',
    attack: 'Angriff',
    focus: 'Schwerpunkt',
    correct: 'Richtig',
    incorrect: 'Falsch',
    timeUp: 'Die Zeit ist um!',
    finalScore: 'Endstand',
    gameComplete: 'Spiel abgeschlossen',
    greatJobLearning: 'Gute Arbeit beim Lernen!',
    shareResults: 'Ergebnisse teilen',
    continue: 'Weiter',
    victory: 'Der Sieg!',
    goodTry: 'Guter Versuch!',
    correctAnswers: 'Richtige Antworten',
    accuracy: 'Genauigkeit',
    playAgain: 'Erneut spielen',
    exit: 'Ausfahrt',
    ready: 'Bereit',
    notReady: 'Nicht bereit',
    thinking: 'Nachdenken',
    answered: 'Antwortet',
    roomChat: 'Zimmer-Chat',
    players: 'Spieler',
    typeMessage: 'Typ Nachricht',
    enterToSend: 'Eingabe zum Senden',
    beRespectful: 'Respektvoll sein',
    playerJoined: 'Spieler beigetreten',
    playerLeft: 'Spieler links',
    gameStarting: 'Spielbeginn',
    welcomeToQuiz: 'Willkommen zum Quiz',
    allowNewPlayers: 'Neue Spieler zulassen',
    allowNewPlayersDesc: 'Erlauben Sie neuen Spielern, dem Spiel beizutreten',
    enableBoosts: 'Boosts aktivieren',
    enableBoostsDesc: 'Power-Ups für Spieler freischalten',
    showHints: 'Hinweise anzeigen',
    showHintsDesc: 'Hinweise für Spieler anzeigen',
    autoAdvance: 'Auto Advance',
    autoAdvanceDesc: 'Fragen automatisch weiterleiten',
    realTimeScores: 'Echtzeit-Ergebnisse',
    realTimeScoresDesc: 'Spielstände in Echtzeit anzeigen',
    enableChat: 'Chat freigeben',
    enableChatDesc: 'Chat für Spieler einschalten',
    connectionLost: 'Verbindung verloren',
    failedToSubmitAnswer: 'Antwort nicht abgeschickt',
    networkError: 'Netzwerkfehler',
    ai: 'AI',
    host: 'Gastgeber',
    titleDescription: 'Beschreibung',
    liveGameScreen: 'Live-Spiel',
  },
  analytics: {
    loadingInsights: 'Einblicke laden...',
    couldNotLoadInsights: 'Die Lerneinblicke konnten nicht geladen werden. Bitte versuchen Sie es erneut.',
    couldNotRefreshInsights: 'Einblicke konnten nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
    excellentPerformance: 'Ausgezeichnete Leistung! Siehe personalisierte nächste Schritte.',
    goodProgress: 'Gute Fortschritte! Entdecken Sie Bereiche, die verbessert werden müssen.',
    keepLearning: 'Lernen Sie weiter! Erhalten Sie individuelle Lerntipps.',
    needHelp: 'Haben Sie Probleme? Holen Sie sich persönliche Hilfe.',
  },
  news: {
    dailyNews: 'Tägliche Nachrichten',
    latestNews: 'Neueste Nachrichten',
    articles: 'Artikel',
    fetchingFrom: 'Abrufe von AP, Reuters, NPR, BBC, Politico...',
    noValidArticles: 'Keine gültigen Artikel nach Filterung gefunden',
    failedToLoad: 'Nachrichten konnten nicht geladen werden',
    newsAPI: 'Nachrichten-API fehlgeschlagen',
    unknownError: 'Unbekannter Fehler',
    refreshNews: 'Nachrichten aktualisieren',
    updating: 'Aktualisieren...',
    today: 'Heute',
    yesterday: 'Gestern',
    breakingNews: 'Eilmeldung',
    newsUpdates: 'Aktuelle Nachrichten',
    readMore: 'Mehr lesen',
    readFull: 'Vollständigen Artikel lesen',
    source: 'Quelle',
    publishedBy: 'Herausgegeben von',
    lastUpdated: 'Zuletzt aktualisiert',
    originalSource: 'Ursprüngliche Quelle',
    previousArticle: 'Vorheriger Artikel',
    nextArticle: 'Nächster Artikel',
    backToNews: 'Zurück zu Nachrichten',
    filterByCategory: 'Nach Kategorie filtern',
    sortBy: 'Sortieren nach',
    newest: 'Neuestes',
    oldest: 'Älteste',
    mostRelevant: 'Am relevantesten',
    noArticlesFound: 'Keine Artikel gefunden',
    loadingFailed: 'Nachrichtenartikel konnten nicht geladen werden',
    tryAgainLater: 'Bitte versuchen Sie es später noch einmal',
    shareArticle: 'Artikel teilen',
    copyLink: 'Link kopieren',
    linkCopied: 'Link in die Zwischenablage kopiert',
    savedToDb: 'in DB gespeichert',
    ago: 'vor',
  },
  collections: {
    takeAction: 'Maßnahmen ergreifen',
    planned: 'geplant',
    completed: 'abgeschlossen',
    immediateActions: 'Sofortige Maßnahmen',
    immediateActionsDesc: 'Dies sind konkrete Schritte, die Sie sofort unternehmen können, um das Gelernte anzuwenden.',
    civicEngagementOpportunities: 'Möglichkeiten für bürgerschaftliches Engagement',
    civicEngagementDesc: 'Verbinden Sie sich mit Ihrer Gemeinschaft und erzielen Sie mit diesen Möglichkeiten eine breitere Wirkung.',
    markAsCompleted: 'Als abgeschlossen markieren',
    yourActionPlan: 'Ihr Aktionsplan',
    youvePlannedActions: 'Sie haben eine {{count}} Aktion{{plural}} geplant',
    andCompleted: ' und abgeschlossen {{count}}',
    greatJobTakingAction: 'Gut gemacht, dass du dich für dein bürgerschaftliches Lernen eingesetzt hast! 🎉',
    keepGoing: 'Weitermachen! Wenn wir aktiv werden, stärken wir die Demokratie.',
    readyToTakeAction: 'Sind Sie bereit, Maßnahmen zu ergreifen?',
    checkOffActions: 'Kreuzen Sie die Maßnahmen an, die Sie ergreifen wollen. Jeder kleine Schritt macht die Demokratie stärker.',
    outstanding: 'Hervorragend!',
    completedAllActions: 'Sie haben alle vorgeschlagenen Aktionen durchgeführt. Sie bewirken einen echten Unterschied in Ihrer Gemeinde!',
    quickCheck: 'Schnell-Check',
    complete: 'Vollständig',
    submitAnswer: 'Antwort abschicken',
    correct: 'Richtig!',
    notQuiteRight: 'Nicht ganz richtig',
    showHint: 'Hinweis anzeigen',
    hideHint: 'Hinweis ausblenden',
    selectAnAnswer: 'Wählen Sie eine Antwort',
    answerSelected: 'Antwort ausgewählt',
    trueOrFalse: 'Richtig oder falsch?',
    selectTrueFalse: 'Wählen Sie Wahr oder Falsch',
    yourResponse: 'Ihre Antwort',
    enterYourAnswer: 'Geben Sie Ihre Antwort ein...',
    submitResponse: 'Antwort einreichen',
    responseRecorded: 'Aufgezeichnete Antwort',
    thankYouForInput: 'Vielen Dank für Ihren Beitrag. Ihre Antwort wurde gespeichert.',
    enterYourResponse: 'Geben Sie Ihre Antwort ein',
    charactersCount: '{{Zahl}} Zeichen',
    rankingExercise: 'Ranking-Übung',
    dragToReorder: 'Ziehen Sie die Elemente, um sie von der wichtigsten zur unwichtigsten zu sortieren:',
    rankingComplete: 'Rangliste vollständig',
    dragToReorderItems: 'Ziehen, um Artikel neu zu ordnen',
    rankingExplanation: 'Rangliste Erläuterung',
    interactiveTimeline: 'Interaktive Zeitleiste',
    clickEachEvent: 'Klicken Sie auf jedes Ereignis, um es zu erkunden ({Aktuell}/{Gesamt})',
    exploreAllEvents: 'Alle Veranstaltungen erkunden',
    reflection: 'Reflexion',
    reflectionPrompts: 'Reflexionsanregungen',
    shareYourThoughts: 'Teilen Sie Ihre Gedanken mit...',
    saveReflection: 'Reflexion speichern',
    actionChecklist: 'Aktions-Checkliste',
    actionsCompleted: '{erledigt} von {insgesamt} abgeschlossenen Aktionen',
    primaryAction: 'Primäre Aktion',
    bonusActions: 'Bonus-Aktionen (fakultativ)',
    helpfulResources: 'Hilfreiche Ressourcen',
    markAsComplete: 'Als vollständig markieren',
    actionComplete: 'Aktion abgeschlossen',
    takeActionStatus: 'Maßnahmen ergreifen',
    pending: 'Anhängig',
    contactRepresentatives: 'Kontakt zu Ihren Vertretern',
    contactsReached: '{erreicht} von {gesamten} Kontakten erreicht',
    whoToContact: 'Wer ist zu kontaktieren?',
    messageTemplates: 'Vorlagen für Nachrichten',
    sendWithTemplate: 'Mit Vorlage senden',
    visitWebsite: 'Website besuchen →',
    alreadyContacted: 'Bereits kontaktiert',
    markAsContacted: 'Als kontaktiert markieren',
    quickPoll: 'Schnelle Umfrage',
    castVote: 'Stimmabgabe',
    thanksForVoting: 'Vielen Dank für Ihre Stimme!',
    results: 'Ergebnisse:',
    votes: 'Stimmen',
    surveyTitle: 'Umfrage',
    questionProgress: 'Frage {aktuell} von {insgesamt}',
    simulationResults: 'Ergebnisse der Simulation',
    yourAnswer: 'Ihre Antwort...',
    previous: 'Vorherige',
    next: 'Weiter',
    completeSurvey: 'Vollständige Umfrage',
    externalSurveyDesc: 'Diese Umfrage wird von einem externen Anbieter durchgeführt. Klicken Sie auf den untenstehenden Link, um teilzunehmen.',
    openSurvey: 'Offene Umfrage',
    opinionScale: 'Meinungsskala',
    moveSlider: 'Bewegen Sie den Schieberegler, um anzugeben, wie sehr Sie zustimmen',
    submitOpinion: 'Stellungnahme abgeben',
    thanksForOpinion: 'Vielen Dank für die Mitteilung Ihrer Meinung!',
    stronglyDisagree: 'Stimmt überhaupt nicht zu',
    disagree: 'Nicht einverstanden',
    neutral: 'Neutral',
    agree: 'Zustimmen',
    stronglyAgree: 'Stimme voll und ganz zu',
    policySimulation: 'Politik-Simulation',
    scenario: 'Szenario',
    adjustVariables: 'Variablen anpassen',
    runSimulation: 'Simulation ausführen',
    rolePlayingExercise: 'Rollenspiel-Übung',
    chooseYourRole: 'Wählen Sie Ihre Rolle',
    objectives: 'Zielsetzungen:',
    whatActionTake: 'Welche Aktion führen Sie in dieser Runde durch?',
    negotiateStakeholders: 'Mit anderen Akteuren verhandeln',
    gatherMoreInfo: 'Sammeln Sie mehr Informationen',
    rolePlayComplete: 'Rollenspiel abgeschlossen!',
    yourDecisions: 'Ihre Entscheidungen',
    decisionPath: 'Entscheidungsweg',
    decisionPoint: 'Entscheidungspunkt',
    chooseResponse: 'Wählen Sie Ihre Antwort:',
    finalOutcome: 'Endgültiges Ergebnis',
    reflectionNote: 'Überlegen Sie, wie andere Entscheidungen zu anderen Ergebnissen hätten führen können. Reale politische Entscheidungen haben oft komplexe Folgen, die nicht sofort ersichtlich sind.',
    tryDifferentPath: 'Versuchen Sie einen anderen Weg',
    yourPath: 'Ihr Weg:',
    compareAndContrast: 'Vergleich und Gegenüberstellung',
    continueLearning: 'Weiteres Lernen',
    viewAllCards: 'Alle Karten anzeigen',
    nextCard: 'Nächste Karte',
    previousCard: 'Vorherige',
    exploreImage: 'Das Bild erforschen',
    dragAndDrop: 'Ziehen und Ablegen',
    availableItems: 'Verfügbare Artikel',
    interactiveMap: 'Interaktive Karte',
    checkAnswers: 'Antworten prüfen',
    allItemsAssigned: 'Alle zugewiesenen Posten',
    assigned: 'zugewiesen',
    adjustParameters: 'Parameter anpassen',
    viewResults: 'Ergebnisse anzeigen',
    resetSimulation: 'Simulation zurücksetzen',
    fillInTheBlanks: 'Füllen Sie die Lücken aus',
    matchingPairs: 'Passende Paare',
    categorizeItems: 'Artikel kategorisieren',
    progressUpdate: 'Aktueller Stand der Dinge',
    wellDone: 'Gut gemacht!',
    goodEffort: 'Gute Arbeit!',
    keepTrying: 'Versuchen Sie es weiter!',
    perfect: 'Perfekt!',
    almostThere: 'Fast geschafft!',
  },
  accessibility: {
    skipToContent: 'Zum Inhalt springen',
    mainNavigation: 'Hauptnavigation',
    userMenu: 'Benutzermenü',
    darkModeToggle: 'Dunkelmodus umschalten',
    languageSelector: 'Sprache auswählen',
    closeDialog: 'Dialog schließen',
    openMenu: 'Menü öffnen',
    closeMenu: 'Menü schließen',
    loadingContent: 'Inhalt laden',
    expandSection: 'Abschnitt erweitern',
    collapseSection: 'Abschnitt kollabieren',
    playAudio: 'Audio abspielen',
    pauseAudio: 'Audio anhalten',
    stopAudio: 'Audio anhalten',
    increaseSpeed: 'Geschwindigkeit erhöhen',
    decreaseSpeed: 'Geschwindigkeit vermindern',
    goBack: 'Zurückgehen',
    openLink: 'Link öffnen',
    bookmark: 'Bookmarken Sie dieses Thema',
    removeBookmark: 'Lesezeichen entfernen',
  },
  settings: {
    title: 'Einstellungen',
    account: 'Konto',
    preferences: 'Präferenzen',
    notifications: 'Benachrichtigungen',
    privacy: 'Datenschutz',
    accessibility: 'Erreichbarkeit',
    language: 'Sprache',
    theme: 'Thema',
    themes: {
      light: 'Licht',
      dark: 'Dunkelheit',
      system: 'System',
    },
    email: 'E-Mail',
    password: 'Passwort',
    changePassword: 'Passwort ändern',
    deleteAccount: 'Konto löschen',
    exportData: 'Daten exportieren',
    saveChanges: 'Änderungen speichern',
    saved: 'Gespeicherte Einstellungen',
    emailNotifications: 'E-Mail-Benachrichtigungen',
    pushNotifications: 'Push-Benachrichtigungen',
    weeklyDigest: 'Wöchentlicher Digest',
    achievementAlerts: 'Leistungswarnungen',
    soundEffects: 'Sound-Effekte',
    animations: 'Animationen',
    highContrast: 'Hoher Kontrast',
    largeText: 'Großer Text',
    reducedMotion: 'Reduzierte Bewegung',
    keyboardShortcuts: 'Tastaturkurzbefehle',
    timezone: 'Zeitzone',
    dateFormat: 'Datum Format',
    giftCredits: 'Gutschriften',
    premium: 'Prämie',
    subscription: 'Abonnement',
    features: 'Eigenschaften',
    upgrade: 'Upgrade',
    manage: 'Verwalten Sie',
    cancel: 'Abbrechen',
    signOut: 'Abmelden',
    accountData: 'Kontodaten',
    displayName: 'Name anzeigen',
    currentPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    confirmPassword: 'Bestätigen Sie Ihr Passwort',
    updateAccount: 'Konto aktualisieren',
    pleaseSignIn: 'Bitte melden Sie sich an, um auf die Einstellungen zuzugreifen',
    signInToAccess: 'Bitte melden Sie sich an, um auf die Einstellungen zuzugreifen',
    editProfile: 'Profil bearbeiten',
    fullName: 'Vollständiger Name',
    fullNameRequired: 'Vollständiger Name ist erforderlich',
    bio: 'Bio',
    location: 'Standort',
    website: 'Website',
    country: 'Land',
    stateProvince: 'Staat/Provinz',
    city: 'Stadt',
    profileUpdated: 'Profil aktualisiert! ✅',
    profileUpdatedMessage: 'Ihre Änderungen wurden erfolgreich gespeichert.',
    great: 'Großartig!',
    discardChanges: 'Änderungen verwerfen?',
    discardChangesMessage: 'Sie haben ungespeicherte Änderungen. Sind Sie sicher, dass Sie sie verwerfen wollen?',
    keepEditing: 'Weiter bearbeiten',
    discard: 'Ablegen',
    permissionRequired: 'Erlaubnis erforderlich',
    photoLibraryPermission: 'Bitte erlauben Sie den Zugriff auf Ihre Fotobibliothek, um Ihren Avatar zu ändern.',
    uploadFailed: 'Avatar konnte nicht hochgeladen werden. Bitte versuchen Sie es erneut.',
    autoTranslateContent: 'Automatisch übersetzte Inhalte',
    autoTranslateContentDesc: 'Automatisches Übersetzen von Quizfragen und Lektionen',
    preserveCivicTerms: 'Staatsbürgerliche Begriffe bewahren',
    preserveCivicTermsDesc: 'Wichtige staatsbürgerliche Begriffe in Übersetzungen korrekt wiedergeben',
    clearTranslationCache: 'Übersetzungs-Cache löschen',
    clearTranslationCacheDesc: 'Gespeicherte Übersetzungen zurücksetzen, um neue Inhalte zu erhalten',
    translationCacheCleared: 'Übersetzungscache erfolgreich geleert',
    translationCacheClearError: 'Übersetzungs-Cache konnte nicht gelöscht werden',
  },
  survey: {
    question: 'Frage',
    questions: 'Fragen',
    required: 'Erforderlich',
    optional: 'Optional',
    progress: 'Fortschritt',
    complete: 'Vollständig',
    submit: 'Einreichen',
    next: 'Weiter',
    previous: 'Vorherige',
    skip: 'Überspringen',
    save: 'Speichern Sie',
    saveProgress: 'Fortschritt speichern',
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    pleaseSelectOption: 'Bitte wählen Sie eine Option',
    pleaseProvideAnswer: 'Bitte geben Sie eine Antwort',
    invalidEmail: 'Bitte geben Sie eine gültige E-Mail Adresse ein',
    invalidPhone: 'Bitte geben Sie eine gültige Telefonnummer ein',
    tooManySelections: 'Zu viele Auswahlmöglichkeiten',
    maxSelections: 'Maximale Auswahlmöglichkeiten erreicht',
    selectAtLeast: 'Bitte wählen Sie mindestens',
    selectAtMost: 'Bitte wählen Sie höchstens',
    charactersRemaining: 'verbleibende Zeichen',
    wordLimit: 'Wortgrenze überschritten',
    fileUpload: 'Hochladen von Dateien',
    chooseFile: 'Datei auswählen',
    removeFile: 'Datei entfernen',
    uploadError: 'Upload fehlgeschlagen',
    stronglyDisagree: 'Stark ablehnend',
    disagree: 'Nicht einverstanden',
    neutral: 'Neutral',
    agree: 'Zustimmen',
    stronglyAgree: 'Stimme voll und ganz zu',
    pleaseSpecify: 'Bitte angeben...',
    other: 'Andere',
    none: 'Keine',
    all: 'Alle',
    completed: 'Abgeschlossen',
    thankYou: 'Ich danke Ihnen!',
    submissionComplete: 'Ihre Übermittlung wurde abgeschlossen',
    viewResults: 'Ergebnisse anzeigen',
    retake: 'Wiederholung',
    share: 'Teilen Sie',
  },
  audio: {
    play: 'Spielen',
    pause: 'Pause',
    stop: 'Stopp',
    resume: 'Lebenslauf',
    restart: 'Neustart',
    mute: 'Stummschalten',
    unmute: 'Aufheben der Stummschaltung',
    volume: 'Band',
    speed: 'Geschwindigkeit',
    voice: 'Stimme',
    settings: 'Einstellungen',
    audioControls: 'Audio-Steuerungen',
    voiceSettings: 'Spracheinstellungen',
    quality: 'Qualität',
    high: 'Hoch',
    medium: 'Mittel',
    low: 'Niedrig',
    autoPlay: 'Automatische Wiedergabe',
    loop: 'Schleife',
    highlighting: 'Hervorhebung von Wörtern',
    cloudTTS: 'Wolke TTS',
    browserTTS: 'Browser-TTS',
    language: 'Sprache',
    male: 'Männlich',
    female: 'Weiblich',
    neutral: 'Neutral',
    loading: 'Laden...',
    error: 'Audio-Fehler',
    notSupported: 'Audio nicht unterstützt',
    recovery: 'Audio wiederherstellen',
    testAudio: 'Test Audio',
    readPage: 'Seite lesen',
    readSelection: 'Auswahl lesen',
    keyboardShortcuts: 'Tastaturkurzbefehle',
    diagnostics: 'Diagnostik',
    usage: 'Verwendung',
    charactersUsed: 'Verwendete Zeichen',
    estimatedCost: 'Geschätzte Kosten',
    voiceCount: 'Anzahl der Stimmen',
    speaking: 'Sprechen',
    pending: 'Anhängig',
    paused: 'Pausiert',
    lastUpdate: 'Letzte Aktualisierung',
  },
  profileScreenTitle: 'Mein Profil',
  loadingProfile: 'Ihr Profil wird geladen...',
  redirectingToLogin: 'Weiterleitung zum Login...',
  leaderboard: {
    title: 'Bestenliste',
    loadingLeaderboard: 'Laden der Rangliste...',
    yourRanking: 'Ihr Ranking',
    currentRank: 'Aktueller Rang',
    topPercentile: 'Höchstes Perzentil',
    totalUsers: 'Benutzer insgesamt',
    today: 'Heute',
    thisWeek: 'Diese Woche',
    thisMonth: 'Dieser Monat',
    allTime: 'Alle Zeiten',
    score: 'Ergebnis',
    xp: 'XP',
    streak: 'Streak',
    quizzes: 'Quizze',
    achievements: 'Leistungen',
    you: '(Sie)',
    takeQuizToClimb: 'Mach ein Quiz zum Klettern!',
    new: 'NEU',
  },
  search: {
    title: 'Suche',
    placeholder: 'Sammlungen und Themen durchsuchen...',
    clearHistory: 'Suchverlauf löschen',
    analytics: '{{Anzahl}} Suchen - {{Angesehen}} betrachtete Artikel',
    streak: '{{Zahl}} Tagestreife',
    loadingData: 'Laden von Suchdaten...',
    searching: 'Suche in Sammlungen und Themen...',
    keepTyping: 'Tippen Sie weiter...',
    minCharacters: 'Geben Sie mindestens 2 Zeichen ein, um die Suche zu starten',
    filterAll: 'Alle',
    filterCollections: 'Sammlungen',
    filterTopics: 'Themen',
    noResults: 'Keine Ergebnisse gefunden',
    noResultsHint: 'Versuchen Sie, nach anderen Stichwörtern wie "Verfassung", "Wahlen" oder "Oberster Gerichtshof" zu suchen.',
    continueLearning: 'Weiteres Lernen',
    pickUpWhereLeft: 'Weitermachen, wo Sie aufgehört haben',
    recommended: 'Empfohlen',
    recentSearches: 'Letzte Suchanfragen',
    clearAll: 'Alle löschen',
    popularTopics: 'Beliebte Themen',
    tapToSearch: 'Tippen Sie auf , um schnell zu suchen',
    searchTips: 'Tipps zur Suche',
    tip1: 'Versuchen Sie es mit spezifischen Themen wie "First Amendment" oder "Electoral College".',
    tip2: 'Artikel, die Sie kürzlich angesehen haben, erscheinen zuerst in den Ergebnissen',
    tip3: 'Ihr Suchverlauf hilft uns, bessere Empfehlungen zu geben',
    collection: 'Sammlung',
    topic: 'Thema',
    questionCount: '{{Zahl}} Fragen',
    recent: 'Neueste',
  },
  profile: {
    title: 'Mein Profil',
    loadingProfile: 'Ihr Profil wird geladen...',
    redirectingToLogin: 'Weiterleitung zum Login...',
    yourProgress: 'Ihr Fortschritt',
    calendarIntegration: 'Kalender-Integration',
    googleCalendarSync: 'Google Kalender Sync',
    googleCalendarSyncDesc: 'Synchronisieren Sie Ihren Studienplan mit Google Calendar',
    dailyQuizReminders: 'Tägliche Quiz-Erinnerungen',
    dailyQuizRemindersDesc: 'Lassen Sie sich an die täglichen Quizfragen erinnern',
    smartScheduling: 'Intelligente Terminplanung',
    smartSchedulingDesc: 'KI-gestützte optimale Studienzeiten',
    learningPodSessions: 'Lernpod-Sitzungen',
    learningPodSessionsDesc: 'Erinnerungen an Gruppensitzungen',
    lastSynced: 'Zuletzt synchronisiert',
    smartStudyRecommendations: 'Empfehlungen für intelligente Studien',
    scheduleThisTime: 'Diese Zeit einplanen',
    learningPods: 'Lernpods',
    constitutionalLawStudyGroup: 'Studiengruppe Verfassungsrecht',
    membersOnline: 'Mitglieder - {{online}} jetzt online',
    billOfRightsReviewSession: 'Sitzung zur Überprüfung der Bill of Rights',
    managePods: 'Pods verwalten',
    editProfile: 'Profil bearbeiten',
    updateYourInformation: 'Aktualisieren Sie Ihre Informationen',
    preferences: 'Präferenzen',
    learningAndNotifications: 'Lernen und Benachrichtigungen',
    exportLearningProgress: 'Lernfortschritt exportieren',
    howWouldYouLikeToShare: 'Wie möchten Sie Ihre Fortschritte mitteilen?',
    exportAsPDF: 'Als PDF exportieren',
    shareWithPod: 'Teilen mit Pod',
    generateReport: 'Erzeugen Ihres CivicSense-Analyseberichts',
    shareReport: 'Bericht teilen',
    exportFailed: 'Export fehlgeschlagen',
    exportError: 'Ihr Lernanalysebericht konnte nicht erstellt werden. Bitte versuchen Sie es erneut.',
    updateProfilePhoto: 'Profilfoto aktualisieren',
    choosePhotoMethod: 'Wählen Sie, wie Sie Ihr Foto hinzufügen möchten',
    camera: 'Kamera',
    photoLibrary: 'Fotobibliothek',
    profilePhotoUpdated: 'Profilfoto erfolgreich aktualisiert!',
    uploadPhotoFailed: 'Hochladen des Profilfotos fehlgeschlagen',
    profileCompletion: 'Profil {{Prozent}}% vollständig',
    profileCompletePercent: 'Profil {{Prozent}}% vollständig',
    quizzes: 'Quizze',
    avgScore: 'Durchschnittliche Punktzahl',
    dayStreak: 'Tagesträhne',
    studyTime: 'Studienzeit',
    achievements: 'Errungenschaften',
    viewDetailedStats: 'Detaillierte Statistiken anzeigen',
    connectedViaGoogle: 'Verbunden über Google',
    appVersion: 'CivicSense v1.0.0 - Gemacht mit ❤️ für Demokratie',
    madeWithLoveForDemocracy: 'Hergestellt mit ❤️ für Demokratie',
  },
  saved: {
    title: 'Gerettet',
    subtitle: 'Ihre Lesezeichen und Ihr Fortschritt',
    loadingSavedContent: 'Laden Ihrer gespeicherten Inhalte...',
    collections: 'Sammlungen',
    createCollection: 'erstellen.',
    organizeYourLearning: 'Organisieren Sie Ihr Lernen',
    organizeYourLearningDesc: 'Erstellen Sie Sammlungen, um Ihre gespeicherten Inhalte in thematischen Ordnern zu organisieren und so das Lernen zu erleichtern.',
    lessons: 'Lektionen',
    lessonsDesc: 'Mehrstufige Kurse von CivicSense',
    myCollections: 'Meine Sammlungen',
    myCollectionsDesc: 'Ihre organisierten Inhaltsordner',
    createYourFirstCollection: 'Erstellen Sie Ihre erste Sammlung, um Ihre gespeicherten Inhalte zu organisieren',
    filterContent: 'Inhalt filtern',
    allContent: 'Alle',
    topics: 'Themen',
    quizResults: 'Quiz-Ergebnisse',
    customQuizzes: 'Benutzerdefinierte Quizze',
    bookmarks: 'Lesezeichen',
    noSavedLessons: 'Keine gespeicherten Lektionen',
    noSavedTopics: 'Keine gespeicherten Themen',
    noQuizResults: 'Keine Quiz-Ergebnisse',
    noBookmarks: 'Keine Lesezeichen',
    noSavedItems: 'Keine gespeicherten Elemente',
    exploreContent: 'Inhalt erkunden',
    selectItems: 'Artikel auswählen',
    itemsSelected: '{{count}} item{{plural}} ausgewählt',
    selectItemsToOrganize: 'Zu organisierende Objekte auswählen',
    organizeSelectedItems: 'Organisieren ausgewählter Objekte',
    moveToCollection: 'In die Sammlung verschieben',
    removeItem: 'Artikel entfernen',
    removeItemConfirm: 'Sind Sie sicher, dass Sie diesen gespeicherten Artikel entfernen möchten?',
    highlightedText: 'Hervorgehobener Text',
    textSnippet: 'Textausschnitt',
    customQuiz: 'Benutzerdefiniertes Quiz',
    continueYourCivicsAssessment: 'Setzen Sie Ihre Bewertung in Staatsbürgerkunde fort',
    questionsCompleted: '{{Erledigt}} von {{Gesamt}} Fragen abgeschlossen',
    started: 'Gestartet {{Datum}}',
    scoreLabel: 'Ergebnis',
    xpEarned: '+{{xp}} XP',
    questions: 'Fragen',
    draft: 'DRAFT',
    published: 'VERÖFFENTLICHT',
    savedRecently: 'Gespeicherte {{Zeit}}',
    savedTime: 'Gespeichert vor {{time}}',
    keepGoing: 'Weitermachen! 🎯',
    nothingNewToday: 'Heute nichts Neues? Perfekter Zeitpunkt zum Erkunden! 📚',
    nothingNewTodayDesc: 'Versuchen Sie, mit den Pfeilen oben zu anderen Terminen zu navigieren, oder erkunden Sie diese Lernoptionen unten.',
    currentEvents: 'Aktuelle Ereignisse',
    currentEventsDesc: 'Tippen Sie auf eine beliebige Geschichte, um ein Quiz zu diesem Thema zu erstellen.',
    findingCurrentEvents: 'Suche nach aktuellen Ereignissen für {{Datum}}...',
    continueWhereLeftOff: 'Weitermachen, wo Sie aufgehört haben',
    orExploreMore: 'Oder erkunden Sie mehr',
    continueLearning: 'Weiter lernen',
    exploreQuizTopics: 'Quizthemen erforschen',
    exploreQuizTopicsDesc: 'Entdecken Sie Quizfragen zu Regierung, Rechten und Bürgerbeteiligung',
    takeCivicsAssessment: 'Staatsbürgerkundeprüfung ablegen',
    takeCivicsAssessmentDesc: 'Testen Sie Ihr Wissen über die amerikanische Regierung und Demokratie',
    reviewSavedContent: 'Gespeicherte Inhalte überprüfen',
    reviewSavedContentDesc: 'Lernen Sie weiter von den Themen, die Sie in Ihren Lesezeichen gespeichert haben',
    createCustomContent: 'Benutzerdefinierte Inhalte erstellen',
    createCustomContentDesc: 'Gestalten Sie Ihre eigenen Themen und Fragen',
    pro: 'PRO',
  },
  learn: {
    title: 'Lernen Sie',
    loadingQuizCollections: 'Laden von Quizsammlungen...',
    usingOfflineData: 'Offline-Quizdaten verwenden - Netzwerk nicht verfügbar',
    featuredLessons: 'Ausgewählte Lektionen',
    featuredLessonsDesc: 'Kuratierte Unterrichtssammlungen zu aktuellen Themen',
    allCollections: 'Alle Sammlungen',
    allCollectionsDesc: 'Umfassender Test der staatsbürgerlichen Kenntnisse',
    collections: '{{Zahl}} Sammlungen',
    topics: 'Themen',
    topicsDesc: 'Erkunden Sie einzelne staatsbürgerliche Themen mit gezielten Fragen',
    noQuizCollections: 'Keine Quizsammlungen verfügbar',
    noQuizCollectionsOffline: 'Überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.',
    noQuizCollectionsOnline: 'Neue Quizsammlungen werden hier erscheinen, sobald sie verfügbar sind.',
    quizDataSource: 'Quelle der Quizdaten: {{Quelle}}',
    liveAPI: 'Live-API',
    offlineCache: 'Offline-Cache',
    showingRealTimeData: 'Anzeige von Echtzeit-Quizsammlungen vom Server',
    usingCachedData: 'Verwendung zwischengespeicherter Quizdaten - einige Inhalte können veraltet sein',
    new: 'Neu',
    featured: 'Ausgewählt',
    estimatedTime: '{{Zeit}} min',
    completionRate: '{{Rate}}% Fertigstellung',
    completion: 'Fertigstellung',
    continue: 'Weiter',
    start: 'Start',
    available: 'Verfügbar',
    difficulty: 'Schwierigkeitsgrad',
    searchTopics: 'Themen suchen',
  },
  home: {
    welcomeBack: 'Willkommen zurück, {{Name}}',
    welcome: 'CivicSense',
    citizen: 'Bürgerin',
    loadingYourCivicJourney: 'Laden Sie Ihre Reise in die Stadt...',
    loadingContent: 'Inhalt laden...',
    today: 'Heute',
    dailyChallenge: 'Tägliche Herausforderung ({{erledigt}} von {{Gesamt}})',
    questionsOf: '{{erledigt}} von {{Gesamt}}',
    dayStreak: '{{count}} Tag{{plural}}',
    days: 'Tage',
    day: 'Tag',
    loadingDate: 'Laden {{date}}',
    noFeaturedToday: 'Heute keine Themenschwerpunkte',
    noFeaturedTodayDesc: 'Schauen Sie später wieder vorbei für aktuelle Nachrichten und besondere Inhalte',
    checkBackLater: 'Schauen Sie später wieder vorbei für aktuelle Nachrichten und besondere Inhalte',
    keepGoingTarget: 'Weitermachen! 🎯',
    navigateToOtherDates: 'Versuchen Sie, mit den Pfeilen oben zu anderen Terminen zu navigieren, oder erkunden Sie diese Lernoptionen unten.',
    exploreMoreOptions: 'Erkunden Sie die folgenden Lernoptionen',
    todaysCurrentEvents: 'Heutige aktuelle Ereignisse',
    currentEventsForDate: '{{Datum}} Aktuelle Ereignisse',
    tapAnyStoryToCreate: 'Tippen Sie auf eine beliebige Geschichte, um ein Quiz zu diesem Thema zu erstellen.',
    findingCurrentEventsFor: 'Suche nach aktuellen Ereignissen für {{Datum}}...',
    exploreQuizTopics: 'Quizthemen erforschen',
    exploreQuizTopicsDesc: 'Entdecken Sie Quizfragen zu Regierung, Rechten und Bürgerbeteiligung',
    takeCivicsAssessment: 'Staatsbürgerkundeprüfung ablegen',
    takeCivicsAssessmentDesc: 'Testen Sie Ihr Wissen über die amerikanische Regierung und Demokratie',
    reviewSavedContent: 'Gespeicherte Inhalte überprüfen',
    reviewSavedContentDesc: 'Lernen Sie weiter von den Themen, die Sie in Ihren Lesezeichen gespeichert haben',
    createCustomContent: 'Benutzerdefinierte Inhalte erstellen',
    createCustomContentDesc: 'Gestalten Sie Ihre eigenen Themen und Fragen',
    designYourOwnTopics: 'Gestalten Sie Ihre eigenen Themen und Fragen',
    proFeature: 'PRO',
    startReview: 'Start Rückblick',
    readMore: 'Mehr lesen',
    signUpToSaveProgress: 'Melden Sie sich an, um Ihren Fortschritt zu speichern und Erfolge freizuschalten',
    yourProgressMatters: 'Ihr Fortschritt zählt',
    preserveYourLearning: 'Bewahren Sie Ihren Lernweg und bauen Sie Ihr staatsbürgerliches Wissen weiter aus',
    getStarted: 'Los geht\'s',
    nothingNewToday: 'Heute nichts Neues? Perfekter Zeitpunkt zum Erkunden! 📚',
    keepGoing: 'Weitermachen! 🎯',
  },
};

export default uiStringsDE;
