import type { UIStrings } from './ui-strings';

export const uiStringsKO: UIStrings = {
  "navigation": {
    "back": "뒤로",
    "close": "닫기",
    "menu": "메뉴",
    "home": "홈",
    "topics": "주제",
    "learn": "탐색",
    "profile": "프로필",
    "settings": "설정",
    "bookmarks": "북마크",
    "history": "역사",
    "signInToPlay": "로그인하여 플레이하기",
    "signInToSaveProgress": "로그인하여 진행 상황 저장"
  },
  "topic": {
    "loading": "주제 세부 정보 로드 중...",
    "loadingDetails": "세부 정보 로드 중...",
    "backToTopics": "주제로 돌아가기",
    "share": "주제 공유",
    "bookmark": "북마크에 추가",
    "removeBookmark": "북마크 제거",
    "bookmarkThis": "북마크에 추가",
    "translateThisPage": "이 페이지 번역하기",
    "showOriginal": "원본 보기",
    "whyThisMatters": "이것이 중요한 이유",
    "sourcesAndReferences": "출처 및 참고 자료",
    "takingTheQuiz": "퀴즈 풀기",
    "startQuiz": "퀴즈 풀기",
    "questionsLabel": "질문",
    "estimatedMinutesLabel": "Est. Min.",
    "ratingLabel": "평가",
    "publishedLabel": "게시됨",
    "levelLabel": "레벨",
    "difficultyLabel": "난이도",
    "questionsCount": "총 질문",
    "estimatedTime": "예상 시간",
    "level": "레벨",
    "difficulty": "난이도",
    "easy": "쉬운",
    "medium": "Medium",
    "hard": "하드",
    "beginner": "초급",
    "intermediate": "중급",
    "advanced": "고급",
    "thinkYouGotIt": "이해했다고 생각하세요?",
    "testYourUnderstanding": "이 주제에 대한 이해도를 테스트하고 지금까지 다룬 핵심 개념을 얼마나 잘 이해하고 있는지 확인해 보세요.",
    "noSourcesAvailable": "아직 사용할 수 있는 소스가 없습니다",
    "noSourcesDescription": "콘텐츠가 검토되고 확인되면 출처와 참고 자료가 추가됩니다.",
    "understandingSourceAnalysis": "소스 분석 이해",
    "biasRatingsMeaning": "편향성 등급은 무엇을 의미하나요?",
    "credibilityPercentageMeaning": "신뢰도 비율은 무엇을 의미하나요?",
    "howRatingsDetermined": "등급은 어떻게 결정되나요?",
    "areRatingsPermanent": "이러한 등급은 영구적인가요?",
    "sourceAnalysisImportance": "이것이 왜 중요한가요?",
    "ratingsAndReviews": "평가 및 리뷰",
    "communityFeedback": "커뮤니티 피드백",
    "communityReviews": "커뮤니티 리뷰",
    "rateThisTopic": "이 주제 평가하기",
    "howHelpfulWasThis": "얼마나 도움이 되었나요?",
    "noRatingsYet": "아직 평가가 없습니다",
    "recentReviews": "최근 리뷰",
    "noReviewsYet": "아직 리뷰가 없습니다",
    "noReviewsDescription": "이 주제에 대한 여러분의 생각을 가장 먼저 공유해 주세요.",
    "writeFirstReview": "첫 리뷰 작성하기",
    "viewAllReviews": "모든 리뷰 보기",
    "editRating": "평점 편집",
    "ratingBreakdown": "등급 분석",
    "shareYourThoughts": "여러분의 생각을 공유하세요...",
    "completeQuizToReview": "퀴즈를 완료하여 검토하기",
    "takeQuizToShare": "퀴즈를 풀고 공유하기",
    "wasThisHelpful": "도움이 되었나요?",
    "writeAReview": "리뷰 작성",
    "rateAndReview": "평가 및 리뷰",
    "selectRating": "등급 선택",
    "submitReview": "리뷰 제출",
    "shareYourThoughtsDesc": "이 주제에 대한 여러분의 생각을 공유하세요",
    "yourReview": "귀하의 리뷰",
    "recently": "최근",
    "excellent": "우수",
    "veryGood": "매우 좋음",
    "good": "Good",
    "fair": "공정",
    "poor": "Poor",
    "checkingProgress": "진행 상황 확인",
    "loadingReviews": "리뷰 로드 중",
    "submittingReview": "리뷰 제출하기",
    "reviewSubmitted": "검토 제출됨",
    "thankYouForReview": "검토해 주셔서 감사합니다!",
    "helpful": "유용한 정보",
    "notHelpful": "도움이 되지 않음",
    "markAsHelpful": "도움이 됨으로 표시",
    "markAsNotHelpful": "도움이 되지 않음으로 표시",
    "completeToReview": "퀴즈를 완료하여 검토하기",
    "takeQuizFirst": "먼저 퀴즈 풀기",
    "finishTopicToReview": "검토할 주제 완료"
  },
  "translation": {
    "selectLanguage": "언어 선택",
    "languagePreferenceSaved": "향후 방문을 위해 언어 기본 설정이 저장됩니다",
    "translating": "번역...",
    "translationComplete": "번역 완료",
    "translationError": "번역 오류",
    "helpTranslate": "이 번역을 도와주세요",
    "noTranslationAvailable": "번역할 수 없음",
    "loadingTranslations": "번역 로드 중...",
    "checkingTranslations": "기존 번역 확인 중...",
    "savingTranslations": "번역 저장하기...",
    "autoTranslating": "자동 번역...",
    "translatingQuestion": "번역 질문",
    "originalText": "원본",
    "loadingExistingTranslations": "기존 번역 로드 중...",
    "translateContent": "콘텐츠 번역",
    "allQuestionsTranslated": "이미 번역된 모든 질문",
    "translationNeeded": "번역 필요",
    "helpTranslateContent": "번역을 돕고 싶으신가요?",
    "translationTest": "번역 테스트",
    "translationTestResult": "번역 테스트 결과",
    "translationTestFailed": "번역 테스트 실패",
    "initializingTranslationService": "번역 서비스 초기화 중...",
    "translated": "번역됨",
    "original": "원본",
    "availableTranslations": "사용 가능한 번역",
    "fullyTranslated": "완전 번역",
    "helpTranslateDescription": "더 많은 언어로 CivicSense에 액세스할 수 있도록 도와주세요",
    "contributeTranslation": "이 번역을 도와주세요",
    "contributeTitle": "CivicSense 번역 지원",
    "contributeMessage": "번역을 제공하여 더 많은 사람들이 CivicSense를 이용할 수 있도록 돕고 싶으신가요?",
    "getStarted": "시작하기",
    "thankYou": "감사합니다!",
    "contactInstructions": "번역 기여를 시작하려면 translate@civicsense.com 으로 문의하세요.",
    "dontSeeLanguage": "해당 언어가 보이지 않나요?",
    "requestLanguage": "새로운 언어를 요청하거나 번역을 도와줄 자원 봉사자를 요청하세요",
    "analyzingContent": "콘텐츠 분석...",
    "translatingToLanguage": "장소 홀더_0__로 번역...",
    "optimizingLayout": "레이아웃 최적화...",
    "elementsTranslated": "{{count}} 요소 번역됨"
  },
  "sources": {
    "analysisOverview": "분석 개요",
    "politicalBias": "정치적 편향성",
    "factualRating": "사실 평가",
    "transparency": "투명성",
    "analysisSummary": "분석 요약",
    "topicRelevanceCheck": "주제 관련성 확인",
    "validationDetails": "유효성 검사 세부 정보",
    "strengths": "강점",
    "areasForImprovement": "개선이 필요한 영역",
    "redFlags": "위험 신호",
    "recommendations": "권장 사항",
    "readFullArticle": "전체 기사 읽기",
    "loadingAnalysis": "분석 로드 중...",
    "analyzed": "분석",
    "credibility": "신뢰성"
  },
  "languages": {
    "english": "영어",
    "spanish": "영어",
    "chinese": "중국어",
    "vietnamese": "베트남어",
    "arabic": "아랍어",
    "hindi": "हिन्दी",
    "french": "프랑스어",
    "german": "독일어",
    "portuguese": "포르투갈어",
    "russian": "러시아어",
    "japanese": "일본어",
    "korean": "한국어",
    "italian": "이탈리아어"
  },
  "actions": {
    "save": "저장",
    "cancel": "취소",
    "delete": "삭제",
    "edit": "편집",
    "share": "공유",
    "copy": "복사",
    "download": "다운로드",
    "upload": "업로드",
    "refresh": "새로 고침",
    "retry": "다시 시도",
    "tryAgain": "다시 시도",
    "continue": "계속하기",
    "next": "다음",
    "previous": "이전 게시물",
    "finish": "완료",
    "submit": "제출하기",
    "confirm": "확인",
    "yes": "예",
    "no": "아니요",
    "ok": "확인",
    "dismiss": "해지"
  },
  "status": {
    "loading": "로드 중...",
    "saving": "저장...",
    "saved": "저장됨",
    "error": "오류",
    "success": "성공",
    "warning": "경고",
    "info": "정보",
    "completed": "완료",
    "failed": "실패",
    "connecting": "연결 중...",
    "connected": "연결됨",
    "disconnected": "연결 해제",
    "offline": "오프라인",
    "online": "온라인",
    "syncing": "동기화...",
    "synced": "동기화"
  },
  "errors": {
    "networkError": "네트워크 오류입니다. 연결을 확인해 주세요.",
    "serverError": "서버 오류가 발생했습니다. 나중에 다시 시도하세요.",
    "unknownError": "알 수 없는 오류가 발생했습니다.",
    "notFound": "콘텐츠를 찾을 수 없습니다.",
    "unauthorized": "이 콘텐츠에 액세스할 수 있는 권한이 없습니다.",
    "forbidden": "이 콘텐츠에 대한 접근은 금지되어 있습니다.",
    "timeout": "요청 시간이 초과되었습니다. 다시 시도해 주세요.",
    "connectionLost": "연결이 끊어졌습니다. 인터넷을 확인해 주세요.",
    "invalidInput": "잘못된 입력입니다. 입력 내용을 확인해 주세요.",
    "requiredField": "이 필드는 필수 입력 사항입니다.",
    "loadingFailed": "콘텐츠를 로드하지 못했습니다.",
    "savingFailed": "변경 사항을 저장하지 못했습니다.",
    "uploadFailed": "업로드에 실패했습니다.",
    "downloadFailed": "다운로드에 실패했습니다."
  },
  "time": {
    "now": "지금",
    "today": "오늘",
    "yesterday": "어제",
    "tomorrow": "내일",
    "thisWeek": "이번 주",
    "lastWeek": "지난 주",
    "thisMonth": "이번 달",
    "lastMonth": "지난 달",
    "minutesAgo": "몇 분 전",
    "hoursAgo": "몇 시간 전",
    "daysAgo": "며칠 전",
    "weeksAgo": "몇 주 전",
    "monthsAgo": "몇 달 전"
  },
  "quiz": {
    "question": "질문",
    "questions": "질문",
    "answer": "답변",
    "answers": "답변",
    "correct": "정답",
    "incorrect": "잘못됨",
    "explanation": "설명",
    "hint": "힌트",
    "score": "점수",
    "results": "결과",
    "startQuiz": "퀴즈 시작",
    "nextQuestion": "다음 질문",
    "previousQuestion": "이전 질문",
    "finishQuiz": "퀴즈 완료",
    "retakeQuiz": "퀴즈 다시 보기",
    "reviewAnswers": "답변 검토",
    "timeRemaining": "남은 시간",
    "questionNumber": "질문",
    "totalQuestions": "총 질문",
    "correctAnswers": "정답",
    "incorrectAnswers": "오답",
    "finalScore": "최종 점수",
    "complete": "퀴즈 완료!",
    "of": "의",
    "title": "퀴즈",
    "loadingQuestion": "질문 로드 중...",
    "unsupportedQuestionType": "지원되지 않는 문제 유형",
    "questionsComplete": "질문 완료",
    "timeUp": "시간 다 됐어요!",
    "pauseQuiz": "일시 정지 퀴즈",
    "resumeQuiz": "이력서 퀴즈",
    "exitQuiz": "종료 퀴즈",
    "saveProgress": "진행 상황 저장",
    "restoreProgress": "복원 진행 상황",
    "quizMode": "패션 퀴즈",
    "practiceMode": "연습 모드",
    "testMode": "테스트 모드",
    "selectAnswer": "답변 선택",
    "submitAnswer": "답변 제출",
    "showExplanation": "설명 표시",
    "hideExplanation": "설명 숨기기",
    "yourAnswer": "귀하의 답변",
    "correctAnswer": "정답",
    "continueToNext": "다음으로 계속",
    "questionTypes": {
      "multipleChoice": "객관식",
      "trueFalse": "참/거짓",
      "shortAnswer": "짧은 답변",
      "fillInBlank": "빈칸 채우기",
      "matching": "매칭",
      "ordering": "주문하기",
      "crossword": "크로스워드"
    },
    "multipleChoice": "객관식",
    "trueFalse": "참/거짓",
    "shortAnswer": "짧은 답변",
    "fillInBlank": "빈칸 채우기",
    "matching": "매칭",
    "ordering": "주문하기",
    "crossword": "크로스워드",
    "accuracy": "정확성",
    "timeSpent": "소요 시간",
    "averageTime": "평균 시간",
    "breakdown": "분석",
    "recommendations": "권장 사항",
    "questionsAnswered": "질문에 대한 답변",
    "questionsSkipped": "질문 건너뛰기",
    "percentageScore": "백분율 점수",
    "passingScore": "합격 점수",
    "passed": "합격",
    "failed": "실패",
    "tryAgain": "다시 시도",
    "viewReview": "리뷰 보기",
    "backToTopics": "주제로 돌아가기",
    "difficulty": {
      "easy": "쉬운",
      "medium": "Medium",
      "hard": "하드"
    }
  },
  "common": {
    "loading": "로드 중...",
    "error": "오류",
    "success": "성공",
    "cancel": "취소",
    "confirm": "확인",
    "save": "저장",
    "delete": "삭제",
    "edit": "편집",
    "done": "완료",
    "close": "닫기",
    "back": "뒤로",
    "next": "다음",
    "previous": "이전 게시물",
    "skip": "건너뛰기",
    "retry": "다시 시도"
  },
  "gameRoom": {
    "questionsPreview": "질문",
    "settings": "설정",
    "sources": "출처",
    "quizSettings": "퀴즈 설정",
    "showHints": "힌트 표시",
    "getHelpfulClues": "막혔을 때 유용한 단서 얻기",
    "showExplanations": "설명 표시",
    "learnWhyAnswersCorrect": "정답 또는 오답의 이유 알아보기",
    "hardMode": "하드 모드",
    "hardModeDescription": "힌트/설명 없음, 15초/질문",
    "timeLimit": "시간 제한",
    "noTimeLimit": "시간 제한 없음",
    "estimatedTime": "예상 시간",
    "questionsAvailable": "사용 가능한 질문",
    "getReady": "지식 테스트 준비하기",
    "trustedSources": "이 콘텐츠의 신뢰할 수 있는 출처",
    "credibilityStandards": "모든 출처는 신뢰성 기준을 충족합니다"
  },
  "onboarding": {
    "welcome": "시빅센스에 오신 것을 환영합니다!",
    "welcomeTitle": "시빅센스에 오신 것을 환영합니다",
    "welcomeSubtitle": "개인화된 시민 학습 경험을 준비해 드립니다",
    "getStarted": "시작하기",
    "skip": "건너뛰기",
    "exploreOnOwn": "혼자서 탐색하겠습니다",
    "timeToComplete": "완료하는 데 5~10분 소요",
    "personalizedLearning": "개인 맞춤형 학습",
    "personalizedLearningDesc": "관심사에 따른 맞춤형 퀴즈",
    "communityLearning": "커뮤니티 학습",
    "communityLearningDesc": "커뮤니티의 다른 사람들과 함께 배우기",
    "trackProgress": "진행 상황 추적",
    "trackProgressDesc": "시간이 지남에 따라 증가하는 시민 지식 확인",
    "learnTogether": "함께 학습하기",
    "learnTogetherDesc": "멀티플레이어 퀴즈에서 친구에게 도전하기",
    "earnAchievements": "업적 획득",
    "earnAchievementsDesc": "주제를 마스터하면서 배지 잠금 해제",
    "personalizeExperience": "개인화된 경험",
    "personalizeExperienceDesc": "학습 여정 맞춤 설정",
    "learningStyle": "학습 스타일",
    "learningStyleDesc": "어떤 방식으로 학습하는 것을 선호하시나요?",
    "visual": "시각적",
    "visualDesc": "이미지와 다이어그램을 통해 알아보기",
    "reading": "읽기",
    "readingDesc": "텍스트와 기사를 통해 학습하기",
    "mixed": "혼합",
    "mixedDesc": "시각적 학습과 텍스트 학습의 결합",
    "difficultyLevel": "난이도",
    "difficultyLevelDesc": "시작 난이도 선택",
    "beginner": "초급",
    "beginnerDesc": "시민 주제를 처음 접하는 분",
    "intermediate": "중급",
    "intermediateDesc": "시민 지식",
    "adaptive": "적응형",
    "adaptiveDesc": "학습에 따라 난이도 조절",
    "location": "위치",
    "locationOptional": "위치(선택 사항)",
    "city": "도시",
    "state": "상태",
    "zipCode": "우편 번호",
    "dailyReminders": "일일 알림",
    "dailyRemindersDesc": "새 콘텐츠에 대한 알림 받기",
    "whatsNext": "다음 단계는 무엇인가요?",
    "whatsNextDesc": "시민 학습 여정을 시작하세요",
    "completeSetup": "설정 완료",
    "invalidZipCode": "잘못된 우편 번호",
    "invalidZipCodeDesc": "유효한 5자리 우편번호를 입력하세요",
    "invalidState": "유효하지 않은 상태",
    "invalidStateDesc": "유효한 주를 입력하세요",
    "invalidCity": "유효하지 않은 도시",
    "invalidCityDesc": "유효한 도시 이름을 입력하세요",
    "zipCodePlaceholder": "우편 번호 입력",
    "cityPlaceholder": "도시 입력",
    "statePlaceholder": "상태 입력",
    "stateLocationDesc": "귀하의 주에서는 관련 지역 콘텐츠를 표시하는 데 도움을 줍니다",
    "cityLocationDesc": "귀하의 도시는 시민 정보를 맞춤화하는 데 도움을 줍니다",
    "zipCodeLocationDesc": "우편 번호는 현지 담당자를 찾는 데 도움이 됩니다",
    "categorySelectionTitle": "관심 분야 선택",
    "categorySelectionDesc": "배우고 싶은 주제를 선택하세요",
    "chooseTopics": "주제 선택",
    "selectInterests": "관심 분야 선택",
    "categoryLoading": "카테고리 로드 중...",
    "categoryLoadingError": "카테고리를 로드하지 못했습니다",
    "questionsAvailable": "사용 가능한 질문",
    "atLeastOneCategory": "카테고리를 하나 이상 선택해 주세요",
    "fallbackCategoryDesc": "다양한 시민 주제 살펴보기",
    "step": "단계",
    "choosePlayStyle": "플레이 스타일 선택",
    "setChallenge": "세트 챌린지",
    "customize": "사용자 지정",
    "soloChallenge": "솔로 챌린지",
    "soloChallengeDescription": "개별적으로 지식 테스트",
    "orUseCustomSettings": "또는 사용자 지정 설정을 사용하세요"
  },
  "multiplayer": {
    "title": "멀티플레이어",
    "connectionError": "연결 오류",
    "failedToJoin": "회의에 참여하지 못했습니다. 다시 시도해 주세요.",
    "failedToStart": "게임을 시작하지 못했습니다. 다시 시도해 주세요.",
    "leaveRoomConfirm": "정말 이 방을 나가시겠어요?",
    "inviteMessage": "시빅센스 퀴즈방에 참여하세요! Code: __placeholder_0__\n\n앱을 다운로드하고 이 코드를 입력하여 함께 플레이하세요.",
    "inviteTitle": "시빅센스 퀴즈방에 참여하세요!",
    "aiPlayer": "AI 플레이어",
    "humanPlayer": "인간 플레이어",
    "sharingFailed": "공유하지 못했습니다. 다시 시도하세요.",
    "getReadyToPlay": "플레이 준비하기",
    "startReview": "검토 시작",
    "waitingForPlayers": "플레이어 대기 중",
    "waitingForHost": "호스트 대기 중",
    "gameMode": "게임 모드",
    "questions": "질문",
    "features": "특징",
    "hints": "힌트",
    "explanations": "설명",
    "teamMode": "팀 패션",
    "powerUps": "파워 업",
    "npcBattle": "NPC 전투",
    "testYourKnowledge": "지식 테스트",
    "skillLevel": "기술 수준",
    "roomCode": "객실 코드",
    "maxPlayers": "최대 플레이어 수",
    "currentPlayers": "현재 플레이어",
    "leaderboard": "리더보드",
    "chat": "채팅",
    "settings": "설정",
    "gameStartingSoon": "곧 게임 시작",
    "getReadyFirstQuestion": "첫 번째 질문 준비하기",
    "battleStarting": "전투 시작",
    "firstQuestionLoading": "첫 번째 질문 로드 중",
    "question": "질문",
    "questionNumber": "질문",
    "hint": "힌트",
    "showHint": "힌트 표시",
    "submitAnswer": "답변 제출",
    "explanation": "설명",
    "shield": "Shield",
    "attack": "공격",
    "focus": "초점",
    "correct": "정답",
    "incorrect": "잘못됨",
    "timeUp": "시간 다 됐어요!",
    "finalScore": "최종 점수",
    "gameComplete": "게임 완료",
    "greatJobLearning": "잘 배웠습니다!",
    "shareResults": "결과 공유",
    "continue": "계속하기",
    "victory": "승리!",
    "goodTry": "좋은 시도였습니다!",
    "correctAnswers": "정답",
    "accuracy": "정확성",
    "playAgain": "다시 플레이",
    "exit": "종료",
    "ready": "준비",
    "notReady": "준비되지 않음",
    "thinking": "사고력",
    "answered": "답변됨",
    "roomChat": "룸 채팅",
    "players": "플레이어",
    "typeMessage": "메시지 유형",
    "enterToSend": "보내려면 입력",
    "beRespectful": "존중하기",
    "playerJoined": "플레이어 가입",
    "playerLeft": "왼쪽 플레이어",
    "gameStarting": "게임 시작",
    "welcomeToQuiz": "퀴즈에 오신 것을 환영합니다",
    "allowNewPlayers": "신규 플레이어 허용",
    "allowNewPlayersDesc": "신규 플레이어의 게임 참여 허용",
    "enableBoosts": "부스트 활성화",
    "enableBoostsDesc": "플레이어를 위한 파워업 활성화",
    "showHints": "힌트 표시",
    "showHintsDesc": "플레이어에게 힌트 표시",
    "autoAdvance": "자동 사전 예약",
    "autoAdvanceDesc": "자동으로 질문 진행",
    "realTimeScores": "실시간 점수",
    "realTimeScoresDesc": "실시간 점수 표시",
    "enableChat": "채팅 사용",
    "enableChatDesc": "플레이어를 위한 채팅 활성화",
    "connectionLost": "연결 끊김",
    "failedToSubmitAnswer": "답변 제출 실패",
    "networkError": "네트워크 오류",
    "ai": "AI",
    "host": "호스트",
    "titleDescription": "설명",
    "liveGameScreen": "라이브 게임"
  },
  "analytics": {
    "loadingInsights": "인사이트 로드 중...",
    "couldNotLoadInsights": "학습 인사이트를 로드할 수 없습니다. 다시 시도해 주세요.",
    "couldNotRefreshInsights": "인사이트를 새로 고칠 수 없습니다. 다시 시도하세요.",
    "excellentPerformance": "뛰어난 성능! 맞춤화된 다음 단계를 확인하세요.",
    "goodProgress": "잘 진행되고 있습니다! 개선할 부분을 찾아보세요.",
    "keepLearning": "계속 학습하세요! 맞춤형 학습 팁을 확인하세요.",
    "needHelp": "문제가 있으신가요? 맞춤화된 도움을 받으세요."
  },
  "news": {
    "dailyNews": "데일리 뉴스",
    "latestNews": "최신 뉴스",
    "articles": "기사",
    "fetchingFrom": "AP, Reuters, NPR, BBC, Politico에서 가져옴...",
    "noValidArticles": "필터링 후 유효한 문서를 찾을 수 없습니다",
    "failedToLoad": "뉴스를 로드하지 못했습니다",
    "newsAPI": "뉴스 API 실패",
    "unknownError": "알 수 없는 오류",
    "refreshNews": "뉴스 새로 고침",
    "updating": "업데이트 중...",
    "today": "오늘",
    "yesterday": "어제",
    "breakingNews": "뉴스 속보",
    "newsUpdates": "뉴스 업데이트",
    "readMore": "자세히 보기",
    "readFull": "전체 기사 읽기",
    "source": "출처",
    "publishedBy": "게시자",
    "lastUpdated": "마지막 업데이트",
    "originalSource": "원본 소스",
    "previousArticle": "이전 기사",
    "nextArticle": "다음 글",
    "backToNews": "뉴스로 돌아가기",
    "filterByCategory": "카테고리별 필터링",
    "sortBy": "정렬 기준",
    "newest": "최신",
    "oldest": "가장 오래된",
    "mostRelevant": "가장 관련성 높음",
    "noArticlesFound": "기사를 찾을 수 없습니다",
    "loadingFailed": "뉴스 기사를 로드하지 못했습니다",
    "tryAgainLater": "나중에 다시 시도하세요",
    "shareArticle": "기사 공유",
    "copyLink": "복사 링크",
    "linkCopied": "링크가 클립보드에 복사됨",
    "savedToDb": "dB에 저장",
    "ago": "전"
  },
  "collections": {
    "takeAction": "조치 취하기",
    "planned": "계획",
    "completed": "완료",
    "immediateActions": "즉각적인 조치",
    "immediateActionsDesc": "다음은 배운 내용을 적용하기 위해 지금 바로 취할 수 있는 구체적인 단계입니다.",
    "civicEngagementOpportunities": "시민 참여 기회",
    "civicEngagementDesc": "이러한 기회를 통해 커뮤니티와 소통하고 더 넓은 영향력을 발휘하세요.",
    "markAsCompleted": "완료된 것으로 표시",
    "yourActionPlan": "실행 계획",
    "youvePlannedActions": "플레이스홀더_0__ 액션__플레이스홀더_1__을 계획했습니다",
    "andCompleted": " 완료 {{count}}",
    "greatJobTakingAction": "시민 학습을 실천하는 데 수고하셨습니다! 🎉",
    "keepGoing": "계속하세요! 행동을 취하는 것이 민주주의를 강화하는 방법입니다.",
    "readyToTakeAction": "조치를 취할 준비가 되셨나요?",
    "checkOffActions": "계획하고 있는 행동에 체크하세요. 작은 한 걸음 한 걸음이 민주주의를 더 강하게 만듭니다.",
    "outstanding": "훌륭합니다!",
    "completedAllActions": "제안된 모든 활동을 완료하셨습니다. 커뮤니티에 진정한 변화를 일으키고 계십니다!",
    "quickCheck": "빠른 확인",
    "complete": "완료",
    "submitAnswer": "답변 제출",
    "correct": "정답!",
    "notQuiteRight": "옳지 않음",
    "showHint": "힌트 표시",
    "hideHint": "인도어 숨기기",
    "selectAnAnswer": "답변 선택",
    "answerSelected": "선택한 답변",
    "trueOrFalse": "참 또는 거짓?",
    "selectTrueFalse": "참 또는 거짓을 선택합니다",
    "yourResponse": "귀하의 응답",
    "enterYourAnswer": "답변을 입력하세요...",
    "submitResponse": "응답 제출",
    "responseRecorded": "응답 기록",
    "thankYouForInput": "의견을 보내주셔서 감사합니다. 답변이 저장되었습니다.",
    "enterYourResponse": "응답 입력",
    "charactersCount": "{{count}} 문자",
    "rankingExercise": "랭킹 연습",
    "dragToReorder": "항목을 드래그하여 가장 중요한 항목부터 가장 중요하지 않은 항목 순으로 순서를 변경할 수 있습니다:",
    "rankingComplete": "랭킹 완료",
    "dragToReorderItems": "드래그하여 항목 재정렬",
    "rankingExplanation": "순위 설명",
    "interactiveTimeline": "대화형 타임라인",
    "clickEachEvent": "탐색하려면 각 이벤트를 클릭합니다({현재}/{총계})",
    "exploreAllEvents": "모든 이벤트 살펴보기",
    "reflection": "반사",
    "reflectionPrompts": "반사 프롬프트",
    "shareYourThoughts": "여러분의 생각을 공유하세요...",
    "saveReflection": "반사 저장",
    "actionChecklist": "조치 체크리스트",
    "actionsCompleted": "완료된 {총} 작업 중 {완료된} 작업 수",
    "primaryAction": "주요 조치",
    "bonusActions": "보너스 액션(선택 사항)",
    "helpfulResources": "유용한 리소스",
    "markAsComplete": "완료로 표시",
    "actionComplete": "작업 완료",
    "takeActionStatus": "조치 취하기",
    "pending": "보류 중",
    "contactRepresentatives": "담당자에게 문의",
    "contactsReached": "{총} 연락처 중 {연결된} 연락처에 도달했습니다",
    "whoToContact": "문의처",
    "messageTemplates": "메시지 템플릿",
    "sendWithTemplate": "템플릿으로 보내기",
    "visitWebsite": "웹사이트 방문 →",
    "alreadyContacted": "이미 연락했습니다",
    "markAsContacted": "연락처로 표시",
    "quickPoll": "빠른 투표",
    "castVote": "투표하기",
    "thanksForVoting": "투표해 주셔서 감사합니다!",
    "results": "결과:",
    "votes": "투표",
    "surveyTitle": "설문 조사",
    "questionProgress": "질문 {현재}의 {총계}",
    "simulationResults": "시뮬레이션 결과",
    "yourAnswer": "귀하의 답변...",
    "previous": "이전 게시물",
    "next": "다음",
    "completeSurvey": "설문조사 완료",
    "externalSurveyDesc": "이 설문조사는 외부에서 진행됩니다. 참여하려면 아래 링크를 클릭하세요.",
    "openSurvey": "설문조사 열기",
    "opinionScale": "의견 척도",
    "moveSlider": "슬라이더를 움직여 동의 수준을 표시합니다",
    "submitOpinion": "의견 제출",
    "thanksForOpinion": "의견을 공유해 주셔서 감사합니다!",
    "stronglyDisagree": "강력히 동의하지 않음",
    "disagree": "동의하지 않음",
    "neutral": "중립",
    "agree": "동의",
    "stronglyAgree": "적극 동의",
    "policySimulation": "정책 시뮬레이션",
    "scenario": "시나리오",
    "adjustVariables": "변수 조정",
    "runSimulation": "시뮬레이션 실행",
    "rolePlayingExercise": "역할 놀이 연습",
    "chooseYourRole": "역할 선택",
    "objectives": "목표:",
    "whatActionTake": "이번 라운드에서는 어떤 조치를 취하시나요?",
    "negotiateStakeholders": "다른 이해관계자와의 협상",
    "gatherMoreInfo": "자세한 정보 수집",
    "rolePlayComplete": "역할 놀이 완료!",
    "yourDecisions": "사용자의 결정",
    "decisionPath": "의사 결정 경로",
    "decisionPoint": "의사 결정 포인트",
    "chooseResponse": "응답을 선택합니다:",
    "finalOutcome": "최종 결과",
    "reflectionNote": "다른 선택이 어떻게 다른 결과를 가져왔는지 생각해 보세요. 실제 정책 결정에는 즉각적으로 드러나지 않는 복잡한 결과가 따르는 경우가 많습니다.",
    "tryDifferentPath": "다른 경로 시도",
    "yourPath": "당신의 길:",
    "compareAndContrast": "비교 및 대조",
    "continueLearning": "계속 학습하기",
    "viewAllCards": "모든 카드 보기",
    "nextCard": "다음 카드",
    "previousCard": "이전 게시물",
    "exploreImage": "이미지 살펴보기",
    "dragAndDrop": "드래그 앤 드롭",
    "availableItems": "사용 가능한 항목",
    "interactiveMap": "대화형 지도",
    "checkAnswers": "답변 확인",
    "allItemsAssigned": "할당된 모든 항목",
    "assigned": "할당",
    "adjustParameters": "매개변수 조정",
    "viewResults": "결과 보기",
    "resetSimulation": "시뮬레이션 초기화",
    "fillInTheBlanks": "빈칸 채우기",
    "matchingPairs": "쌍 매칭",
    "categorizeItems": "항목 분류",
    "progressUpdate": "진행 상황 업데이트",
    "wellDone": "잘했어!",
    "goodEffort": "수고하셨습니다!",
    "keepTrying": "계속 시도해 보세요!",
    "perfect": "완벽해요!",
    "almostThere": "거의 다 왔습니다!"
  },
  "accessibility": {
    "skipToContent": "콘텐츠로 건너뛰기",
    "mainNavigation": "주요 탐색",
    "userMenu": "사용자 메뉴",
    "darkModeToggle": "다크 모드 전환",
    "languageSelector": "언어 선택",
    "closeDialog": "대화 닫기",
    "openMenu": "메뉴 열기",
    "closeMenu": "메뉴 닫기",
    "loadingContent": "콘텐츠 로드 중",
    "expandSection": "섹션 확장",
    "collapseSection": "섹션 축소",
    "playAudio": "오디오 재생",
    "pauseAudio": "오디오 일시 중지",
    "stopAudio": "오디오 중지",
    "increaseSpeed": "속도 향상",
    "decreaseSpeed": "속도 감소",
    "goBack": "뒤로 가기",
    "openLink": "링크 열기",
    "bookmark": "이 주제를 북마크에 추가하세요",
    "removeBookmark": "북마크 제거"
  },
  "settings": {
    "title": "설정",
    "account": "계정",
    "preferences": "기본 설정",
    "notifications": "알림",
    "privacy": "개인 정보 보호",
    "accessibility": "접근성",
    "language": "언어",
    "theme": "테마",
    "themes": {
      "light": "빛",
      "dark": "Dark",
      "system": "시스템"
    },
    "email": "이메일",
    "password": "비밀번호",
    "changePassword": "비밀번호 변경",
    "deleteAccount": "계정 삭제",
    "exportData": "데이터 내보내기",
    "saveChanges": "변경 사항 저장",
    "saved": "설정 저장",
    "emailNotifications": "이메일 알림",
    "pushNotifications": "푸시 알림",
    "weeklyDigest": "위클리 다이제스트",
    "achievementAlerts": "업적 알림",
    "soundEffects": "음향 효과",
    "animations": "애니메이션",
    "highContrast": "높은 명암비",
    "largeText": "큰 텍스트",
    "reducedMotion": "동작 감소",
    "keyboardShortcuts": "키보드 단축키",
    "timezone": "시간대",
    "dateFormat": "날짜 형식",
    "giftCredits": "기프트 크레딧",
    "premium": "프리미엄",
    "subscription": "구독",
    "features": "특징",
    "upgrade": "업그레이드",
    "manage": "관리",
    "cancel": "취소",
    "signOut": "로그아웃",
    "accountData": "계정 데이터",
    "displayName": "표시 이름",
    "currentPassword": "현재 비밀번호",
    "newPassword": "새 비밀번호",
    "confirmPassword": "비밀번호 확인",
    "updateAccount": "계정 업데이트",
    "pleaseSignIn": "설정에 액세스하려면 로그인하세요",
    "signInToAccess": "설정에 액세스하려면 로그인하세요",
    "editProfile": "프로필 수정",
    "fullName": "전체 이름",
    "fullNameRequired": "성명은 필수 입력 사항입니다",
    "bio": "바이오",
    "location": "위치",
    "website": "웹사이트",
    "country": "국가",
    "stateProvince": "주/시/도",
    "city": "도시",
    "profileUpdated": "프로필 업데이트! ✅",
    "profileUpdatedMessage": "변경 사항이 성공적으로 저장되었습니다.",
    "great": "좋아요!",
    "discardChanges": "변경 사항을 삭제하시겠습니까?",
    "discardChangesMessage": "저장하지 않은 변경 내용이 있습니다. 정말 삭제하시겠습니까?",
    "keepEditing": "계속 편집",
    "discard": "폐기",
    "permissionRequired": "필요한 권한",
    "photoLibraryPermission": "아바타를 변경하려면 사진 라이브러리에 대한 액세스를 허용하세요.",
    "uploadFailed": "아바타 업로드에 실패했습니다. 다시 시도하세요.",
    "autoTranslateContent": "콘텐츠 자동 번역",
    "autoTranslateContentDesc": "퀴즈 문제 및 강의 자동 번역",
    "preserveCivicTerms": "시민 용어 보존",
    "preserveCivicTermsDesc": "중요한 시민 용어를 번역에서 정확하게 유지하세요",
    "clearTranslationCache": "번역 캐시 지우기",
    "clearTranslationCacheDesc": "저장된 번역을 초기화하여 새로운 콘텐츠 얻기",
    "translationCacheCleared": "번역 캐시가 성공적으로 지워졌습니다",
    "translationCacheClearError": "번역 캐시를 지우지 못했습니다"
  },
  "survey": {
    "question": "질문",
    "questions": "질문",
    "required": "필수",
    "optional": "선택 사항",
    "progress": "진행 상황",
    "complete": "완료",
    "submit": "제출하기",
    "next": "다음",
    "previous": "이전 게시물",
    "skip": "건너뛰기",
    "save": "저장",
    "saveProgress": "진행 상황 저장",
    "loading": "로드 중...",
    "error": "오류",
    "success": "성공",
    "pleaseSelectOption": "옵션을 선택하세요",
    "pleaseProvideAnswer": "답변을 제공해 주세요",
    "invalidEmail": "유효한 이메일 주소를 입력하세요",
    "invalidPhone": "유효한 전화번호를 입력하세요",
    "tooManySelections": "선택 항목이 너무 많습니다",
    "maxSelections": "최대 선택 항목 도달",
    "selectAtLeast": "최소한 다음 중 하나를 선택하세요",
    "selectAtMost": "최대",
    "charactersRemaining": "남은 문자 수",
    "wordLimit": "단어 수 제한 초과",
    "fileUpload": "파일 업로드",
    "chooseFile": "파일 선택",
    "removeFile": "파일 제거",
    "uploadError": "업로드 실패",
    "stronglyDisagree": "강력히 동의하지 않음",
    "disagree": "동의하지 않음",
    "neutral": "중립",
    "agree": "동의",
    "stronglyAgree": "적극 동의",
    "pleaseSpecify": "지정해 주세요...",
    "other": "기타",
    "none": "없음",
    "all": "모두",
    "completed": "완료",
    "thankYou": "감사합니다!",
    "submissionComplete": "제출이 완료되었습니다",
    "viewResults": "결과 보기",
    "retake": "재응시",
    "share": "공유"
  },
  "audio": {
    "play": "플레이",
    "pause": "일시 중지",
    "stop": "중지",
    "resume": "이력서",
    "restart": "다시 시작",
    "mute": "음소거",
    "unmute": "음소거 해제",
    "volume": "볼륨",
    "speed": "속도",
    "voice": "음성",
    "settings": "설정",
    "audioControls": "오디오 컨트롤",
    "voiceSettings": "음성 설정",
    "quality": "품질",
    "high": "높음",
    "medium": "Medium",
    "low": "낮음",
    "autoPlay": "자동 재생",
    "loop": "Loop",
    "highlighting": "단어 강조 표시",
    "cloudTTS": "클라우드 TTS",
    "browserTTS": "브라우저 TTS",
    "language": "언어",
    "male": "남성",
    "female": "여성",
    "neutral": "중립",
    "loading": "로드 중...",
    "error": "오디오 오류",
    "notSupported": "오디오가 지원되지 않음",
    "recovery": "오디오 복구",
    "testAudio": "오디오 테스트",
    "readPage": "페이지 읽기",
    "readSelection": "선택 항목 읽기",
    "keyboardShortcuts": "키보드 단축키",
    "diagnostics": "진단",
    "usage": "사용법",
    "charactersUsed": "사용된 문자",
    "estimatedCost": "예상 비용",
    "voiceCount": "음성 수",
    "speaking": "말하기",
    "pending": "보류 중",
    "paused": "일시 중지됨",
    "lastUpdate": "최근 업데이트"
  },
  "profileScreenTitle": "내 프로필",
  "loadingProfile": "프로필 로드 중...",
  "redirectingToLogin": "로그인으로 리디렉션...",
  "leaderboard": {
    "title": "리더보드",
    "loadingLeaderboard": "리더보드 로드 중...",
    "yourRanking": "내 랭킹",
    "currentRank": "현재 순위",
    "topPercentile": "상위 백분위수",
    "totalUsers": "총 사용자 수",
    "today": "오늘",
    "thisWeek": "이번 주",
    "thisMonth": "이번 달",
    "allTime": "모든 시간",
    "score": "점수",
    "xp": "XP",
    "streak": "Streak",
    "quizzes": "퀴즈",
    "achievements": "성과",
    "you": "(귀하)",
    "takeQuizToClimb": "퀴즈를 풀고 등반하세요!",
    "new": "신규"
  },
  "search": {
    "title": "검색",
    "placeholder": "컬렉션 및 주제 검색...",
    "clearHistory": "검색 기록 지우기",
    "analytics": "{{count}} 검색한 항목 - {{viewed}} 조회한 항목",
    "streak": "플레이스홀더_0__ 일 연승",
    "loadingData": "검색 데이터 로드 중...",
    "searching": "컬렉션 및 주제 검색하기...",
    "keepTyping": "계속 입력하세요...",
    "minCharacters": "검색을 시작하려면 2자 이상 입력하세요",
    "filterAll": "모두",
    "filterCollections": "컬렉션",
    "filterTopics": "주제",
    "noResults": "결과를 찾을 수 없습니다",
    "noResultsHint": "\"헌법\", \"선거\" 또는 \"대법원\"과 같은 다양한 키워드로 검색해 보세요",
    "continueLearning": "계속 학습하기",
    "pickUpWhereLeft": "중단한 부분부터 다시 시작하기",
    "recommended": "추천",
    "recentSearches": "최근 검색",
    "clearAll": "모두 지우기",
    "popularTopics": "인기 주제",
    "tapToSearch": "빠르게 검색하려면 탭하세요",
    "searchTips": "검색 팁",
    "tip1": "\"수정 헌법 제1조\" 또는 \"선거인단\"과 같은 특정 주제를 사용해 보세요",
    "tip2": "최근에 본 항목이 결과에서 가장 먼저 표시됩니다",
    "tip3": "검색 기록은 더 나은 추천을 표시하는 데 도움이 됩니다",
    "collection": "컬렉션",
    "topic": "주제",
    "questionCount": "{{count}} 질문",
    "recent": "최근"
  },
  "profile": {
    "title": "내 프로필",
    "loadingProfile": "프로필 로드 중...",
    "redirectingToLogin": "로그인으로 리디렉션...",
    "yourProgress": "진행 상황",
    "calendarIntegration": "캘린더 통합",
    "googleCalendarSync": "Google 캘린더 동기화",
    "googleCalendarSyncDesc": "Google 캘린더와 학습 일정 동기화",
    "dailyQuizReminders": "일일 퀴즈 알림",
    "dailyQuizRemindersDesc": "매일 퀴즈 알림 받기",
    "smartScheduling": "스마트 스케줄링",
    "smartSchedulingDesc": "AI 기반 최적의 학습 시간",
    "learningPodSessions": "학습 포드 세션",
    "learningPodSessionsDesc": "그룹 스터디 세션 알림",
    "lastSynced": "마지막 동기화",
    "smartStudyRecommendations": "스마트 학습 권장 사항",
    "scheduleThisTime": "이 시간 예약하기",
    "learningPods": "학습 포드",
    "constitutionalLawStudyGroup": "헌법 연구 그룹",
    "membersOnline": "회원 - {{online}} 지금 온라인 상태",
    "billOfRightsReviewSession": "권리장전 검토 세션",
    "managePods": "파드 관리",
    "editProfile": "프로필 수정",
    "updateYourInformation": "정보 업데이트",
    "preferences": "기본 설정",
    "learningAndNotifications": "학습 및 알림",
    "exportLearningProgress": "학습 진행 상황 내보내기",
    "howWouldYouLikeToShare": "진행 상황을 어떻게 공유하시겠습니까?",
    "exportAsPDF": "PDF로 내보내기",
    "shareWithPod": "Pod와 공유",
    "generateReport": "CivicSense 분석 보고서 생성하기",
    "shareReport": "보고서 공유",
    "exportFailed": "내보내기 실패",
    "exportError": "학습 분석 보고서를 생성하지 못했습니다. 다시 시도해 주세요.",
    "updateProfilePhoto": "프로필 사진 업데이트",
    "choosePhotoMethod": "사진 추가 방법을 선택하세요",
    "camera": "카메라",
    "photoLibrary": "사진 라이브러리",
    "profilePhotoUpdated": "프로필 사진이 성공적으로 업데이트되었습니다!",
    "uploadPhotoFailed": "프로필 사진을 업로드하지 못했습니다",
    "profileCompletion": "프로필 {{percent}}% 완료",
    "profileCompletePercent": "프로필 {{percent}}% 완료",
    "quizzes": "퀴즈",
    "avgScore": "평균 점수",
    "dayStreak": "일 연속",
    "studyTime": "학습 시간",
    "achievements": "업적",
    "viewDetailedStats": "상세 통계 보기",
    "connectedViaGoogle": "Google을 통해 연결",
    "appVersion": "CivicSense v1.0.0 - 민주주의를 위해 ❤️ 제작",
    "madeWithLoveForDemocracy": "민주주의를 위해 ❤️ 제작"
  },
  "saved": {
    "title": "저장됨",
    "subtitle": "북마크 및 진행 상황",
    "loadingSavedContent": "저장된 콘텐츠를 로드 중...",
    "collections": "컬렉션",
    "createCollection": "만들기",
    "organizeYourLearning": "학습 정리",
    "organizeYourLearningDesc": "컬렉션을 만들어 저장된 콘텐츠를 테마별 폴더로 정리하면 더 쉽게 공부할 수 있습니다.",
    "lessons": "배운 교훈",
    "lessonsDesc": "CivicSense의 다단계 코스",
    "myCollections": "내 컬렉션",
    "myCollectionsDesc": "정리된 콘텐츠 폴더",
    "createYourFirstCollection": "첫 번째 컬렉션을 만들어 저장된 콘텐츠를 정리하세요",
    "filterContent": "콘텐츠 필터링",
    "allContent": "모두",
    "topics": "주제",
    "quizResults": "퀴즈 결과",
    "customQuizzes": "맞춤 퀴즈",
    "bookmarks": "북마크",
    "noSavedLessons": "저장된 레슨 없음",
    "noSavedTopics": "저장된 주제 없음",
    "noQuizResults": "퀴즈 결과 없음",
    "noBookmarks": "북마크 없음",
    "noSavedItems": "저장된 항목 없음",
    "exploreContent": "콘텐츠 탐색",
    "selectItems": "항목 선택",
    "itemsSelected": "플레이스홀더_0__ 항목__플레이스홀더_1__ 선택됨",
    "selectItemsToOrganize": "정리할 항목 선택",
    "organizeSelectedItems": "선택한 항목 정리",
    "moveToCollection": "컬렉션으로 이동",
    "removeItem": "항목 제거",
    "removeItemConfirm": "이 저장된 항목을 삭제하시겠습니까?",
    "highlightedText": "강조 표시된 텍스트",
    "textSnippet": "텍스트 스니펫",
    "customQuiz": "맞춤 퀴즈",
    "continueYourCivicsAssessment": "시민성 평가 계속하기",
    "questionsCompleted": "플레이스홀더_0__ 중 __플레이스홀더_1__ 질문 완료됨",
    "started": "시작 {{date}}",
    "scoreLabel": "점수",
    "xpEarned": "+__placeholder_0__ xp",
    "questions": "질문",
    "draft": "초안",
    "published": "게시됨",
    "savedRecently": "저장됨 {{time}}",
    "savedTime": "저장됨 {{time}} 전",
    "keepGoing": "계속하세요! 🎯",
    "nothingNewToday": "오늘 새로운 소식이 없나요? 탐험하기에 완벽한 시간입니다! 📚",
    "nothingNewTodayDesc": "위의 화살표를 사용하여 다른 날짜로 이동하거나 아래의 학습 옵션을 살펴보세요.",
    "currentEvents": "현재 이벤트",
    "currentEventsDesc": "스토리를 탭하여 해당 주제에 대한 퀴즈를 만들 수 있습니다",
    "findingCurrentEvents": "장소 홀더_0__...에 대한 현재 이벤트 찾기",
    "continueWhereLeftOff": "중단한 부분부터 계속 진행",
    "orExploreMore": "또는 자세히 알아보기",
    "continueLearning": "학습 계속하기",
    "exploreQuizTopics": "퀴즈 주제 살펴보기",
    "exploreQuizTopicsDesc": "정부, 권리, 시민 참여에 관한 퀴즈 알아보기",
    "takeCivicsAssessment": "시민 평가 응시",
    "takeCivicsAssessmentDesc": "미국 정부와 민주주의에 대한 지식을 테스트하세요",
    "reviewSavedContent": "저장된 콘텐츠 검토",
    "reviewSavedContentDesc": "북마크한 주제에서 계속 학습하기",
    "createCustomContent": "사용자 지정 콘텐츠 만들기",
    "createCustomContentDesc": "나만의 주제 및 질문 디자인하기",
    "pro": "PRO"
  },
  "learn": {
    "title": "학습",
    "loadingQuizCollections": "퀴즈 컬렉션 로드 중...",
    "usingOfflineData": "오프라인 퀴즈 데이터 사용 - 네트워크를 사용할 수 없음",
    "featuredLessons": "주요 레슨",
    "featuredLessonsDesc": "최신 주제에 대한 엄선된 강의 컬렉션",
    "allCollections": "모든 컬렉션",
    "allCollectionsDesc": "종합적인 시민 지식 테스트",
    "collections": "{{count}} 컬렉션",
    "topics": "주제",
    "topicsDesc": "타겟팅된 질문으로 개별 시민 주제를 탐색하세요",
    "noQuizCollections": "사용 가능한 퀴즈 컬렉션이 없습니다",
    "noQuizCollectionsOffline": "인터넷 연결을 확인하고 다시 시도하세요",
    "noQuizCollectionsOnline": "새 퀴즈 컬렉션은 사용 가능한 경우 여기에 표시됩니다",
    "quizDataSource": "퀴즈 데이터 소스: {{source}}",
    "liveAPI": "라이브 API",
    "offlineCache": "오프라인 캐시",
    "showingRealTimeData": "서버에서 실시간 퀴즈 컬렉션 표시하기",
    "usingCachedData": "캐시된 퀴즈 데이터 사용 - 일부 콘텐츠가 오래되었을 수 있습니다",
    "new": "신규",
    "featured": "추천",
    "estimatedTime": "{{time}} 분",
    "completionRate": "플레이스홀더_0__% 완료",
    "completion": "완료",
    "continue": "계속하기",
    "start": "시작",
    "available": "사용 가능",
    "difficulty": "난이도",
    "searchTopics": "주제 검색"
  },
  "home": {
    "welcomeBack": "돌아온 것을 환영합니다, {{name}}",
    "welcome": "시민 감각",
    "citizen": "시민",
    "loadingYourCivicJourney": "시민 여정을 로드 중...",
    "loadingContent": "콘텐츠 로드 중...",
    "today": "오늘",
    "dailyChallenge": "일일 챌린지({{completed}} 중 {{total}})",
    "questionsOf": "{{completed}}의 {{total}}",
    "dayStreak": "{{count}} day{{plural}}",
    "days": "일수",
    "day": "일",
    "loadingDate": "로드 중 {{date}}",
    "noFeaturedToday": "오늘 추천 토픽이 없습니다",
    "noFeaturedTodayDesc": "속보 및 주요 콘텐츠는 나중에 다시 확인하세요",
    "checkBackLater": "속보 및 주요 콘텐츠는 나중에 다시 확인하세요",
    "keepGoingTarget": "계속하세요! 🎯",
    "navigateToOtherDates": "위의 화살표를 사용하여 다른 날짜로 이동하거나 아래의 학습 옵션을 살펴보세요.",
    "exploreMoreOptions": "아래에서 이러한 학습 옵션을 살펴보세요",
    "todaysCurrentEvents": "오늘의 시사 뉴스",
    "currentEventsForDate": "{{date}} 현재 이벤트",
    "tapAnyStoryToCreate": "스토리를 탭하여 해당 주제에 대한 퀴즈를 만들 수 있습니다",
    "findingCurrentEventsFor": "장소 홀더_0__...에 대한 현재 이벤트 찾기",
    "exploreQuizTopics": "퀴즈 주제 살펴보기",
    "exploreQuizTopicsDesc": "정부, 권리, 시민 참여에 관한 퀴즈 알아보기",
    "takeCivicsAssessment": "시민 평가 응시",
    "takeCivicsAssessmentDesc": "미국 정부와 민주주의에 대한 지식을 테스트하세요",
    "reviewSavedContent": "저장된 콘텐츠 검토",
    "reviewSavedContentDesc": "북마크한 주제에서 계속 학습하기",
    "createCustomContent": "사용자 지정 콘텐츠 만들기",
    "createCustomContentDesc": "나만의 주제 및 질문 디자인하기",
    "designYourOwnTopics": "나만의 주제 및 질문 디자인하기",
    "proFeature": "PRO",
    "startReview": "검토 시작",
    "readMore": "자세히 보기",
    "signUpToSaveProgress": "가입하여 진행 상황을 저장하고 도전 과제를 잠금 해제하세요",
    "yourProgressMatters": "진행 상황이 중요합니다",
    "preserveYourLearning": "학습 여정을 보존하고 시민 지식을 계속 쌓아보세요",
    "getStarted": "시작하기",
    "nothingNewToday": "오늘 새로운 소식이 없나요? 탐험하기에 완벽한 시간입니다! 📚",
    "keepGoing": "계속하세요! 🎯"
  }
};

export default uiStringsKO;
