// Russian UI Strings for CivicSense Mobile App
// Русский - Строки интерфейса пользователя

import type { UIStrings } from './ui-strings';

export const uiStringsRU: UIStrings = {
  navigation: {
    back: 'Назад',
    close: 'Закрыть',
    menu: 'Меню',
    home: 'Главная',
    topics: 'Темы',
    quiz: 'Тест',
    profile: 'Профиль',
    settings: 'Настройки',
    bookmarks: 'Закладки',
    history: 'История',
  },

  topic: {
    loading: 'Загрузка сведений о теме...',
    loadingDetails: 'Загрузка сведений...',
    backToTopics: 'Вернуться к темам',
    share: 'Поделиться темой',
    bookmark: 'Добавить в закладки',
    removeBookmark: 'Удалить закладку',
    bookmarkThis: 'Добавить в закладки',
    translateThisPage: 'Перевести эту страницу',
    showOriginal: 'Показать оригинал',
    whyThisMatters: 'Почему это важно',
    sourcesAndReferences: 'Источники и ссылки',
    takingTheQuiz: 'Прохождение теста',
    startQuiz: 'Начать тест',
    questionsLabel: 'Вопросы',
    estimatedMinutesLabel: 'Прим. мин.',
    ratingLabel: 'Рейтинг',
    publishedLabel: 'Опубликовано',
    thinkYouGotIt: 'Думаете, что поняли?',
    testYourUnderstanding: 'Проверьте свое понимание этой темы и посмотрите, насколько хорошо вы усвоили ключевые концепции, которые мы рассмотрели.',
    noSourcesAvailable: 'Источники пока недоступны',
    noSourcesDescription: 'Источники и ссылки будут добавлены после проверки и верификации контента.',
    understandingSourceAnalysis: 'Понимание анализа источников',
    biasRatingsMeaning: 'Что означают рейтинги предвзятости?',
    credibilityPercentageMeaning: 'Что означает процент достоверности?',
    howRatingsDetermined: 'Как определяются эти рейтинги?',
    areRatingsPermanent: 'Эти рейтинги постоянны?',
    sourceAnalysisImportance: 'Почему это важно?',
  },

  translation: {
    selectLanguage: 'Выберите язык',
    languagePreferenceSaved: 'Ваша языковая настройка будет сохранена для будущих посещений',
    translating: 'Переводится...',
    translationComplete: 'Перевод завершен',
    translationError: 'Ошибка перевода',
    helpTranslate: 'Помочь с переводом',
    noTranslationAvailable: 'Перевод недоступен',
    loadingTranslations: 'Загрузка переводов...',
    checkingTranslations: 'Проверка существующих переводов...',
    savingTranslations: 'Сохранение переводов...',
    autoTranslating: 'Автоматический перевод...',
    translatingQuestion: 'Перевод вопроса',
    originalText: 'Оригинал',
    loadingExistingTranslations: 'Загрузка существующих переводов...',
    translateContent: 'Перевести контент',
    allQuestionsTranslated: 'Все вопросы уже переведены',
    translationNeeded: 'Требуется перевод',
    helpTranslateContent: 'Хотите помочь с переводом?',
    translationTest: 'Тест перевода',
    translationTestResult: 'Результат теста перевода',
    translationTestFailed: 'Тест перевода не пройден',
    initializingTranslationService: 'Инициализация службы перевода...',
  },

  sources: {
    analysisOverview: 'Обзор анализа',
    politicalBias: 'Политическая предвзятость',
    factualRating: 'Фактический рейтинг',
    transparency: 'Прозрачность',
    analysisSummary: 'Сводка анализа',
    topicRelevanceCheck: 'Проверка релевантности темы',
    validationDetails: 'Детали проверки',
    strengths: 'Сильные стороны',
    areasForImprovement: 'Области для улучшения',
    redFlags: 'Красные флаги',
    recommendations: 'Рекомендации',
    readFullArticle: 'Читать полную статью',
    loadingAnalysis: 'Загрузка анализа...',
    analyzed: 'ПРОАНАЛИЗИРОВАНО',
    credibility: 'Достоверность',
  },

  languages: {
    english: 'English',
    spanish: 'Español',
    chinese: '中文',
    vietnamese: 'Tiếng Việt',
    arabic: 'العربية',
    hindi: 'हिन्दी',
    french: 'Français',
    german: 'Deutsch',
    portuguese: 'Português',
    russian: 'Русский',
    japanese: '日本語',
    korean: '한국어',
    italian: 'Italiano',
  },

  actions: {
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Редактировать',
    share: 'Поделиться',
    copy: 'Копировать',
    download: 'Скачать',
    upload: 'Загрузить',
    refresh: 'Обновить',
    retry: 'Повторить',
    tryAgain: 'Попробовать снова',
    continue: 'Продолжить',
    next: 'Далее',
    previous: 'Назад',
    finish: 'Завершить',
    submit: 'Отправить',
    confirm: 'Подтвердить',
    yes: 'Да',
    no: 'Нет',
    ok: 'OK',
    dismiss: 'Отклонить',
  },

  status: {
    loading: 'Загрузка...',
    saving: 'Сохранение...',
    saved: 'Сохранено',
    error: 'Ошибка',
    success: 'Успех',
    warning: 'Предупреждение',
    info: 'Информация',
    completed: 'Завершено',
    failed: 'Не удалось',
    connecting: 'Подключение...',
    connected: 'Подключено',
    disconnected: 'Отключено',
    offline: 'Оффлайн',
    online: 'Онлайн',
    syncing: 'Синхронизация...',
    synced: 'Синхронизировано',
  },

  errors: {
    networkError: 'Ошибка сети. Проверьте ваше подключение.',
    serverError: 'Ошибка сервера. Попробуйте позже.',
    unknownError: 'Произошла неизвестная ошибка.',
    notFound: 'Контент не найден.',
    unauthorized: 'У вас нет доступа к этому контенту.',
    forbidden: 'Доступ к этому контенту запрещен.',
    timeout: 'Время запроса истекло. Попробуйте снова.',
    connectionLost: 'Соединение потеряно. Проверьте интернет.',
    invalidInput: 'Неверный ввод. Проверьте ваш ввод.',
    requiredField: 'Это поле обязательно.',
    loadingFailed: 'Не удалось загрузить контент.',
    savingFailed: 'Не удалось сохранить изменения.',
    uploadFailed: 'Загрузка не удалась.',
    downloadFailed: 'Скачивание не удалось.',
  },

  time: {
    now: 'сейчас',
    today: 'сегодня',
    yesterday: 'вчера',
    tomorrow: 'завтра',
    thisWeek: 'на этой неделе',
    lastWeek: 'на прошлой неделе',
    thisMonth: 'в этом месяце',
    lastMonth: 'в прошлом месяце',
    minutesAgo: 'минут назад',
    hoursAgo: 'часов назад',
    daysAgo: 'дней назад',
    weeksAgo: 'недель назад',
    monthsAgo: 'месяцев назад',
  },

  quiz: {
    question: 'Вопрос',
    questions: 'Вопросы',
    answer: 'Ответ',
    answers: 'Ответы',
    correct: 'Правильно',
    incorrect: 'Неправильно',
    explanation: 'Объяснение',
    hint: 'Подсказка',
    score: 'Счет',
    results: 'Результаты',
    startQuiz: 'Начать тест',
    nextQuestion: 'Следующий вопрос',
    previousQuestion: 'Предыдущий вопрос',
    finishQuiz: 'Завершить тест',
    retakeQuiz: 'Пройти тест заново',
    reviewAnswers: 'Просмотр ответов',
    timeRemaining: 'Оставшееся время',
    questionNumber: 'Вопрос',
    totalQuestions: 'Всего вопросов',
    correctAnswers: 'Правильные ответы',
    incorrectAnswers: 'Неправильные ответы',
    finalScore: 'Финальный счет',
  },

  accessibility: {
    skipToContent: 'Перейти к контенту',
    mainNavigation: 'Главная навигация',
    userMenu: 'Меню пользователя',
    darkModeToggle: 'Переключить темный режим',
    languageSelector: 'Выбор языка',
    closeDialog: 'Закрыть диалог',
    openMenu: 'Открыть меню',
    closeMenu: 'Закрыть меню',
    loadingContent: 'Загрузка контента',
    expandSection: 'Развернуть раздел',
    collapseSection: 'Свернуть раздел',
    playAudio: 'Воспроизвести аудио',
    pauseAudio: 'Приостановить аудио',
    stopAudio: 'Остановить аудио',
    increaseSpeed: 'Увеличить скорость',
    decreaseSpeed: 'Уменьшить скорость',
    goBack: 'Вернуться',
    openLink: 'Открыть ссылку',
    bookmark: 'Добавить эту тему в закладки',
    removeBookmark: 'Удалить закладку',
    dontSeeLanguage: 'Не видите ваш язык?',
    requestLanguage: 'Запросить новый язык или стать волонтёром для помощи с переводами',
    // Scanner animation strings
    analyzingContent: 'Анализ контента...',
    translatingToLanguage: 'Перевод на {language}...',
    optimizingLayout: 'Оптимизация макета...',
    elementsTranslated: 'Переведено {count} элементов',
  },
};

export default uiStringsRU; 