declare namespace NodeJS {
  interface ProcessEnv {
    // Environment
    NODE_ENV: 'development' | 'production' | 'test'
    VERCEL_ENV?: 'production' | 'preview' | 'development'
    
    // Navigation Feature Flags
    NEXT_PUBLIC_ENABLE_GLOBAL_SEARCH?: string
    NEXT_PUBLIC_ENABLE_HOME_NAVIGATION?: string
    NEXT_PUBLIC_ENABLE_CATEGORIES_NAVIGATION?: string
    NEXT_PUBLIC_ENABLE_MULTIPLAYER_NAVIGATION?: string
    NEXT_PUBLIC_ENABLE_SUPPORT_NAVIGATION?: string
    NEXT_PUBLIC_ENABLE_ABOUT_NAVIGATION?: string
    NEXT_PUBLIC_ENABLE_USER_MENU?: string
    NEXT_PUBLIC_ENABLE_CIVICS_TEST_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_QUIZ_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_SCENARIOS_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_PROGRESS_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_LEARNING_PODS_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_DASHBOARD_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_SETTINGS_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_ADMIN_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_THEME_TOGGLE_MENU_ITEM?: string
    NEXT_PUBLIC_ENABLE_MOBILE_MENU?: string
    NEXT_PUBLIC_ENABLE_MOBILE_HOME_ITEM?: string
    NEXT_PUBLIC_ENABLE_MOBILE_CATEGORIES_ITEM?: string
    NEXT_PUBLIC_ENABLE_MOBILE_SCENARIOS_ITEM?: string
    NEXT_PUBLIC_ENABLE_MOBILE_MULTIPLAYER_ITEM?: string
    NEXT_PUBLIC_ENABLE_MOBILE_SUPPORT_ITEM?: string
    
    // Premium Feature Flags
    NEXT_PUBLIC_ENABLE_CUSTOM_DECKS?: string
    NEXT_PUBLIC_ENABLE_HISTORICAL_PROGRESS?: string
    NEXT_PUBLIC_ENABLE_ADVANCED_ANALYTICS?: string
    NEXT_PUBLIC_ENABLE_SPACED_REPETITION?: string
    NEXT_PUBLIC_ENABLE_LEARNING_INSIGHTS?: string
    NEXT_PUBLIC_ENABLE_PRIORITY_SUPPORT?: string
    NEXT_PUBLIC_ENABLE_OFFLINE_MODE?: string
    NEXT_PUBLIC_ENABLE_DATA_EXPORT?: string
    NEXT_PUBLIC_ENABLE_PREMIUM_BADGES?: string
    NEXT_PUBLIC_ENABLE_UPGRADE_PROMPTS?: string
    NEXT_PUBLIC_ENABLE_PREMIUM_ONBOARDING?: string
    NEXT_PUBLIC_ENABLE_BILLING_MANAGEMENT?: string
    NEXT_PUBLIC_ENABLE_AI_GENERATED_CONTENT?: string
    NEXT_PUBLIC_ENABLE_PERSONALIZED_RECOMMENDATIONS?: string
    NEXT_PUBLIC_ENABLE_ADVANCED_QUIZ_MODES?: string
    NEXT_PUBLIC_ENABLE_COLLABORATIVE_FEATURES?: string
    NEXT_PUBLIC_ENABLE_INTEGRATIONS_ACCESS?: string
    
    // Core Feature Flags
    NEXT_PUBLIC_ENABLE_MULTIPLAYER?: string
    NEXT_PUBLIC_ENABLE_LEARNING_PODS?: string
    NEXT_PUBLIC_ENABLE_SCENARIOS?: string
    NEXT_PUBLIC_ENABLE_CIVICS_TEST?: string
    NEXT_PUBLIC_ENABLE_QUIZZES?: string
    NEXT_PUBLIC_ENABLE_SURVEYS?: string
    NEXT_PUBLIC_ENABLE_DOCUMENTATION_SECTION?: string
    NEXT_PUBLIC_ENABLE_ADMIN_ACCESS?: string
    NEXT_PUBLIC_ENABLE_DEBUG_ROUTES?: string
    NEXT_PUBLIC_ENABLE_DEBUG_PANELS?: string
    NEXT_PUBLIC_ENABLE_SIGN_UP_FLOW?: string
    NEXT_PUBLIC_ENABLE_SOCIAL_LOGIN?: string
    NEXT_PUBLIC_ENABLE_GUEST_ACCESS?: string
    NEXT_PUBLIC_ENABLE_NOTIFICATIONS?: string
    NEXT_PUBLIC_ENABLE_EMAIL_MARKETING?: string
    NEXT_PUBLIC_ENABLE_CHAT_SUPPORT?: string
    NEXT_PUBLIC_ENABLE_ANALYTICS_TRACKING?: string
    NEXT_PUBLIC_ENABLE_ERROR_REPORTING?: string
    NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING?: string
    NEXT_PUBLIC_ENABLE_EXPERIMENTAL_FEATURES?: string
    NEXT_PUBLIC_ENABLE_BETA_FEATURES?: string
    NEXT_PUBLIC_ENABLE_ALPHA_FEATURES?: string
  }
} 