-- Insert TikTok regulation topic
INSERT INTO question_topics (
    topic_id,
    topic_title,
    description,
    why_this_matters,
    emoji,
    date,
    day_of_week,
    categories
) VALUES (
    'tiktok_regulation_2024',
    'TikTok Regulation and Potential Ban',
    'The ongoing debate and legislative action on TikTok regulation and potential ban in the United States (2023-2024). Congress has passed legislation requiring TikTok''s parent company to divest or face a ban, citing national security concerns about foreign data access and influence.',
    '<ul><li><strong>Digital Privacy:</strong> This legislation affects how your personal data is protected and who can access it online.</li><li><strong>Free Speech:</strong> Understanding the balance between national security and First Amendment rights in the digital age.</li><li><strong>Economic Impact:</strong> Millions of creators and businesses depend on TikTok for income, affecting the digital economy.</li><li><strong>Democratic Process:</strong> This showcases how Congress responds to national security concerns in the modern digital landscape.</li></ul>',
    '📱',
    '2024-03-15',
    'Friday',
    '["Government", "National Security", "Constitutional Rights", "Media Literacy", "Legislative Process"]'::jsonb
);

-- Insert TikTok regulation questions
INSERT INTO questions (
    topic_id,
    question_number,
    question_type,
    category,
    question,
    option_a,
    option_b,
    option_c,
    option_d,
    correct_answer,
    hint,
    explanation,
    sources,
    difficulty_level
) VALUES 
(
    'tiktok_regulation_2024',
    1,
    'multiple_choice',
    'Government',
    'Which federal body passed legislation in 2024 requiring TikTok''s parent company to divest or face a ban in the U.S.?',
    'The Supreme Court',
    'The House of Representatives',
    'The Federal Communications Commission',
    'The Department of Justice',
    'option_b',
    'It''s the legislative chamber where bills often originate.',
    'In March 2024, the U.S. House of Representatives passed a bill targeting TikTok, citing national security concerns.',
    '[{"name": "New York Times - TikTok House Vote", "url": "https://www.nytimes.com/2024/03/13/technology/tiktok-house-vote.html"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    2,
    'true_false',
    'National Security',
    'True or False: The primary concern cited by lawmakers for regulating TikTok is its potential to allow foreign governments access to American user data.',
    null,
    null,
    null,
    null,
    'true',
    'Think about the main arguments made by Congress.',
    'Lawmakers have expressed concern that TikTok''s Chinese ownership could allow the Chinese government to access U.S. user data or influence content.',
    '[{"name": "CNN - TikTok Ban Explained", "url": "https://www.cnn.com/2024/03/13/tech/tiktok-ban-explained/index.html"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    3,
    'multiple_choice',
    'Constitutional Rights',
    'Which constitutional amendment is most frequently cited in debates about banning TikTok due to concerns over free speech?',
    'First Amendment',
    'Second Amendment',
    'Fourth Amendment',
    'Tenth Amendment',
    'option_a',
    'It protects freedom of expression.',
    'The First Amendment protects freedom of speech, which critics argue could be infringed by banning a social media platform.',
    '[{"name": "NPR - TikTok First Amendment", "url": "https://www.npr.org/2024/03/14/tech/tiktok-ban-first-amendment"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    4,
    'multiple_choice',
    'Legislative Process',
    'After passing the House, where does a bill go next in the federal legislative process?',
    'The President',
    'The Senate',
    'The Supreme Court',
    'State Legislatures',
    'option_b',
    'It''s the other chamber of Congress.',
    'A bill must pass both the House and Senate before going to the President for approval.',
    '[{"name": "Congress.gov - How Laws Are Made", "url": "https://www.congress.gov/resources/display/content/How+Our+Laws+Are+Made"}]'::jsonb,
    1
),
(
    'tiktok_regulation_2024',
    5,
    'multiple_choice',
    'Economics',
    'What is a potential economic impact of banning TikTok in the U.S.?',
    'Increase in U.S. tech jobs',
    'Loss of advertising revenue for creators',
    'Decrease in smartphone sales',
    'Rise in oil prices',
    'option_b',
    'Think about who earns money on TikTok.',
    'Many American creators and businesses rely on TikTok for income through advertising and sponsorships.',
    '[{"name": "Wall Street Journal - TikTok Creator Economy", "url": "https://www.wsj.com/tech/tiktok-ban-creators-economy"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    6,
    'short_answer',
    'Media Literacy',
    'The term for spreading false or misleading information online, often cited as a concern with social media platforms like TikTok, is ____.',
    null,
    null,
    null,
    null,
    'disinformation',
    'It''s not misinformation, but a more deliberate act.',
    'Disinformation is intentionally false information spread to deceive people, a key concern in regulating social media.',
    '[{"name": "Brookings - Disinformation on Social Media", "url": "https://www.brookings.edu/articles/disinformation-on-social-media/"}]'::jsonb,
    3
),
(
    'tiktok_regulation_2024',
    7,
    'multiple_choice',
    'Foreign Policy',
    'Which country is home to ByteDance, TikTok''s parent company?',
    'United States',
    'China',
    'South Korea',
    'Japan',
    'option_b',
    'It''s a major global economic power.',
    'ByteDance is headquartered in Beijing, China, fueling U.S. national security concerns.',
    '[{"name": "Reuters - TikTok ByteDance China", "url": "https://www.reuters.com/technology/tiktok-bytedance-china"}]'::jsonb,
    1
),
(
    'tiktok_regulation_2024',
    8,
    'multiple_choice',
    'Historical Precedent',
    'Which previous U.S. law restricted foreign ownership of media outlets, similar to concerns raised about TikTok?',
    'The Smith Act',
    'The Foreign Agents Registration Act',
    'The Communications Act of 1934',
    'The Espionage Act',
    'option_c',
    'It''s a foundational law for U.S. communications.',
    'The Communications Act limited foreign ownership in U.S. broadcast stations, reflecting longstanding concerns about foreign influence.',
    '[{"name": "FCC - Foreign Ownership Rules", "url": "https://www.fcc.gov/foreign-ownership-broadcast"}]'::jsonb,
    3
),
(
    'tiktok_regulation_2024',
    9,
    'true_false',
    'Civic Action',
    'True or False: U.S. citizens can contact their representatives to express their views on the TikTok legislation.',
    null,
    null,
    null,
    null,
    'true',
    'Think about how democracy works.',
    'Constituents are encouraged to contact their elected officials to share opinions on pending legislation.',
    '[{"name": "House.gov - Find Your Representative", "url": "https://www.house.gov/representatives/find-your-representative"}]'::jsonb,
    1
),
(
    'tiktok_regulation_2024',
    10,
    'multiple_choice',
    'Judicial Review',
    'If TikTok is banned and the company sues, which branch of government would decide if the ban is constitutional?',
    'Legislative',
    'Executive',
    'Judicial',
    'Administrative',
    'option_c',
    'It interprets the law.',
    'The judicial branch, including federal courts, reviews the constitutionality of laws and executive actions.',
    '[{"name": "US Courts - Court Role", "url": "https://www.uscourts.gov/about-federal-courts/court-role-and-structure"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    11,
    'multiple_choice',
    'Media Literacy',
    'Which of the following is a recommended strategy for evaluating the credibility of information found on TikTok?',
    'Rely on the number of likes',
    'Check the creator''s nationality',
    'Cross-reference with reputable sources',
    'Trust viral content',
    'option_c',
    'It''s a key media literacy skill.',
    'Verifying information with multiple reputable sources helps prevent the spread of misinformation.',
    '[{"name": "Common Sense Media - Spot Fake News", "url": "https://www.commonsense.org/education/articles/how-to-spot-fake-news"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    12,
    'multiple_choice',
    'Public Policy',
    'Which federal agency is primarily responsible for regulating communications and media in the U.S.?',
    'Federal Trade Commission',
    'Federal Communications Commission',
    'Department of State',
    'Department of Commerce',
    'option_b',
    'Its acronym is FCC.',
    'The FCC oversees communications by radio, television, wire, satellite, and cable in the U.S.',
    '[{"name": "FCC - About Overview", "url": "https://www.fcc.gov/about/overview"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    13,
    'multiple_choice',
    'Civil Rights',
    'Which group has argued that a TikTok ban could disproportionately affect marginalized voices?',
    'Tech companies',
    'Civil liberties organizations',
    'Foreign governments',
    'Political parties',
    'option_b',
    'They focus on rights and freedoms.',
    'Groups like the ACLU argue that TikTok provides a platform for marginalized communities to be heard.',
    '[{"name": "ACLU - TikTok Free Expression", "url": "https://www.aclu.org/news/free-speech/tiktok-ban-threatens-free-expression"}]'::jsonb,
    3
),
(
    'tiktok_regulation_2024',
    14,
    'multiple_choice',
    'Government',
    'Which of the following is NOT a power granted to Congress under the U.S. Constitution?',
    'Regulate interstate commerce',
    'Declare war',
    'Appoint Supreme Court Justices',
    'Levy taxes',
    'option_c',
    'Think about checks and balances.',
    'The President appoints Justices, with Senate confirmation; Congress does not have this power.',
    '[{"name": "National Archives - Constitution", "url": "https://www.archives.gov/founding-docs/constitution-transcript"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    15,
    'multiple_choice',
    'National Security',
    'Which U.S. federal agency has warned about potential national security risks posed by TikTok?',
    'Department of Agriculture',
    'Department of Defense',
    'Federal Reserve',
    'Department of Homeland Security',
    'option_d',
    'It''s responsible for protecting the U.S. from threats.',
    'DHS has raised concerns about data privacy and foreign influence via TikTok.',
    '[{"name": "DHS Statement on TikTok", "url": "https://www.dhs.gov/news/2023/03/15/dhs-statement-tiktok"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    16,
    'true_false',
    'Electoral Systems',
    'True or False: Social media platforms like TikTok have been used to influence public opinion during U.S. elections.',
    null,
    null,
    null,
    null,
    'true',
    'Consider recent election cycles.',
    'Social media has been used to spread information and misinformation during elections, raising concerns about foreign interference.',
    '[{"name": "CISA - Foreign Interference", "url": "https://www.cisa.gov/news-events/news/foreign-interference-us-elections"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    17,
    'multiple_choice',
    'Policy Analysis',
    'Which of the following is a possible alternative to an outright ban on TikTok?',
    'Mandating U.S. data storage',
    'Blocking all social media',
    'Nationalizing TikTok',
    'Banning smartphones',
    'option_a',
    'Think about data privacy solutions.',
    'Some propose requiring TikTok to store U.S. data domestically and undergo security reviews instead of banning it.',
    '[{"name": "CNBC - TikTok Bill Alternatives", "url": "https://www.cnbc.com/2024/03/13/tiktok-bill-alternatives"}]'::jsonb,
    3
),
(
    'tiktok_regulation_2024',
    18,
    'multiple_choice',
    'Civic Participation',
    'What is one way young people have used TikTok for civic engagement?',
    'Organizing voter registration drives',
    'Selling products',
    'Streaming video games',
    'Posting only dance videos',
    'option_a',
    'Think about political participation.',
    'TikTok has been used to mobilize young voters and promote civic participation.',
    '[{"name": "Pew Research - Social Media Civic Engagement", "url": "https://www.pewresearch.org/internet/2023/09/19/social-media-and-civic-engagement/"}]'::jsonb,
    2
),
(
    'tiktok_regulation_2024',
    19,
    'multiple_choice',
    'Media Literacy',
    'Which term describes the use of algorithms to tailor content to individual users, a key feature of TikTok?',
    'Encryption',
    'Personalization',
    'Open source',
    'Censorship',
    'option_b',
    'It''s about customizing content.',
    'TikTok''s algorithm personalizes content feeds, raising questions about echo chambers and information diversity.',
    '[{"name": "Nature - Algorithm Personalization", "url": "https://www.nature.com/articles/s41599-023-01728-7"}]'::jsonb,
    3
),
(
    'tiktok_regulation_2024',
    20,
    'multiple_choice',
    'Historical Precedent',
    'Which U.S. President previously attempted to ban TikTok via executive order in 2020?',
    'Barack Obama',
    'Joe Biden',
    'Donald Trump',
    'George W. Bush',
    'option_c',
    'It happened during the COVID-19 pandemic.',
    'President Trump signed an executive order to ban TikTok, but it was blocked in federal courts.',
    '[{"name": "New York Times - Trump TikTok Ban", "url": "https://www.nytimes.com/2020/08/06/technology/trump-tiktok-ban.html"}]'::jsonb,
    2
); 