-- =========================================================
-- SEED DEMOCRACY THREAT ASSESSMENT FRAMEWORK
-- Based on the CivicSense Democracy Threat Assessment Framework
-- =========================================================

BEGIN;

-- Insert the main framework
INSERT INTO assessment_frameworks (
    id,
    framework_name,
    framework_slug,
    description,
    framework_type,
    scoring_system,
    methodology_url,
    academic_sources,
    created_by,
    version
) VALUES (
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'CivicSense Democracy Threat Assessment Framework',
    'civicsense_authoritarianism',
    'A research-based early warning system for democratic backsliding',
    'authoritarianism',
    '{"type": "binary", "scale": "0-20"}',
    'https://civicsense.org/assessment-framework',
    '["Steven Levitsky & Daniel Ziblatt - How Democracies Die", "Timothy Snyder - On Tyranny", "Robert Paxton - The Anatomy of Fascism", "Freedom House Democracy indicators", "V-Dem Project", "Hannah Arendt - The Origins of Totalitarianism"]',
    'system_seed',
    '1.0'
) ON CONFLICT (framework_slug) DO NOTHING;

-- Insert the United States as an assessed entity
INSERT INTO assessed_entities (
    id,
    entity_name,
    entity_slug,
    entity_type,
    iso_code,
    metadata
) VALUES (
    'e47ac10b-58cc-4372-a567-0e02b2c3d479',
    'United States of America',
    'united_states',
    'country',
    'US',
    '{"population": 331900000, "capital": "Washington, D.C.", "government_type": "Federal Republic"}'
) ON CONFLICT (entity_slug) DO NOTHING;

-- Insert indicator categories
INSERT INTO indicator_categories (
    id,
    framework_id,
    category_name,
    category_slug,
    description,
    severity_level,
    color_code,
    icon,
    threshold_description,
    display_order
) VALUES 
(
    'cat1-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'Early Warning Signs',
    'level1_early_warning',
    'Democracy Under Stress - Initial signs of authoritarian behavior',
    1,
    '#FFA500',
    'AlertTriangle',
    '3-4 indicators typical for healthy democracies',
    1
),
(
    'cat2-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'Democratic Erosion',
    'level2_democratic_erosion',
    'Institutions Under Attack - Systematic undermining of democratic institutions',
    2,
    '#FF4500',
    'Shield',
    '6-8 indicators = significant concern',
    2
),
(
    'cat3-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'Authoritarian Consolidation',
    'level3_authoritarian_consolidation',
    'Democracy in Crisis - Active authoritarian takeover',
    3,
    '#DC143C',
    'AlertOctagon',
    '12+ indicators = democracy at severe risk',
    3
),
(
    'cat4-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'Fascist State',
    'level4_fascist_state',
    'Democracy Eliminated - Full authoritarian regime',
    4,
    '#8B0000',
    'Skull',
    '18+ indicators = authoritarian regime',
    4
) ON CONFLICT (framework_id, category_slug) DO NOTHING;

-- Insert Level 1 indicators (Early Warning Signs)
INSERT INTO indicators (
    id,
    framework_id,
    category_id,
    indicator_name,
    indicator_slug,
    description,
    evidence_threshold,
    measurement_type,
    measurement_config,
    weight,
    display_order,
    historical_context,
    civic_education_angle,
    status,
    current_status
) VALUES 
(
    'ind1-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat1-47ac-10b5-8cc4-372a567',
    'Rejection of Democratic Rules',
    'rejection_democratic_rules',
    'Leaders who explicitly reject democratic norms like accepting election results',
    'Public statements refusing to commit to peaceful transfer of power',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    1,
    '2020 election denial, January 6th',
    'Highlights importance of respecting election results',
    'TRIGGERED',
    'Leaders continue to question election integrity without evidence'
),
(
    'ind2-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat1-47ac-10b5-8cc4-372a567',
    'Denial of Legitimacy of Political Opponents',
    'denial_legitimacy_opponents',
    'Treating opposition as enemies rather than legitimate competitors',
    'Consistent rhetoric portraying opponents as traitors/criminals',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    2,
    'Common tactic in authoritarian movements',
    'Teaches importance of loyal opposition',
    'TRIGGERED',
    '"Enemy within," prosecution threats'
),
(
    'ind3-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat1-47ac-10b5-8cc4-372a567',
    'Tolerance/Encouragement of Violence',
    'tolerance_encouragement_violence',
    'Failure to condemn political violence or using inflammatory rhetoric',
    'Refusing to condemn violence by supporters or inciting language',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    3,
    'January 6th, "fight like hell" rhetoric',
    'Emphasizes peaceful conflict resolution',
    'TRIGGERED',
    'History of inflammatory rhetoric and failure to condemn violence'
),
(
    'ind4-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat1-47ac-10b5-8cc4-372a567',
    'Readiness to Curtail Civil Liberties',
    'readiness_curtail_civil_liberties',
    'Restricting press freedom, protest rights, or opposition activities',
    'Laws or policies restricting constitutional rights',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    4,
    'Press access restrictions, protest responses',
    'Importance of First Amendment protections',
    'TRIGGERED',
    'Press access restrictions, protest responses documented'
) ON CONFLICT (framework_id, indicator_slug) DO NOTHING;

-- Insert Level 2 indicators (Democratic Erosion)
INSERT INTO indicators (
    id,
    framework_id,
    category_id,
    indicator_name,
    indicator_slug,
    description,
    evidence_threshold,
    measurement_type,
    measurement_config,
    weight,
    display_order,
    historical_context,
    civic_education_angle,
    status,
    current_status
) VALUES 
(
    'ind5-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat2-47ac-10b5-8cc4-372a567',
    'Capturing the Courts',
    'capturing_courts',
    'Packing courts with loyalists, undermining judicial independence',
    'Appointing judges based on loyalty over qualifications',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    5,
    'Supreme Court appointments, lower court influence',
    'Understanding judicial independence',
    'PARTIAL',
    'Supreme Court appointments, lower court influence concerns'
),
(
    'ind6-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat2-47ac-10b5-8cc4-372a567',
    'Weaponizing Law Enforcement',
    'weaponizing_law_enforcement',
    'Using FBI, DOJ, or police for political purposes',
    'Targeting opponents while protecting allies',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    6,
    'DOJ investigations, selective enforcement',
    'Understanding rule of law and equal justice',
    'TRIGGERED',
    'DOJ investigations targeting opponents, selective enforcement patterns'
),
(
    'ind7-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat2-47ac-10b5-8cc4-372a567',
    'Buying Off Media & Business Elites',
    'buying_off_media_business',
    'Co-opting media owners and business leaders for political support',
    'Media outlets changing coverage due to owner pressure',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    7,
    'Some media consolidation concerns',
    'Understanding media independence and democracy',
    'PARTIAL',
    'Some concerning patterns of media ownership influence'
),
(
    'ind8-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat2-47ac-10b5-8cc4-372a567',
    'Attacking Election Integrity',
    'attacking_election_integrity',
    'Undermining voting systems, ballot access, or election administration',
    'Laws restricting voting or election administration changes',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    8,
    'Voting restrictions, election official pressure',
    'Understanding free and fair elections',
    'TRIGGERED',
    'Voting restrictions, election official pressure documented'
),
(
    'ind9-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat2-47ac-10b5-8cc4-372a567',
    'Dismantling Oversight Mechanisms',
    'dismantling_oversight',
    'Firing inspectors general, ethics officers, or independent watchdogs',
    'Mass removal of oversight officials',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    9,
    '17 IGs fired in one week',
    'Understanding government accountability',
    'TRIGGERED',
    'Mass firing of inspectors general and oversight officials'
),
(
    'ind10-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat2-47ac-10b5-8cc4-372a567',
    'Politicizing Civil Service',
    'politicizing_civil_service',
    'Replacing career officials with political loyalists',
    'Mass firings/replacements of non-political positions',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    10,
    'Schedule F plans, agency purges',
    'Understanding professional civil service',
    'TRIGGERED',
    'Schedule F implementation and civil service politicization'
) ON CONFLICT (framework_id, indicator_slug) DO NOTHING;

-- Insert Level 3 indicators (Authoritarian Consolidation)
INSERT INTO indicators (
    id,
    framework_id,
    category_id,
    indicator_name,
    indicator_slug,
    description,
    evidence_threshold,
    measurement_type,
    measurement_config,
    weight,
    display_order,
    historical_context,
    civic_education_angle,
    status,
    current_status
) VALUES 
(
    'ind11-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat3-47ac-10b5-8cc4-372a567',
    'Eliminating Federalism',
    'eliminating_federalism',
    'Centralizing power, overriding state/local authority',
    'Federal intervention in state governance',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    11,
    'National Guard federalization',
    'Understanding federalism and separation of powers',
    'TRIGGERED',
    'Federal override of state authority in multiple areas'
),
(
    'ind12-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat3-47ac-10b5-8cc4-372a567',
    'Creating Parallel Power Structures',
    'creating_parallel_power',
    'Establishing informal authority outside constitutional framework',
    'Unofficial advisors making policy, bypassing institutions',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    12,
    'Informal advisors, Mar-a-Lago meetings',
    'Understanding constitutional governance',
    'PARTIAL',
    'Evidence of informal power structures bypassing official channels'
),
(
    'ind13-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat3-47ac-10b5-8cc4-372a567',
    'Mass Deportations/Targeting Groups',
    'mass_deportations_targeting',
    'Using state power to target ethnic, political, or social groups',
    'Mass roundups or systematic targeting',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    13,
    'Immigration raids, denaturalization',
    'Understanding equal protection and civil rights',
    'TRIGGERED',
    'Large-scale deportation operations and systematic targeting'
),
(
    'ind14-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat3-47ac-10b5-8cc4-372a567',
    'Militarizing Domestic Policy',
    'militarizing_domestic_policy',
    'Using military for domestic law enforcement or political purposes',
    'Troops deployed for non-emergency domestic issues',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    14,
    'National Guard deployments',
    'Understanding Posse Comitatus and civilian authority',
    'PARTIAL',
    'Concerning patterns of military involvement in domestic affairs'
),
(
    'ind15-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat3-47ac-10b5-8cc4-372a567',
    'Controlling Information Flow',
    'controlling_information_flow',
    'State control over information, propaganda, censorship',
    'Government controlling or restricting information access',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    15,
    'Platform pressure, media restrictions',
    'Understanding free press and information access',
    'PARTIAL',
    'Evidence of pressure on platforms and media restrictions'
),
(
    'ind16-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat3-47ac-10b5-8cc4-372a567',
    'Economic Control & Corruption',
    'economic_control_corruption',
    'Using government power for personal enrichment or control',
    'Direct financial benefit from government position',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    16,
    'Emoluments violations, family enrichment',
    'Understanding government ethics and corruption',
    'TRIGGERED',
    'Documented patterns of using government position for personal gain'
) ON CONFLICT (framework_id, indicator_slug) DO NOTHING;

-- Insert Level 4 indicators (Fascist State)
INSERT INTO indicators (
    id,
    framework_id,
    category_id,
    indicator_name,
    indicator_slug,
    description,
    evidence_threshold,
    measurement_type,
    measurement_config,
    weight,
    display_order,
    historical_context,
    civic_education_angle,
    status,
    current_status
) VALUES 
(
    'ind17-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat4-47ac-10b5-8cc4-372a567',
    'Suspending Elections or Declaring Emergencies',
    'suspending_elections_emergencies',
    'Canceling elections or using emergency powers to extend rule',
    'Actual suspension of electoral process',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    17,
    'Emergency declarations, election postponements',
    'Understanding democratic continuity',
    'NOT_YET',
    'Elections still occurring regularly'
),
(
    'ind18-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat4-47ac-10b5-8cc4-372a567',
    'Mass Arrest of Opposition',
    'mass_arrest_opposition',
    'Systematic imprisonment of political opponents',
    'Coordinated arrests of opposition leaders',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    18,
    'Mass arrests, political prisoners',
    'Understanding political freedom and due process',
    'NOT_YET',
    'Threats made but not systematically implemented'
),
(
    'ind19-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat4-47ac-10b5-8cc4-372a567',
    'Complete Media Control',
    'complete_media_control',
    'All major media outlets controlled by or supporting the regime',
    'No independent media allowed to operate',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    19,
    'Media shutdowns, licensing restrictions',
    'Understanding press freedom',
    'NOT_YET',
    'Independent media still exists but under pressure'
),
(
    'ind20-47ac-10b5-8cc4-372a567',
    'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    'cat4-47ac-10b5-8cc4-372a567',
    'Totalitarian Social Control',
    'totalitarian_social_control',
    'Government control over all aspects of social life',
    'Surveillance state, elimination of civil society',
    'binary',
    '{"options": ["TRIGGERED", "PARTIAL", "NOT_YET"]}',
    1.0,
    20,
    'Mass surveillance, organization bans',
    'Understanding civil liberties and social freedom',
    'NOT_YET',
    'Civil society still exists but increasingly constrained'
) ON CONFLICT (framework_id, indicator_slug) DO NOTHING;

COMMIT; 